### ISSUE TITLE
Extract the release parts as generic step to be reused by other projects

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#100]
@pmbethe09 asked me some time ago if he could reuse the release pipeline of CI to release buildifier, this is a neat idea if we can extract the push release part of bazel and make it available to other project. I am pretty sure other like @xingao267 could be interested too.

**Comment by achew22** [comment]
@damienmg, thanks for taking the time to look into this with me.

The objectives:
 * To create a reusable release process for Bazel adjacent projects that allows expedient release of code.

The requirements:
 * Able to compile Go binary and emit build artifacts (I believe all these tools are written in Go right now, but that is not an indelible fact of nature)
 * Go artifacts must be able to be built as static binaries for multiple OSes (I think rules_go either supports this now or will very soon with their crosstool support for rules_go)
 * Build artifacts must be able to be uploaded to Github to be served under the "releases" tab.

Nice to haves (sorted by preference):
 * Automatically uploading to the releases tab in Github as a robot account.
 * Automatically run when a new tag is pushed to Github.
 * The ability to publish to the debian repo that is already in place for Bazel releases.
 * The ability to run arbitrary programs for uploading to domain specific repos (NPM, PIP, Gems, etc.).

**Comment by achew22** [comment]
@damienmg Do you have any thoughts on this?

**Comment by damienmg** [comment]
Sorry I though I answered.

Build artifacts should be buildable for Bazel on our side. Which is the case for all those tools. We can build the binary on all the platform available on CI without cross compilation (we can also configure the job to do cross-compilation). We have a step to upload the release tab of Github and one to upload to releases.bazel.build (which is backed by GCS so available in China, more reliable and faster than Github)

On the nice to have:
  1. and 2. are the plan. We believe than we should do 3, so people can have bazel installed with a set of tools with a simple setup. The last point (4.) might be trickier, we might want to think of run targets that bazel can run maybe?

**Comment by damienmg** [comment]
Also we are going to start by extending the job to push the website so we can automate push to all our website then we will think of adding release features to it.

**Comment by achew22** [comment]
Is there somewhere I can track that progress?

**Comment by damienmg** [comment]
In that bug, unfortunately it is not yet scheduled as you see. I'll share
planning as soon as I have it but don't expect this before next quarter.

**Comment by buchgr** [comment]
closing this, since we are moving away from jenkins to a new release process.
