### ISSUE TITLE
Update the default Xcode?

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#1001]
https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#macos-using-a-specific-version-of-xcode seems to suggest not setting an explicit value, but the current default seems to be Xcode 11.1, which I believe was Oct of last year?

**Comment by philwo** [comment]
I pushed a change to flip default Xcode to 11.7 in the testing org, let's see how it goes...

**Comment by philwo** [comment]
I verified that these pipelines are green with Xcode 11.7, so I'm going ahead with making it the default in Bazel CI:

- [X] Bazel postsubmit
- [X] rules_swift
- [X] rules_apple
- [X] apple_support
- [X] Tulsi
