### ISSUE TITLE
Can't find kythe installation on docker image `ubuntu2004-java11-kythe`

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/continuous-integration#1007]
`kythe` is [installed at `/opt/kythe`](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/docker/ubuntu2004/Dockerfile#L136) for image `ubuntu2004-java11-kythe`. However, container is [mounted with a volume `/opt:/opt:ro`](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/bazelci.py#L1955) which makes `/opt` directory inside container is actually host's `/opt` directory. We can't access `kythe` inside container.

Maybe we can install `kythe` to another directory such as `/var/lib/kythe` to avoid conflicts?

**Comment by philwo** [comment]
@coeuvre Good catch. Ideally I would like to get away from the `/opt` mount, but the Android SDK and NDK are so big... last time we put them into the container directly, the download and especially extraction took a very long time. (Just so you know the history for this.)

Can we put it into `/usr/local/kythe`? Feel free to send a PR to the Dockerfile and you can also build and push the `ubuntu2004` containers if you like - they are not yet used in production. :)
