### ISSUE TITLE
Builds requiring numpy on MacOS fail

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1027]
Failing:
Bazel Federation (rules_python) on Mac
bazel-bench on Mac

Logs:
https://buildkite.com/bazel/bazel-bench/builds/669#8502fcfe-e487-49b2-9483-7d4ead6914a2
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1617#8068fcf6-58e0-4f1f-9f17-d4a6efc4abdf

Error at the end of the log:
"error: library dfftpack has Fortran sources but no Fortran compiler found"

**Comment by philwo** [comment]
Indeed, it looks like the Fortran compiler was lost during the last system maintenance. Not that I knew that we ever had one installed. 😅 

I'll install it on the machines later today to fix this.

**Comment by comius** [comment]
rules_docker is also failing on Mac since Friday
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1617#e7d3c6a4-462c-4741-ae0c-989fbc406e1e

Something changed with docker? Logs don't show anything definite, except that only on MAC sha sums are different.

**Comment by philwo** [comment]
@comius Whoah. No idea regarding Docker. :/

@smukherj1 Do you know what might cause this?

**Comment by smukherj1** [comment]
> @comius Whoah. No idea regarding Docker. :/
> 
> @smukherj1 Do you know what might cause this?

I looked into this a little bit. Some notes [here](https://github.com/bazelbuild/rules_docker/pull/1600#issuecomment-681924702).

Basically something's broken between rules_docker & RBE causing erroneous cache hits in Linux while the Mac CI fails. Need to figure out:
1. What's the missing dependency causing us to get erroneous remote cache hits?
2. What changed to cause the change in image digest?

**Comment by philwo** [comment]
I'm installing the Fortran compiler on the testing Macs now, I hope this will not break anything and fix this... will report back.

**Comment by philwo** [comment]
Fixed by installing the Fortran compiler.
