### ISSUE TITLE
Support for go-1.15 version

### ISSUE THREAD

**Issue by gkousik** [bazelbuild/continuous-integration#1030]
We are using bazel-ci in https://github.com/bazelbuild/remote-apis-sdks repository. One of our use cases it to support `go build ./...` of the repository in addition to `bazel build //...`.

We test to make sure that `go build` works as part of CI. We would like to use a new API from `go.1.15` but it seems that the latest version of go that is supported in `ubuntu1804` platform is `go-1.13`.

What's the recommended way to go about using latest go version? I couldn't find documentation about this in https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md.

I have a pull request here https://github.com/bazelbuild/remote-apis-sdks/pull/175 that manually downloads and installs the latest go version but it seems that it would be better if the latest version of go is pre-installed in the image / if we could pick the version of go we want.

**Comment by atetubou** [comment]
There is code like
https://github.com/bazelbuild/continuous-integration/blob/b2b6568edf43303870efb36cbe9c2c04206a3f5d/buildkite/docker/ubuntu1804/Dockerfile#L127-L129
but it actually doesn't install Go?

**Comment by philwo** [comment]
I'm happy to upgrade Go on the machines to the latest version. It'll take me a day or so, as I have to finish other things today. Please ping me here on this issue if I don't follow up.

@atetubou Yes, indeed - we mount the Go installation from the host system, because otherwise our Docker containers would become very large.

**Comment by atetubou** [comment]
@philwo ping? how long will it take?

**Comment by philwo** [comment]
I'm building the images now, it should be done in ~2 hours or so. I'll let you know here. :)

Just to confirm - you only need this on Linux, right?

**Comment by atetubou** [comment]
Thank you!

> Just to confirm - you only need this on Linux, right?

Yes, as long as https://github.com/bazelbuild/remote-apis-sdks uses only linux in their CI.

**Comment by gkousik** [comment]
Yeah we use `ubuntu1804` platform - https://github.com/bazelbuild/remote-apis-sdks/blob/master/.bazelci/presubmit.yml#L16

**Comment by philwo** [comment]
I pushed the new VMs and containers to the staging area of Bazel CI, will check the results in a few hours and if all looks good, flip them over to production CI. 👍

**Comment by philwo** [comment]
This is done! The default Go version in the Docker containers is now 1.15.2. Please give it a try :)

Commits:
- https://github.com/bazelbuild/continuous-integration/commit/2cf26cd0e46610bd9c9eaab1aa9586d40367e83f 
- https://github.com/bazelbuild/continuous-integration/commit/b74b647ac00fc2b83174f6ec1269bf8ea9c6880a

**Comment by atetubou** [comment]
Thank you! That worked in my PR.
