### ISSUE TITLE
Linux (CentOS?) images should have `rpmbuild` installed

### ISSUE THREAD

**Issue by nacl** [bazelbuild/continuous-integration#1039]
In bazelbuild/rules_pkg#183, we have observed that the buildkite images do not have `rpmbuild(8)` in them, so we currently cannot run any RPM building tests in CI.

This can be solved by:

1) Building `rpmbuild` and related tools within `rules_pkg`
2) Build a custom rpm-building tool in `rules_pkg`
3) Including `rpmbuild` in one or more of the buildkite images

Of these, 1) and 2) are likely to be difficult to implement, whereas 3) should be relatively simple.  It should just be small addition to the package list.

**Comment by philwo** [comment]
If it’s documented here in the README.md that these rules need rpmbuild installed, I can install it in the containers, no problem. 👍

**Comment by philwo** [comment]
I'm pushing new containers with rpmbuild installed in ~30 minutes or so.

**Comment by philwo** [comment]
CentOS 7 containers have `rpmbuild` installed now.
