### ISSUE TITLE
Add CI support for s390x architecture

### ISSUE THREAD

**Issue by sid226** [bazelbuild/continuous-integration#1041]
Looking to add s390x support to the existing Bazel CI  to allow testing of the latest build and release binaries for s390x architecture.
Need some pointers to proceed. Hardware/VM access can be provided if needed. Happy to discuss. Thanks!

**Comment by philwo** [comment]
Hi @sid226,

Thanks for your offer! I'm already in talks with @ruixin-bao to get access to an s390x VM for these purposes, but it will take some time to get it all sorted out. I'll update this issue when there's any news. 👍

Cheers,
Philipp

**Comment by sid226** [comment]
Gentle ping @philwo Any updates ?

**Comment by philwo** [comment]
@sid226 Unfortunately not. We currently do not have the capacity to onboard another platform - even with your generous offer of providing free servers, we'd still need to spend engineering time to setup the machines and maintain them, debug issues, fix failing tests, help users who report issues on that platform, ...

@sventiffe FYI

**Comment by sid226** [comment]
@philwo I see, thanks for the info. 
Happy to help if there are plans to add support in future.
