### ISSUE TITLE
Upload info.json with metadata for each commit

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#1045]
We currently store metadata (most importantly the sha256 sums) for published Bazel binaries: https://storage.googleapis.com/bazel-builds/metadata/latest.json

This is done here: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/bazelci.py#L3079-L3096

By this pipeline: https://buildkite.com/bazel-trusted/publish-bazel-binaries

We currently only keep the `latest.json`. It would be useful to upload and store the metadata per commit, too.

Given our current URL structure, a good location might be: https://storage.googleapis.com/bazel-builds/artifacts/metadata/$COMMIT_HASH/info.json

FYI @rupertks

**Comment by rupertks** [comment]
Awesome :D
