### ISSUE TITLE
Can we re-enable macOS during Google Presubmits?

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#1056]
We disabled macOS testing during presubmits due to performance concerns some time ago, but a lot of improvements have been rolled out in the meantime, like pre-extracted external deps for tests, sharding, more machines, ...

We regularly get questions from the team regarding this behavior. Maybe we can consider disabling it for now? (We shouldn't remove the overall mechanisms in case we need them again in the future, of course!)

**Comment by fweikert** [comment]
Has to be fixed internally.
