### ISSUE TITLE
Xcode 12 support?

### ISSUE THREAD

**Issue by keith** [bazelbuild/continuous-integration#1073]
Tulsi internally at google bumped to Xcode 12 https://github.com/bazelbuild/tulsi/commit/59ac17de84dabd7f3e44eac309b5af13c2468e7f, but it looks like that's not supported externally https://buildkite.com/bazel/tulsi-bazel-darwin/builds/1149#5fc5abbe-4635-43a9-89d8-0a87c59bc131

Is there any plan to update the public agents to support Xcode 12?

**Comment by philwo** [comment]
@keith Yes, definitely. Can’t promise I’ll get to it before I’m back from vacation beginning of January 2021 though.

**Comment by philwo** [comment]
I'll roll out new Xcode versions this evening.

**Comment by philwo** [comment]
Xcode 12.4 is now available and the default version on Bazel CI.
