### ISSUE TITLE
Last green Bazel could not be downloaded

### ISSUE THREAD

**Issue by thii** [bazelbuild/continuous-integration#1074]
https://buildkite.com/bazel/rules-apple-darwin/builds/3647#76b691ba-ad4b-41b2-889b-90a8bb932797

**Comment by fweikert** [comment]
There was a temporary problem with the pipeline that builds and uploads the binaries, which affected exactly this commit. 

I published a new binary by retrying the failed task, and I also retried the failing task in your build, too. Everything is passing now.
