### ISSUE TITLE
Release pipeline can't find origin/branch

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#1077]
Stumbled into this during the 3.7.2 release. Some of the recent changes to https://github.com/bazelbuild/continuous-integration/blob/master/pipelines/bazel-release.yml aren't working with git, here's the error:

```
/bin/bash -e -c $'git fetch origin master\ngit checkout -b 3.7.2 --track origin/3.7.2\n\nrelease_name=$(source scripts/release/common.sh; get_full_release_name)\necho "release_name = \\"$release_name\\""\nbuildkite-agent meta-data set "release_name" "$release_name"\n'
--
  | From https://github.com/bazelbuild/bazel
  | * branch                  master     -> FETCH_HEAD
  | fatal: 'origin/3.7.2' is not a commit and a branch '3.7.2' cannot be created from it
```

Full run is https://buildkite.com/bazel-trusted/bazel-release/builds/202#f4fc8ca5-1003-484d-9a51-88d8e81896bc

**Comment by katre** [comment]
I submitted aac713edbcef481f6ae1528f7e8905e3a2560ba3 to try and fix this, but it still didn't work and should be reverted when the overall issue is fixed.

**Comment by katre** [comment]
@meisterT updated the Buildkite config directly to use https://github.com/bazelbuild/continuous-integration/blob/1c44e16b8c652f8c9447e227c2ba883bc20130d1/pipelines/bazel-release.yml in order to unblock 3.7.2. We'll need to change this config back when the issue is resolved.

**Comment by meisterT** [comment]
To revert, we need to change
```
curl -s "https://raw.githubusercontent.com/bazelbuild/continuous-integration/1c44e16b8c652f8c9447e227c2ba883bc20130d1/pipelines/bazel-release.yml?$(date +%s)" | buildkite-agent pipeline upload --replace
```
back to
```
curl -s "https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/pipelines/bazel-release.yml?$(date +%s)" | buildkite-agent pipeline upload --replace
```
here: https://buildkite.com/bazel-trusted/bazel-release/steps

**Comment by meteorcloudy** [comment]
This should now be fixed, I also changed the setup of steps back to `https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/pipelines/bazel-release.yml`

**Comment by katre** [comment]
Thanks @meteorcloudy!
