### ISSUE TITLE
Buildifier configuration?

### ISSUE THREAD

**Issue by keith** [bazelbuild/continuous-integration#1080]
I noticed after this commit landed https://github.com/bazelbuild/rules_apple/commit/572aee29236aa6aa850484d5706b79aa2a098219 there were some buildifier issues I see locally:

```
% buildifier -mode=check "test/starlark_tests/ios_dynamic_framework_tests.bzl"
test/starlark_tests/ios_dynamic_framework_tests.bzl # reformat
```

That are not being caught on CI. Is there some configuration of paths we should be doing to include these files?

**Comment by fweikert** [comment]
Which Buildifier version did you use on your machine?

**Comment by keith** [comment]
I'm installing via `go get`, I just updated to make sure this repros and it does, so I assume https://github.com/bazelbuild/buildtools/commit/ea23b22a5994820220102fcb8ddd0b7f0cb1fc0f at this point. I believe the corrections are valid though?

```patch
% buildifier -mode=diff "test/starlark_tests/ios_dynamic_framework_tests.bzl"
--- test/starlark_tests/ios_dynamic_framework_tests.bzl 2021-01-19 09:22:00.700099519 -0800
+++ /var/folders/h6/6btvg47n7y1f5xxz4_n9rsd40000gn/T/buildifier-tmp-881139563   2021-01-19 09:22:52.394393220 -0800
@@ -43,11 +43,11 @@
             "$BUNDLE_ROOT/Info.plist",
             "$BUNDLE_ROOT/Modules/module.modulemap",
             "$BUNDLE_ROOT/Modules/BasicFramework.swiftmodule/x86_64.swiftdoc",
-            "$BUNDLE_ROOT/Modules/BasicFramework.swiftmodule/x86_64.swiftmodule"
+            "$BUNDLE_ROOT/Modules/BasicFramework.swiftmodule/x86_64.swiftmodule",
         ],
         tags = [name],
     )
-
+
     infoplist_contents_test(
         name = "{}_plist_test".format(name),
         target_under_test = "//test/starlark_tests/targets_under_test/ios:basic_framework",
@@ -84,7 +84,7 @@
             "$BUNDLE_ROOT/Info.plist",
             "$BUNDLE_ROOT/Modules/module.modulemap",
             "$BUNDLE_ROOT/Modules/DirectDependencyTest.swiftmodule/x86_64.swiftdoc",
-            "$BUNDLE_ROOT/Modules/DirectDependencyTest.swiftmodule/x86_64.swiftmodule"
+            "$BUNDLE_ROOT/Modules/DirectDependencyTest.swiftmodule/x86_64.swiftmodule",
         ],
         tags = [name],
     )
@@ -102,7 +102,7 @@
             "$BUNDLE_ROOT/Info.plist",
             "$BUNDLE_ROOT/Modules/module.modulemap",
             "$BUNDLE_ROOT/Modules/TransitiveDependencyTest.swiftmodule/x86_64.swiftdoc",
-            "$BUNDLE_ROOT/Modules/TransitiveDependencyTest.swiftmodule/x86_64.swiftmodule"
+            "$BUNDLE_ROOT/Modules/TransitiveDependencyTest.swiftmodule/x86_64.swiftmodule",
         ],
         tags = [name],
     )
exit status 1
```

**Comment by fweikert** [comment]
Another report about Buildifier behaving badly:

>  It seems buildifier is not behaving like we would like it, it's missing warnings. This is a CI run https://buildkite.com/bazel/rules-rust-rustlang/builds/2397#9146fb58-1d4d-470b-8f99-67177d956f42 for https://github.com/bazelbuild/rules_rust/pull/620/files. There the WORKSPACE file is misformatted. https://github.com/bazelbuild/rules_rust/issues/611 shows some existing edits that buildifier on the CI missed (vast majority of those is expected since there are build files that have a custom suffix). Maybe we are not configuring buildifier correctly?

**Comment by fweikert** [comment]
Another link: https://github.com/bazelbuild/rules_rust/commit/7579c34722c6bdf47bd7644ae66e0cb0c39d9679

**Comment by hlopko** [comment]
Any progress? We regularly miss buildifier lints in PRs and end up having `Additionally, this PR contains buildifier fixes` in overy other PR. Like yesterday https://github.com/bazelbuild/rules_rust/pull/665.

**Comment by fweikert** [comment]
@hlopko Sorry for the delay. There were so many problems that a significant rewrite was needed.

**Comment by hlopko** [comment]
No worries, thank you for your work!!

**Comment by fweikert** [comment]
Had to fix two other problems, but it seems to work now: https://buildkite.com/bazel/rules-rust-rustlang/builds/2602

**Comment by keith** [comment]
Thanks! I'm seeing failures on our side too now

**Comment by fweikert** [comment]
Great! I'll close this issue - please let me know if you run into other problems.
