### ISSUE TITLE
 Build Ownership Migration

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1082]
Poking around buildkite I found on Bazel Downstream project (probably also other projects):

"This schedule uses the deprecated build ownership property, which will be removed January 30, 2020. Please migrate this schedule by removing build ownership before January 30, using the Remove Build Ownership button below.

Removing build ownership will remove the build association with the user Jakob Buchgraber, and builds will no longer have an associated user (e.g. the BUILDKITE_BUILD_CREATOR environment variable will be empty).

You can read more about the deprecation on the changelog, or contact support@buildkite.com if you have any questions."

**Comment by fweikert** [comment]
Can you please add a link to such a page? I don't see any messages.

**Comment by comius** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/settings/schedules/fbfdc764-e0d2-4bed-a430-c4b7dd816cf2

**Comment by fweikert** [comment]
I clicked the button for this particular pipeline. However, I don't think it's feasible to remove ownership for each pipeline manually. We should just wait until it's automatically removed on January 20th, since it's a no-op for us.

**Comment by comius** [comment]
Ack.
