### ISSUE TITLE
Pushing a new Buildifier Docker image breaks the Buildifier step

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1089]
https://buildkite.com/bazel/rules-apple-darwin/builds/3868#0ff6f6b9-999a-42cf-9662-ca1a4f58cc25

"[FATAL tini (6)] exec /usr/local/bin/buildifier.py failed: Permission denied"

**Comment by fweikert** [comment]
I restored the previous image.

**Comment by philwo** [comment]
Mhm.. the error message sounds like the buildifier.py was not marked as executable.
