### ISSUE TITLE
rules_nodejs broken on macos CI Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/continuous-integration#1093]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1906#44b4eb78-3a05-4ecf-abdb-dfa16b20ff86

Broken only on Bazel@HEAD, only on macos, verified it's not a one-off flake.

Failure has no culprit, looks like it might be machine configuration? 
Not sure how to diagnose.

Error snippet:

(17:28:01) ERROR: /Users/buildkite/builds/bk-imacpro-1/bazel-downstream-projects/rules_nodejs/packages/protractor/test/protractor-2/BUILD.bazel:76:26: Testing //packages/protractor/test/protractor-2:devserver_test_chromium-local failed: Exec failed due to IOException: /private/var/tmp/_bazel_buildkite/91c18959b05b90458bcda693ef4a8678/execroot/build_bazel_rules_nodejs/build_bazel_rules_nodejs/bazel-out/darwin-fastbuild/bin/packages/protractor/test/protractor-2/devserver_test_chromium-local.sh.runfiles/io_bazel_rules_webtesting/third_party/chromium/chromium.out/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Helpers (No such file or directory)

**Comment by philwo** [comment]
[Auto-Sheriff](https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/431) identified this commit as the culprit: https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe

**Comment by comius** [comment]
Actually Auto-Sheriff determined another culprit: https://github.com/bazelbuild/bazel/commit/7149f578006a4ad0d51df69830a6986749b34df5.

**Comment by comius** [comment]
Confirming it's fixed https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1924

**Comment by meteorcloudy** [comment]
@comius Thanks for confirming!
