### ISSUE TITLE
upb broken with Bazel@Head on Mac

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1098]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1914#c50bd664-9fb0-4155-a613-00d82e0615b2

Reported error:
```
/private/var/tmp/_bazel_buildkite/fa7b00f247f538313ededea77e2ee60e/sandbox/darwin-sandbox/673/execroot/upb/bazel-out/darwin-fastbuild/bin/cmake/cmake_build.runfiles/upb/cmake/cmake_build: line 6: cmake: command not found
```

**Comment by philwo** [comment]
Fixed by installing missing `cmake` on Mac machines and verified by successfully retrying the job.
