### ISSUE TITLE
rules_foreign_cc broken with Bazel@HEAD on Mac

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1100]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1914#1aa940b2-9117-4c71-8704-6cf202207935

It looks cmake related.
Also related: https://github.com/bazelbuild/continuous-integration/issues/1098

**Comment by philwo** [comment]
Fixed by installing missing `cmake` on Mac machines and verified by successfully retrying the job.
