### ISSUE TITLE
Add build badget to bazelbuild/starlark

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/continuous-integration#1102]
I'd like to add a build badge to bazelbuild/starlark. Looking at [BuildKite's docs](https://buildkite.com/docs/integrations/build-status-badges), the link to add a badge is found from the settings page on the [pipeline](https://buildkite.com/bazel/starlark/builds). But I don't appear to have access to that page.

Could you tell me what markdown to add to generate a link a la the one on stardoc's page, which is:

```
[![Build status](https://badge.buildkite.com/d8594eb71e4869c792cce22428b08e03b345f9c65dc603d70b.svg?branch=master)](https://buildkite.com/bazel/stardoc)
```

I'm assuming the hex string in the svg is important, but maybe I'm wrong, in which case can instructions for adding the badge be added to the readme?

**Comment by philwo** [comment]
You can use this link:

```
[![Build status](https://badge.buildkite.com/8b4240b7092ded039cad0d825d7a6ebff115623ec8af217121.svg?branch=master)](https://buildkite.com/bazel/starlark)
```

**Comment by philwo** [comment]
I also made you an administrator of the pipeline, so the Settings page should work now. 😊
