### ISSUE TITLE
rules_swift broken on Mac

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1107]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1915#78f59480-1dfb-4e39-bf5d-c5f37849eb71

Autosheriff claims it's infra change

Log:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples/xplatform/xctest:xctest
-----------------------------------------------------------------------------
objc[26545]: CLASS: class 'examples_xplatform_xctest_xctest.SimpleTests' 0x10eacd1c0 small method list 0x10eac8b98 is not in immutable memory
```

**Comment by philwo** [comment]
Possibly caused by upgrading our Xcode to 12.4. Upstream issue here: https://github.com/bazelbuild/rules_swift/issues/548

**Comment by thii** [comment]
I submitted a fix here: https://github.com/bazelbuild/rules_swift/pull/566.

**Comment by comius** [comment]
Swiftly fixed :)
