### ISSUE TITLE
dashboard.bazel.build has broken links in open issue table for all sections except bazelbuild/bazel

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/continuous-integration#1119]
In the [bazelbuild/bazel](https://dashboard.bazel.build/bazelbuild/bazel) section of https://dashboard.bazel.build/, links to open issues table are set correctly; for example, the link for Android/PR correctly points to https://github.com/bazelbuild/bazel/issues?q=is%3Apr+is%3Aopen+label%3Ateam-Android

By contrast, in all other sections of the dashboard (i.e. [bazelbuild/starlark](https://dashboard.bazel.build/bazelbuild/starlark), [bazelbuild/stardoc](https://dashboard.bazel.build/bazelbuild/stardoc), [bazelbuild/bazel-skylib](https://dashboard.bazel.build/bazelbuild/bazel-skylib), and [google/starlark-go](https://dashboard.bazel.build/google/starlark-go)), the <a> elements in the open issues table have an empty href attribute, so clicking on the issue link leads nowhere.

**Comment by tetromino** [comment]
@coeuvre - this is for https://github.com/coeuvre/continuous-integration which I think hasn't been merged yet

**Comment by coeuvre** [comment]
Fixed. Thanks for catching this!
