### ISSUE TITLE
Learnings from bazelbuild/bazel#3495

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#112]
Opening the bug for now.

**Comment by damienmg** [comment]
__What happened:__

- The new pipeline changed the way the release name is invoked. it worked fine on test and RCs but failed on actual release
- It failed because xargs got unhappy with the environment, fix on bazel remove the usage of xargs
- Fixing the release itself I had to patch bazel on the fly:
  - Add sh "sed -i.bak 's/| xargs echo//' scripts/release/common.sh" in the bootstrapBazel step [1]
  - Re-run the release job with the "replay" button from Jenkins. I had to re-run twice: one for test and the second one to actually rewrite the release on github. So go to the release and click on the delete button delete the release info (but not the release commit) and the re-run of the job 

Initial release on 2017-07-27 20:04 Munich time
Fixed release on 2017-07-28 10:48 Munich time

__Impact:__
 - At the time of the release the windows binaries did not had any release information
 - The remediation led to a time ~20minute during which the github release page did not had any artifacts anymore.
 - When the re-run of the pipeline, the replay button enable us to edit the pipeline, removing the recipient mail to avoid sending a second release mail. It was not done for the second re-run and another mail announcing the release was sent.

**Comment by damienmg** [comment]
__My recommendations:__

- Testing the final release is hard, we should make it possible on staging for testing change in the release by connecting it to another github repository (so we can test github integration).
- Applying patch on the release might be an interesting feature we want to have on CI to better remediate those feature. Maybe add the sh step as a parameter? This is a risky feature though.
- Move the release scripts outside of Bazel repository and eventually rewrite them in a more portable language (e.g. python) to have less cross-platform surprises. Release script can be used for more system so that could be helpful for #100 

I'll leave that bug open unassigned for follow-ups, I will be away for 3 weeks now.

**Comment by philwo** [comment]
Obsolete, as we're migrating away from Jenkins.
