### ISSUE TITLE
Request to add new project ash2k/bazel-tools

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/continuous-integration#1121]
- I want to test the following project on Bazel CI: https://github.com/ash2k/bazel-tools
- I confirm that the project has a `.bazelci/presubmit.yml` file.

Please remove the configuration for https://github.com/atlassian/bazel-tools, which was added in https://github.com/bazelbuild/continuous-integration/issues/692. I no longer work at Atlassian, I'm maintaining the repo at the new location now. The old one has been archived.

**Comment by fweikert** [comment]
Done. I re-used the old pipeline and team, which preserves the build history. First new build: https://buildkite.com/bazel/ash2k-bazel-tools/builds/1015

Note: Buildkite complained about getting 404s from GitHub when updating commit statuses. You might need to connect your GitHub account to Buildkite via the Buildkite GitHub Application: https://buildkite.com/organizations/bazel/repository-providers

**Comment by ash2k** [comment]
Thank you!

>  https://buildkite.com/organizations/bazel/repository-providers

I don't have access to that page. I have uninstalled "Github" integration (legacy one?) and installed the "Github app" application from https://github.com/apps/buildkite/. I initially tried using the "Github app" from https://buildkite.com/user/connected-apps but from what I understand it wants full access to my account (Github page says "app would like permission on Act on your behalf"), which is not going to happen. So I'm wondering if there is a page with instructions on how to set everything up? For example, I don't understand how to setup webhooks? Do I need to or it all somehow magically works via the "Github app" integration?

**Comment by fweikert** [comment]
Re webhooks: https://buildkite.com/bazel/ash2k-bazel-tools/settings/setup/github

This means that Buildkite will trigger builds whenever a PR is opened. However, without connecting the app Buildkite cannot update the commit status on GitHub :(

**Comment by fweikert** [comment]
Since this problem has come up frequently, I'm thinking about creating a dedicated Bazel CI GitHub user, which could connect its accounts with each other.

**Comment by fweikert** [comment]
Ok, we actually have a workaround for org-owned repos: The owners had to give our bazel-io robot account write permissions to the repository. Since your repo is not owned by an org, the only alternative might be to invite bazel-io as collaborator (not 100% sure if this works, though).

**Comment by ash2k** [comment]
> Re webhooks: https://buildkite.com/bazel/ash2k-bazel-tools/settings/setup/github

This link redirects me back to this issue. Very weird. If I open it in an incognito window and auth with Buildkit, it tells me "You don’t have the required access level to change this pipeline".

Ok, I've invited @bazel-io as collaborator.

**Comment by fweikert** [comment]
Ok, that's weird. I just sent you the instructions via email, that should work, too.

I'm having some problems accessing bazel-io's email account. Will try again tomorrow.

**Comment by ash2k** [comment]
@fweikert Hey, thanks for the email! I've setup the webhook and works fine. Still waiting for the bazel.io to accept the invitation. Looks like currently Buildkit is unable to set build status/etc on a PR.

**Comment by fweikert** [comment]
It works now after accepting the invite: https://github.com/ash2k/bazel-tools/pull/6

**Comment by ash2k** [comment]
Looks like it does! Thanks a lot! I now need to fix those failing tests...
