### ISSUE TITLE
bazel-test UI is unusable

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/continuous-integration#114]
The pipeline picture here: http://ci.bazel.io/blue/organizations/jenkins/bazel-tests/detail/bazel-tests/923/pipeline
tells me that tests on all platforms are broken

The actual broken variation is darwin (http://ci.bazel.io/blue/organizations/jenkins/bazel-tests/detail/bazel-tests/923/pipeline/30)  but all build steps show as successful.
In the list of steps there are many "Shell Script"s, it is utterly unclear which are tests and which are not

**Comment by dslomov** [comment]
Lowering priority, since it seem to occur only for baseline

**Comment by dslomov** [comment]
It is extremely annoying: there is no way to understand what is actually broken from this view:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Global/job/pipeline/
nor from this view: http://ci.bazel.io/blue/organizations/jenkins/Global%2Fpipeline/detail/pipeline/175/pipeline

**Comment by dslomov** [comment]
Wow it looks like **https://issues.jenkins-ci.org/browse/JENKINS-39203** and it is not fixed since 12 months. Why we switched to this UI again?

**Comment by dslomov** [comment]
The key problem is this line: https://github.com/bazelbuild/continuous-integration/blob/master/jenkins/lib/vars/runAll.groovy#L38
When we say `currentBuild.result = whatever` that immediately marks the entire thing as whatever - ALL the stages.

**Comment by dslomov** [comment]
@buchgr @aehlig I think we should rewrite this to actually fail the build if tests fail, but still publish the report. I am curious if the artifacts are still published that way

**Comment by dslomov** [comment]
Ok people I think this is a P0 problem. CI is completely unusable: what failed here for example: http://ci.bazel.io/blue/organizations/jenkins/Global%2Frules_go/detail/rules_go/52/pipeline/
(well actually everything but analyzing this is utterly impossible)

**Comment by aehlig** [comment]
first step: 7bb4844547b580454848779d61f75e2c93ad3166

**Comment by dslomov** [comment]
Awesome! This is so much nicer: http://ci.bazel.io/blue/organizations/jenkins/Global%2Fpipeline/detail/pipeline/183/pipeline

As discussed offline, would be great to do the same for tests as well: http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/132/pipeline

**Comment by dslomov** [comment]
With https://bazel.googlesource.com/continuous-integration/+/272a2bf76f0e00c5066aa6a05354d13ce5968727 in, I think the most immediate issues are addressed.
