### ISSUE TITLE
Request to add new project limdor/bazel-examples

### ISSUE THREAD

**Issue by limdor** [bazelbuild/continuous-integration#1149]
- I want to test the following project on Bazel CI: https://github.com/limdor/bazel-examples
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
@fweikert Could you help @limdor set this up? :)

**Comment by limdor** [comment]
@philwo @fweikert can I do something on my side to speed up the process of making this happen?
I would like to keep creating and maintaining examples for Bazel but without using Bazel CI is hard to say if the issues are because of CI setup or Bazel bugs.
For me it would be also fine to add examples in https://github.com/bazelbuild/examples but I saw there is a capacity problem there to review and merge PRs.

**Comment by fweikert** [comment]
Sorry for the delay! You can find the pipeline here: https://buildkite.com/bazel/limdor-bazel-examples/builds/1

I'll send you the webhook instructions via email.

**Comment by limdor** [comment]
Thanks a lot! I've followed the email instructions and I've created a PR to test it:
https://github.com/limdor/bazel-examples/pull/45
The build got triggered
https://buildkite.com/bazel/limdor-bazel-examples/builds/2
But the status does not appear in the PR. Any ideas?
![image](https://user-images.githubusercontent.com/3073717/120110710-e35cb880-c16e-11eb-91f1-a51956b21b1f.png)

To me  it looks similar to the issue that we had in https://github.com/bazelbuild/continuous-integration/issues/1078

Should I add @bazel-io as colaborator of the repository?

**Comment by limdor** [comment]
One more thing, if I try to go to https://buildkite.com/organizations/bazel/repository-providers like you mentioned in https://github.com/bazelbuild/continuous-integration/issues/1078#issuecomment-815165756 I'm getting this error:
![image](https://user-images.githubusercontent.com/3073717/120111212-5cf5a600-c171-11eb-8027-41f26a5b9a92.png)

**Comment by fweikert** [comment]
Adding @bazel-io should do the trick

**Comment by limdor** [comment]
Ok done, once @bazel-io accepts the invitation I'll try again. Thanks!

**Comment by fweikert** [comment]
Ok, I’ll see whether I can access the account tomorrow. In the worst case we have to wait one week until Philipp is back in the office.

**Comment by philwo** [comment]
@limdor Sorry, could you please resend the invite? They expire after 7 days and this one has apparently just expired :/

**Comment by limdor** [comment]
Great, with bazel-io as a collaborator now it works:
![image](https://user-images.githubusercontent.com/3073717/121057596-b9834180-c7bf-11eb-9f4a-54d54e85f50c.png)
