### ISSUE TITLE
rules_nodejs failing on Windows

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1155]
rules_nodejs started failing on windows on  2021-05-11
Log: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2033#507b633a-a766-4150-ab89-35f00475ff97

The failing test (https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/pkg_npm/test/diff_pack_dir.sh) is comparing output `pkg_npm` and a template. And `pkg_npm` supposedly produces extra files `external.mjs`, `foo.mjs`,`ts_library.externs.js`.

I **could not** reproduce the test on Windows testing machine with any commit. I was running a single test and all tests locally (no RBE).

There is a problem with culprit finder - first build succeeds and subsequent fail - reporting a wrong commit. Link: https://buildkite.com/bazel/culprit-finder/builds/1457#b2fda6b5-cf23-4590-9d52-f07a3f5ee1c6

 I suspect no sandboxing on windows and leftover files?

**Comment by philwo** [comment]
> I suspect no sandboxing on windows and leftover files?

Correct :/ Maybe NEEDS_CLEAN helps? (https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#culprit-finder)

**Comment by comius** [comment]
This was fixed.
