### ISSUE TITLE
Global/pipeline view: add a link to executing "subpipeline"

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/continuous-integration#117]
E.g. here: http://ci.bazel.io/blue/organizations/jenkins/Global%2Fpipeline/detail/pipeline/177/pipeline/
If you click on TensorFlow, you get the following log:
```
Scheduling project: Global » TensorFlow
Starting building: Global » TensorFlow #63
```
It would be nice if that log contained a link to that pipeline status. Maybe that's hard because it Jenkins' inetrnal built-in

**Comment by dslomov** [comment]
Actually I think just a link to general pipeline view would be enough: http://ci.bazel.io/blue/organizations/jenkins/Global%2FTensorFlow/activity

**Comment by philwo** [comment]
Obsolete, as we're migrating away from Jenkins.
