### ISSUE TITLE
Blue Ocean: Pipeline views are very slow to load

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/continuous-integration#118]
Not sure how actionable is this - maybe we just need a beefier machine for jenkins?

**Comment by damienmg** [comment]
Indeed I noticed that, it was way faster on the container running on my laptop, +1 for trying to increase the size of the master.

**Comment by damienmg** [comment]
Increasing the size does not help. actually we do not seem to even use fully the machine, let's try to tune the docker container...

**Comment by damienmg** [comment]
There is no limit on docker so it is not in the infra.

**Comment by damienmg** [comment]
Ok I am giving up since it is not a simple resolution, found https://issues.jenkins-ci.org/browse/JENKINS-38363 that have a bunch of workaround to investigate.

**Comment by philwo** [comment]
I noticed that we had *8 TB* of job history stored on the Jenkins volume. I figured that if even "find" takes an hour to go through the directory structure, then Jenkins can't be much faster either, considering that it doesn't use an SQL DB or something to keep its state.

I fixed this by:
- Nuking our history from orbit. We're now down to ~2 TB of data and I intend to reduce it even more.
- Replacing the HDD volume with an SSD.
- Updating Jenkins and all plug-ins (and thus also Blueocean).

It seems that this helped. Blueocean loads quite fast for me now.

**Comment by ulfjack** [comment]
I just tried it after your post - the initial load took a few seconds for me, but after that it was fast. Great!

**Comment by hilalhmuhammed** [comment]
@philwo Could you share the load times after this change

> Nuking our history from orbit. We're now down to ~2 TB of data and I intend to reduce it even more.
Replacing the HDD volume with an SSD.
Updating Jenkins and all plug-ins (and thus also Blueocean).

**Comment by philwo** [comment]
Hi @hilalhmuhammed, sorry, we've migrated from Jenkins to Buildkite a few months ago. I don't have any historic data for our Jenkins. The UI certainly felt much quicker after these steps (but I don't have any numbers for this). Hope that helps!
