### ISSUE TITLE
Gerrit pipeline has been broken since April

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1182]
- Last green: https://buildkite.com/bazel/gerrit/builds/7055 at [79a017f](https://gerrit.googlesource.com/gerrit/+/79a017f7ddb80047232a04a24c83ae37812a3e47)
- First red: https://buildkite.com/bazel/gerrit/builds/7056 at [caa7997](https://gerrit.googlesource.com/gerrit/+/caa7997c551462e210054265af4843f7a5816c51)

Based on the [log](https://gerrit.googlesource.com/gerrit/+log?s=08325a350ffc6c3264535819456c9f0765fe3229) [2b5fe09](https://gerrit.googlesource.com/gerrit/+/2b5fe095f9431e995b23d3517a052fa7f4c36638) looks like the potential culprit.

**Comment by Wyverald** [comment]
Gerrit bug: https://bugs.chromium.org/p/gerrit/issues/detail?id=14557

**Comment by fweikert** [comment]
Nice, thanks for filing the issue! But it's not a great signal that they keep ignoring it :(

**Comment by Wyverald** [comment]
This seems to have been fixed.
