### ISSUE TITLE
Passing startup commands via `presubmit.yaml`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/continuous-integration#1197]
Is it possible to do this?

**Comment by philwo** [comment]
Not currently. What would you use it for?

**Comment by UebelAndre** [comment]
to pass `--windows_enable_symlinks` (and other startup args) to a build. As an alternative to making a `.bazelrc`

**Comment by UebelAndre** [comment]
But that said, I suppose a `.bazelrc` is a solution so the work to support this is not necessary.
