### ISSUE TITLE
Reorganize jobs

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#120]
To be able to see and correctly directly identify which jobs does what I was thiking of some renaming we should do:

- `Global/pipeline` should be split into 2 targets: `bazel/nightly` and `bazel/release`
- `CR/global-verifier` should be renamed into `bazel/presubmit`
- `CR/gerrit-verifier` should be moved to `maintenance/gerrit-verifier`
- Bazel-Push-Benchmark-Site and `install-bazel` should be moved to `maintenance` folder

This way `bazel` folder would contains only bazel jobs, `CR`, `PR` and `Global` would only be copies of master jobs and `maintenance` can be ignored in most cases. The display would just have to display top jobs and `bazel/nightly`.

**Comment by dslomov** [comment]
Why `Global / pipeline` is `bazel / nightly`? It should be `bazel / master', shouldn't it?

+1 to splitting `bazel / release` out of general pipeline

**Comment by damienmg** [comment]
Should be `bazel / nightly` according to #94.
