### ISSUE TITLE
Make it possible to `sudo apt install` in presubmit.yml

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#1214]
Instead of preinstalling a lot of dependencies that are used by only one project on our CI, I want to make it possible that projects can just `sudo apt install` in their presubmit.yml whatever they need.

**Comment by coeuvre** [comment]
I can implement this feature. What the syntax do you want to support installing packages?

**Comment by coeuvre** [comment]
well, that's not flexible enough. We could probably use something similar to github actions.

**Comment by coeuvre** [comment]
Implemented via https://github.com/bazelbuild/continuous-integration/pull/1236.
