### ISSUE TITLE
Buildfarm failure cannot be bisected

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1237]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2193#c2635432-1220-4c15-9490-c6c4d05a5b3e fails with `subprocess.CalledProcessError: Command '['set -e\n./bazelw build //src/main/java/build/buildfarm/rpms/server:buildfarm-server-rpm //src/main/java/build/buildfarm/rpms/worker:buildfarm-worker-rpm']' returned non-zero exit status 1.`

The corresponding run of https://buildkite.com/bazel/culprit-finder/builds/2271#63af3010-26c4-479b-95f4-f512f35249a3 says "Exception: Given good commit (662cf54de7a103db30e04ebae2d2b919437c4846) is not actually good, abort bisecting"

**Comment by fweikert** [comment]
Assigning to Yun as recommended in the error message.

**Comment by meteorcloudy** [comment]
Looks like it's caused by Buildfarm's change on their own presubmit.yml file:
https://github.com/bazelbuild/bazel-buildfarm/pull/911/files

This is not a bug from our CI.
