### ISSUE TITLE
Blue Ocean button disappeared?

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/continuous-integration#124]
I do not see it e.g. here: http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/

**Comment by damienmg** [comment]
It did not disappeared, an update of the jenkins plugins by @aehlig had a side effect to move it on the side bar on the left. I find it also less discoverable now :/

**Comment by dslomov** [comment]
Got it.
