### ISSUE TITLE
Add Python3 to the PATH

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#126]
To support build for Gerrit Code Review project on Windows, Python 3 is needed.

**Comment by meteorcloudy** [comment]
Can we already using Bazel 0.5.4 to build gerrit from HEAD?

**Comment by davido** [comment]
@meteorcloudy We need one single cl more: https://bazel-review.googlesource.com/15850

**Comment by meteorcloudy** [comment]
@davido Hmm, that means we cannot yet build with latest released Bazel. I think we'll have to wait for a new release with https://bazel-review.googlesource.com/15850, then we can add a Windows gerrit job on Bazel CI.

**Comment by laszlocsomor** [comment]
@meteorcloudy : Can you elaborate why we need to wait for a release that contains https://bazel-review.googlesource.com/15850?

**Comment by davido** [comment]
@laszlocsomor Well, I said that ;-)

The point is, that to buid something useful, would require to build `headless.war` artifact, that we cannot build, because the generated script is 25k and gets truncated.

On seond tought, rto not waste the time, we could set CI job up, but build less, say only `gerrit-server:server``, and once, this cl is released we would switch to building `headless.war` instead.

**Comment by laszlocsomor** [comment]
I meant why we couldn't use a head-built Bazel on CI instead of waiting for a release. But I suppose because we don't want any version churn on the CI machines.

**Comment by davido** [comment]
Any progress on this issue, after 0.7 was released?

**Comment by meteorcloudy** [comment]
So, can we already build Gerrit with 0.7.0? If so, we can just start setting up a CI job for gerrit.

**Comment by meteorcloudy** [comment]
Can you tell us which target should we build, also the build options if any?

**Comment by davido** [comment]
No build options. `:headless` should work out of the box on Gerrit master. This would build the 100% Gerrit server stack, without any UI (Neither GWT no PolyGerrit UI)

**Comment by meteorcloudy** [comment]
Are you familiar with this error? I got it when running `bazel build //:headless -s`
```
>>>>> # //gerrit-war:log4j-config__jar [action 'Executing genrule //gerrit-war:log4j-config__jar']
cd C:/tmp/_bazel_pcloudy/tp7ykz9l/execroot/gerrit
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\Program Files\Anaconda3;C:\tools\msys64\home\pcloudy\bin;C:\Program Files\Java\jdk1.8.0_112\bin;C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl
    SET TEMP=C:\Users\pcloudy\AppData\Local\Temp\2
    SET TMP=C:\Users\pcloudy\AppData\Local\Temp\2
    SET TMPDIR=C:\tmp
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; ROOT=$PWD && TMP=$(mktemp -d || mktemp -d -t bazel-tmp) && (cd gerrit-war/src/main/resources && zip -9Dqr $ROOT/bazel-out/msvc_x64-fastbuild/genfiles/gerrit-war/log4j-config.jar .)
ERROR: Process exited with status 1: Process exited with status 1.
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by davido** [comment]
Nope, this seems to be caused by:

```
genrule2(
    name = "log4j-config__jar",
    srcs = ["src/main/resources/log4j.properties"],
    outs = ["log4j-config.jar"],
    cmd = "cd gerrit-war/src/main/resources && zip -9Dqr $$ROOT/$@ .",
)
```

from: gerrit-war/BUILD. Can it be some issues in your environment? Can you issue:

```
  zip -9Dqr $ROOT/bazel-out/msvc_x64-fastbuild/genfiles/gerrit-war/log4j-config.jar .
```

**Comment by meteorcloudy** [comment]
That command works, I just figured out it's because in `tools/bazel.rc` we have 
```
$ cat tools/bazel.rc
build --workspace_status_command=./tools/workspace-status.sh --strategy=Closure=worker
test --build_tests_only
```
`./tools/workspace-status.sh` is not a valid Windows command.
Did you removed this when you running the build?

**Comment by davido** [comment]
Ah, right! I forgot to mention that ;-(

**Comment by davido** [comment]
in this [comment](https://github.com/bazelbuild/bazel/issues/2040#issuecomment-322980147) you can see, what I did.

I ported the workspace-status script to Windows:

```
echo STABLE_BUILD_GERRIT_LABEL dev
echo STABLE_WORKSPACE_ROOT %cd%
```

And then passing this to the build:

```
$ bazel --nomaster_bazelrc build --workspace_status_command=/C/users/davido/projects/gerrit/tools/workspace-status.cmd --verbose_failures -s :headless
```

**Comment by meteorcloudy** [comment]
So can you check in this `workspace-status.cmd` script?

**Comment by davido** [comment]
Can you confirm that it works for you as well?

**Comment by meteorcloudy** [comment]
It worked with
```
bazel --nomaster_bazelrc build --workspace_status_command=C:/tools/msys64/home/pcloudy/workspace/gerrit/tools/workspace-status.cmd --verbose_failures :headless
```
But I don't think we should use an absolute path in `--workspace_status_command` option..

**Comment by davido** [comment]
I agree, so do you have a better idea to make it work?

**Comment by meteorcloudy** [comment]
Ideally, we should just use `--workspace_status_command=tools\workspace-status.cmd`, looks like there is still a bug in Bazel preventing us from doing so, I'm debugging this.

**Comment by davido** [comment]
Indeed, this is the way to go, but it didn't worked ;-(

**Comment by davido** [comment]
@meteorcloudy I just wrote this https://github.com/bazelbuild/bazel/issues/3962

**Comment by meteorcloudy** [comment]
Thanks, sent https://bazel-review.googlesource.com/#/c/bazel/+/19470/

**Comment by davido** [comment]
Thanks, so I guess we would need to wait until this change is merged and released to proceed, right? Just to make sure we donÄt missed anything else, could you setup a test CI job and test whether or not https://bazel-review.googlesource.com/#/c/bazel/+/19470/ and the `custom workspace-status.cmd` are the only missing links in the chain?

I just would like to avoid, that this would be a never ending story, of missing feature in Bazel to setup CI-Job on Windows for Gerrit Code Review.

**Comment by meteorcloudy** [comment]
Sorry, it's not easy to set up a ci job with a custom Bazel. But after you check in `workspace-status.cmd`, it should be easy to test it manually. I'll make sure of that. 
Filed https://github.com/bazelbuild/bazel/issues/3965 as a release blocker.

**Comment by davido** [comment]
> Filed bazelbuild/bazel#3965 as a release blocker.

Thanks. `workspace-status.cmd` is merged now in gerrit.

**Comment by philwo** [comment]
I have replaced Python 2.x with Python 3.x in the new Windows Server 2016 image.

**Comment by davido** [comment]
@meteorcloudy @philwo 

What has to be done to activate Gerrit@HEAD build on Bazel CI on Windows? I verified yesterday and Gerrit@HEAD can be built on Bazel@HEAD on python 3 (I used 3.61). The build target that woks is `bazel build :headless`. Some tests a re still failing on Windows, so that we would have to find a way to only specify the subset of tests that known to pass on Windows.

**Comment by meteorcloudy** [comment]
We need to update the jenkins configure file for gerrit:
https://github.com/bazelbuild/continuous-integration/blob/master/jenkins/jobs/configs/gerrit.json

I'll send a change for this.

**Comment by meteorcloudy** [comment]
@davido I think you can mark the failing tests with `tags = ["no_windows"]`, then we'll filter them on Windows.

**Comment by meteorcloudy** [comment]
Good, will do it.

**Comment by meteorcloudy** [comment]
BTW, you can test it by adding '--test_tag_filters=-no_windows' :)

**Comment by davido** [comment]
@philwo @meteorcloudy 

Python 3 activation didn't seem to work out of the box on the CI: [1]. It seems, that still python 2 is used on Windows node:

```
RROR: C:/jenkins/workspace/global/gerrit-node=windows-x86_64/lib/log/BUILD:1:1: no such package '@log_api//jar': failed C:/python_27_amd64/files/python.exe C:/jenkins/workspace/global/gerrit-node=windows-x86_64/tools/download_file.py -o C:/windows/temp/_bazel_system/odusxnky/external/log_api/jar/slf4j-api-1.7.7.jar -u MAVEN_CENTRAL:/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar -v 2b8019b6249bb05d81d3a3094e468753e2b21311: Traceback (most recent call last):

  File "C:/jenkins/workspace/global/gerrit-node=windows-x86_64/tools/download_file.py", line 20, in <module>

    from os import link, makedirs, path, remove

ImportError: cannot import name link
```

I tried to figure out, how this was done for tensorflow, and it seems that tensorflow is hard coding the dependency on Anaconda 3 in the environment setting machinery: [2]. So that I'm not sure what is the right way to call Geirrit build on Bazel CI using Python 3 on Windows?

* [1] https://ci.bazel.build/blue/organizations/jenkins/Global%2Fgerrit/detail/gerrit/352/pipeline/
* [2] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/bazel/common_env.sh#L35

**Comment by meteorcloudy** [comment]
@davido Yes, we were still using the old image.
Just switched to the new image, gerrit is building on Windows, but several tests are failing, can you mark them as `no_windows`?
https://ci.bazel.build/blue/organizations/jenkins/gerrit/detail/gerrit/2147/pipeline

**Comment by davido** [comment]
@meteorcloudy Yes, I will have a look. I was waitig for Bazel CI *actually* work on Windows ;-)

**Comment by meteorcloudy** [comment]
@davido Any progress on fixing the tests?

**Comment by davido** [comment]
@meteorcloudy I still waiting for Gerrir Maintainer @Google to approve my `rules_closure` upgrade CL: [1], may be you can ping Gerrit Team @Google internally? Of course, this change is unrelated, but I try to avoid having long backlog of not reviewed changes, for all open source projects that I contribute in my spare free time...

* [1] https://gerrit-review.googlesource.com/#/c/gerrit/+/147231/

**Comment by philwo** [comment]
I've pinged someone I know on the Gerrit team.

**Comment by davido** [comment]
Thank you @philwo !

**Comment by davido** [comment]
@meteorcloudy Something is fishy here: not all tests are ran for some reasons. On Bazel CI only these tests are ran: [1]. Locally, mcuh more tests are executed: [2].

All "//javatests/com/google/gerrit/acceptance/..." test are skipped for some reasons?

Locally I am running this command:

```
  $ bazel test --workspace_status_command=tools/workspace-status.cmd //javatests/...
```

* [1] http://paste.openstack.org/show/646545
* [2] http://paste.openstack.org/show/646546

**Comment by davido** [comment]
@philwo @meteorcloudy 

The CI to exclude failing tests on Windows is pending for review: [1].

* [1] https://gerrit-review.googlesource.com/152890

**Comment by meteorcloudy** [comment]
@davido `//javatests/com/google/gerrit/acceptance/...` tests are skipped because they are marked as `slow`. We have `-slow` in test_tag_filters on all platforms, so they also don't run on Linux, either.

I think the gerrit job on Bazel CI is intended to catch any build error with Bazel@HEAD, if the tests fail, that's probably on gerrit's side to fix. Maybe you can setup a Windows job on gerrit CI to run the whole tests? WDYT?

**Comment by philwo** [comment]
FYI, I’m removing the slow filter and the bazel-slow-tests job today, unless someone can convince me that they are useful.

**Comment by meteorcloudy** [comment]
I see, I guess bazel-slow-tests was introduced to reduce presubmit time? But not sure how useful it is.
