### ISSUE TITLE
Support matrix testing

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#1277]
This is a feature request to add matrix testing similar to https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix to our config language.

This should solve a lot of duplication that we see in config files in our organization, where the same config is repeated for all platforms and various Bazel versions.

**Comment by meteorcloudy** [comment]
This is done in #1300
