### ISSUE TITLE
Ubuntu 21.04 image not working

### ISSUE THREAD

**Issue by limdor** [bazelbuild/continuous-integration#1279]
I tried to used the Ubuntu 21.04 image but it seems that there is some problem with Python. Not sure what is the problem because it looks like the other Ubuntu version.
https://buildkite.com/bazel/limdor-bazel-examples/builds/65
The error is the following when running the docker run
`/bin/sh: 2: python3.8: not found`

**Comment by philwo** [comment]
Hi @limdor,

Thanks for spotting this! I must have accidentally put the wrong Python interpreter binary into our config. Sent a PR #1281 that should fix this and will retry afterwards.

Philipp

**Comment by philwo** [comment]
It's working now! 😊  See here: https://buildkite.com/bazel/limdor-bazel-examples/builds/66#44537b8d-7995-4459-a31c-27ef6c297222

**Comment by limdor** [comment]
Thanks for the retrigger, I just merge it. I found it because I decided to add to the CI all images available :-)
