### ISSUE TITLE
Update pip version on macOS machines

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#1284]
Bazel Bench is failing on macOS when installing python pip dependencies with:
https://buildkite.com/bazel/bazel-bench/builds/1205#dc6dcde4-9ea2-4d42-8afc-31840912af52
```
  numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.
```

This issue https://github.com/scipy/scipy/issues/13102#issuecomment-962468269 indicates upgrading pip to the latest version can solve the problem.

**Comment by meteorcloudy** [comment]
@philwo Can you help upgrade the pip version? ;)

**Comment by meteorcloudy** [comment]
@fweikert Do you know how to upgrade the pip version on our mac VMs?

**Comment by fweikert** [comment]
I guess we need to ssh into each Mac worker individually and perform the update. The team drive should have a sheet with all IPs, let me see if I can find it.

**Comment by meteorcloudy** [comment]
Thanks!

**Comment by fweikert** [comment]
Updated 20 iMac Pros and 4 Mac Pros from 21.3 to 21.3.1

**Comment by philwo** [comment]
@fweikert How, which commands did you run?

**Comment by fweikert** [comment]
´pip install --upgrade pip`

**Comment by meteorcloudy** [comment]
Still failing at https://buildkite.com/bazel/bazel-bench/builds/1218#42d94548-e083-43f5-92e3-c65868c16005
Maybe it should be
```
/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip
``` ?

**Comment by meteorcloudy** [comment]
Wait, I don't see the `You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.` warning anymore, but still have the error message: `ERROR: No matching distribution found for scipy==1.5.0`

**Comment by philwo** [comment]
@fweikert OK, I think that's fine. :) Thank you!

I asked, because I just remembered that I once broke the system Python installation when I upgraded pip - because there are multiple versions of Python and pip on these systems: One is provided by Xcode and we also install the latest Python from Homebrew.

See:

```
$ find / -name pip -or -name pip3 -or -name pip3.\*
/usr/bin/pip3
/usr/local/bin/pip3.9
/usr/local/bin/pip3
/usr/local/bin/pip
...
```

If you upgrade /usr/bin/pip3 provided by Xcode, stuff breaks. But upgrading the version in /usr/local/bin/pip3 is fine, because it's provided by Homebrew.

**Comment by philwo** [comment]
> You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command

I think pip just prints that always when a new version is available, it's probably unrelated to the error.

**Comment by fweikert** [comment]
That's definitely one thing we should document (and maybe fix).

**Comment by philwo** [comment]
There's nothing to fix, this is just how Python works 😄 The same would happen if you would update the pip version provided by the system on a Linux distribution.

We can document it, but in general handling stuff like this comes with experience and is nothing you can reliably document, as the whole situation can easily change with the next operating system or Xcode version etc.

I'd recommend whoever wants to maintain the machines in the future to spend a lot of time trying and experimenting with system maintenance to get a good feeling for these kind of things and also how to fix stuff when it breaks. (And it *will break. It happens all the time.)

I'll share all my scripts and notes with you, of course, that I took over the time!

**Comment by meteorcloudy** [comment]
Looks like it's the scipy version that needs to be upgraded https://github.com/bazelbuild/bazel-bench/pull/126
