### ISSUE TITLE
Buildkite not triggering on master from hook

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/continuous-integration#1296]
When pushing to master at https://github.com/rules-proto-grpc/rules_proto_grpc, no buildkite run is started. However, when pushing to another branch (see dev) the run is started as expected, suggesting the hook is working. I can still see the hook in place on the repo and the history shows it was delivered to buildkite on the master update.

Could you check if there is a branch-specific override in place for master? The nightly builds of master are still running though.

**Comment by meteorcloudy** [comment]
![image](https://user-images.githubusercontent.com/4171702/148191898-dc899e59-7af5-4c60-a4f5-b885cd4cd869.png)
I just enabled Build Branches option for this pipeline, it should work now. ;-)
