### ISSUE TITLE
Provides a report for test that shows where to look at -- define requirements

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#130]
A great summary of this come from bazelbuild/bazel#3795:

> 
> http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests/runs/263/nodes/30/steps/451/log/?start=0 contains the full execution log of bazel on macOS. The test log at the top of the bug was indeed taken from http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/263
> 
> The coloring of the steps are unfortunate, see https://issues.jenkins-ci.org/browse/JENKINS-39203 for the why. We use red to mark the step that has test failure (yellow means test failure).
> 
> The Global/bazel-tests was executed by the nightly (as stated in the title of the bug). So using Bazel @ 5d41dbe (from http://ci.bazel.io/job/bazel/job/nightly/62/, there is the name of the upstream job around in the log).

Basically for each test failure it would be great to have a link to one place that groups everything that could give clue when investigating.

This is a meta bug to define requirements.

**Comment by philwo** [comment]
Will be fixed as part of the new CI.
