### ISSUE TITLE
Follow up with JENKINS-39203 and fix the incorrect step marking

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#131]
Right now the coloring of the step in Blue Ocean is a mess due to https://issues.jenkins-ci.org/browse/JENKINS-39203.

Due to error catching, if a test is failing or the build is failing during the test phase the whole pipeline get yellow (or red) and the precise step that caused stay green or sometime even the wrong step is shown as red. The coloring is incorrect (all step as yellow, using red for failing tests) and point at the wrong step (at least the damage is limited it shows which platforms fails now).

We should follow up with this issue and https://issues.jenkins-ci.org/browse/JENKINS-45579 that are scheduled for resolution on the Jenkins side and fix the marking step as broken

**Comment by philwo** [comment]
Unfortunately this is still blocked on Jenkins. Looks like they don’t even have a plan on how to fix this yet. There’s no known workaround either, except for what we currently have. :(

**Comment by philwo** [comment]
Obsolete, as we're migrating away from Jenkins.
