### ISSUE TITLE
rules_apple failing with Head Deps: Infra failure?

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/continuous-integration#1314]
rules_apple seems to be failing with green Bazel using Head Deps, and the culprit could not be identified. Perhaps an infra change / failure?

```
error: frontend job retrieving target info failed with code 1: <unknown>:0: error: unsupported target architecture: 'in_x86_64'
```

https://buildkite.com/bazel/rules-apple-darwin/builds/5008#169a07c1-9b8f-4447-b873-d7e21308a293

`in_x86_64` looks like the beginning of `darwin_x86_64` ...

**Comment by c-parsons** [comment]
@meteorcloudy

**Comment by keith** [comment]
I think this is actually caused by https://github.com/bazelbuild/rules_swift/commit/918a4d6e2fe87c3cdadf8d66a25179740f0099d6

**Comment by keith** [comment]
going to revert and see if it fixes it https://github.com/bazelbuild/rules_swift/pull/748

**Comment by keith** [comment]
Yea looks like it was a bug in that change, so we can probably close this

**Comment by c-parsons** [comment]
many thanks
