### ISSUE TITLE
Add arm64 bazel for last_green commits

### ISSUE THREAD

**Issue by keith** [bazelbuild/continuous-integration#1338]
When using last_green with bazelisk, you get an x86_64 bazel even if you're on an arm64 mac. Ideally it would be an arm64 build of bazel. Might be related to https://github.com/bazelbuild/continuous-integration/issues/1112

**Comment by keith** [comment]
maybe fixed by https://github.com/bazelbuild/bazelisk/pull/303

sorry i assumed this was an upload issue

**Comment by fweikert** [comment]
Fixed in Bazelisk (for MacOS).
