### ISSUE TITLE
Provide Xcode 13.1 and above on macOS machines

### ISSUE THREAD

**Issue by thii** [bazelbuild/continuous-integration#1348]
rules_apple needs to test features that are only available with newer Xcodes, e.g. https://github.com/bazelbuild/rules_apple/pull/1393. Is there any plan to add newer Xcode versions (preferably 13.1, 13.2.1, and 13.3) to macOS machines? (newer versions don't need to be the default version)

**Comment by fweikert** [comment]
ETA for rolling out 13.4.1 and 14.2 is EOD tomorrow (Tuesday)

**Comment by fweikert** [comment]
Closing this issue since new versions of Xcode have been installed. I'll use #1431 to discuss the remaining issues.
