### ISSUE TITLE
Extract a Jenkins Shared Pipeline Library for reuse by other Jenkins

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#137]
We currently have a pipeline library that could be shared to offer better maintainability and create a better Jenkins experience.

/cc @davidstanke fyi

__Tentative API: Jenkins Shared Library tentative API__

```python
bazelJob(targets = ["//…"], tests = ["//…"], configure = [], build_opts = [], test_opts = [], startup_opts = [], extra_bazelrc = "")
```

Would be almost the same API as the current one, except for 2 things: there would be no stage name (we would not use any stage definition inside the `bazelJob`) and the bazel binary would not be provided but selected by another step. This job would basically do the configure steps, then bazel build and bazel test, with the given options.

```python
bazelBinary(version="latest", path=None)
```

Would select the Bazel binary used by any further `bazelJob`, the bazel binary would be automatically installed if not yet installed. You can provide either path (to an actual binary) or version (to fetch it from the Bazel server). If this step is not called, the `bazelJob` step will assume latest bazel is selected.

```python
bazelConfiguredJob(restrict_configuration={}, extra_bazelrc = "", workspace = "", config_files = ["scripts/ci/<job>.json", ".ci/<job>.json"]) { 
   fetch_step  // e.g. scm step
}
```

`bazelConfiguredJob` would be a variation of the current `bazelCiConfiguredJob` but with less options and allowing to use non git repositories by putting the fetch step in a closure. The `restrict_configuration` parameter can be used to restrict the allowed configurations on some system (we use it for testing infrastructure where not all platforms are available). `extra_bazelrc` are simply further content for the rc file used to build projects and workspace the directory where the workspace can be found. The step would look for the same configuration file we use currently in well known location specified by `config_files` and build bazel accordingly.

So to have a job capable of building bazel and running the tests on different platform, you would simply have to create a pipeline job on Jenkins that calls:

```python
bazelConfiguredJob {
   git url: "https://github.com/foo/bar.git"
}
```

The release features of our CI could also be exposed so people can release artifacts.

**Comment by philwo** [comment]
Won't fix, as we're migrating away from Jenkins.
