### ISSUE TITLE
Request to add new project: Crubit (https://github.com/google/crubit)

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/continuous-integration#1372]
URL: https://github.com/google/crubit

- [ ] My project is part of the bazelbuild GitHub organization.
- [ ] My project is a rules set of a GitHub organization other than bazelbuild.
- [*] I want to test the following project on Bazel CI: https://github.com/google/crubit
- [*] I confirm that the project has a `.bazelci/presubmit.yml` file.

Thank you!!

**Comment by hlopko** [comment]
Pretty please? :)

**Comment by fweikert** [comment]
Please follow the instructions at https://buildkite.com/bazel/crubit/settings/setup/github to set up GitHub integration

**Comment by hlopko** [comment]
Is it possible I don't have permissions to see that page?

**Comment by hlopko** [comment]
"You don’t have the required access level to change this pipeline"

**Comment by fweikert** [comment]
Ok, I know why: I granted full access to the Googlers team, but you weren't a member. I fixed it - can you please try again?

**Comment by hlopko** [comment]
Yay it works now!! Thank you so much!
