### ISSUE TITLE
Use HSTS redirection for every site of bazel.{io,build} domains

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#139]
We currently rely on JS redirection because it is not supported by GCS. Jenkins does not do redirection either through it is probably feasible.

We can route the traffic on a different backend depending in the protocol using GCLB so we could instead just redirect everything on HTTP to a backend that just send a HSTS header.

**Comment by davidstanke** [comment]
Redirect for HTTP --> HTTPS is now in place. I still have some cleanup to do though.

And IDK whether we'll actually do HSTS: that header has to be served by the server that serves HTTPS, which for the CI server is Jenkins, which makes it more fussy. And it's not strictly necessary, though it is a nice optimization.

**Comment by davidstanke** [comment]
Closing this; we have server-side redirection to SSL for all domains now. We don't have HSTS, but I'm okay with that.
