### ISSUE TITLE
Publish arm64 Linux binaries for commits

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1402]
There have been requests for such binaries. We already publish arm64 Linux binaries for releases (LTS + rolling).

**Comment by keith** [comment]
anything we can do to prioritize this? it would be useful to be able to test last_green on arm64 linux

**Comment by fweikert** [comment]
I'll bring it up at the next standup, but I don't think we'll have any capacity for this in the near future.

**Comment by meteorcloudy** [comment]
Also sent a bazelisk change

**Comment by keith** [comment]
thanks!
