### ISSUE TITLE
Respect user-defined .bazelrc

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/continuous-integration#141]
I started a PR https://github.com/bazelbuild/BUILD_file_generator/pull/13 with a `.bazelrc` file in it, which changes some flags.

`ci.bazel.build` specified its own `bazelrc` using the `--bazelrc=` flag, overriding mine.

Is it feasible to support user-defined `.bazelrc` files?

**Comment by damienmg** [comment]
Put the file in tools/bazel.rc instead?

**Comment by cgrushko** [comment]
I don't think it matters? the command-line flag will override it either way.
I tried it and am still getting
http://ci.bazel.io/blue/organizations/jenkins/PR%2FBUILD_file_generator/detail/BUILD_file_generator/4/pipeline

**Comment by damienmg** [comment]
it is `tools/bazel.rc` not `tools/.bazelrc`

The flag overwrite the user bazel not the masters bazelrc so it should work

**Comment by damienmg** [comment]
(see https://blog.bazel.build/2015/07/01/Configuration-File.html)

**Comment by cgrushko** [comment]
Ah, that works :)
Thanks!
(it's inconsistent with what we have internally - I expected this file to be the bazel binary itself)
