### ISSUE TITLE
Make bazelisk-plus-incompatible-flags pipeline useful again

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#1410]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags has been broken since Bazel moved to LTS model. We should fix this pipeline to provide useful information for downstream projects on upcoming incompatible flags and hopefully accelerate incompatible flags flip in Bazel.

**Comment by aiuto** [comment]
In #349 there was a comment about bringing back the github label system. I would recommend agains that. Looking at the github labels was a strange hack and few of us got the labels right so it was always a little wrong.

We should simply have a file in bazelbuild/bazel of the flags we intend to flip for the next release. That has some advantages:
- The file becomes a roadmap of what we intend.
- It can include comments about the timelines
- Since it is with the bazel source we can easily integrate it into any CI chain.
- If we want, we can use it to generate a bazelrc file that we could provide alongside bazel releases.  That would satisfy the request which came up in the rules SIG for such a file.

**Comment by meteorcloudy** [comment]
> In https://github.com/bazelbuild/continuous-integration/issues/349 there was a comment about bringing back the github label system.

Hmm, I don't see such comment in that bug.

I think we should still have github issues tracking each incompatible flag. In the bug, the author can write migration guide and users can report issues. A file is very hard to achieve that.

How does the updated process in https://github.com/bazelbuild/bazel/pull/16195 sounds to you? In the end, there are only two labels to mange "incompatible-change" and "migration-ready" label. I also plan to send out an email to bring attention to the team.

**Comment by aiuto** [comment]
Wrong repo.  I meant https://github.com/bazelbuild/bazelisk/pull/349

We still need the github issue per flag to have conversations. Having bazelisk query github to decide how to run is the problem. It means there is no consolidated place where someone can see the intent for the next LTS release.  Users don't really care about the flags themselves.  They want to know "What is bazel 6.x going to be?".  Having a single place to understand that is easier than having to do a very precise github query.

The other advantage of a rc file with the source is that we can version it with each LTS branch.  So the 6.0 release can run with all the things we expect to flip for 6.1, while HEAD can have everything we expect to flip for 7.x.  Getting that right with github labels was not scalable.

**Comment by meteorcloudy** [comment]
> Wrong repo. I meant https://github.com/bazelbuild/bazelisk/pull/349

Oh, I see. You meant for Bazelisk to fetch flags from github. I don't feel strongly about that.

> So the 6.0 release can run with all the things we expect to flip for 6.1

What do you mean? We shouldn't flip incompatible flags in minor version release.

I think we are trying to solve two different problems:

- A. I'm trying to implement a pipeline and process to help core projects migrate and make it easier to flip a flag.
- B. You're trying to have a way to make sure users flip some flags by default so that they won't be accidentally broken in future.

The solutions are not contradicting each other. In fact, A will be necessary for B, because if some basic dependencies are not migrated, it's impossible for projects that depend on those dependencies to flip the flag in a bazelrc file.
