### ISSUE TITLE
rules_python is failing in downstream only

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/continuous-integration#1426]
Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2615#01831b45-55d6-4dc4-ab2a-380a90ae2c2b

Main build is fine, so we need to find the culprit Bazel commit that caused this.

**Comment by meteorcloudy** [comment]
After fixing the cache poisoning issue, this test is also failing in the main build:
https://buildkite.com/bazel/rules-python-python/builds/3352#0183322f-5297-43ea-a9da-4b7cd2a84f1f

**Comment by meteorcloudy** [comment]
Closing in favour of https://github.com/bazelbuild/rules_python/issues/827
