### ISSUE TITLE
rules_go is failing on RBE in downstream only; main build fine

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/continuous-integration#1429]
Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2618#01831d43-1070-4452-90de-85bd2d686223

Culprit finder run (https://buildkite.com/bazel/culprit-finder/builds/3519#01831b54-279b-4443-87f1-c2ddcc977723) points to this commit (https://github.com/bazelbuild/bazel/commit/6a66b0b8c731b86af0c5cf92a0cabf8a4ee42c5d) which makes zero sense as this build doesn't even enable Bzlmod.

**Comment by meteorcloudy** [comment]
A manual bisect points to https://github.com/bazelbuild/bazel/commit/943e8cfb9970ca86f88ba60c944601573b366db5

**Comment by meteorcloudy** [comment]
`//tests/core/coverage:lcov_coverage_test` and `//tests/core/coverage:lcov_test_main_coverage_test` are broken by https://github.com/bazelbuild/bazel/commit/a70d84b9eaae99f665ccdebd68eb3da57e07530b

**Comment by Wyverald** [comment]
Turns out the `//tests/core/cross:non_executable_test` failure is fixed by flipping https://github.com/bazelbuild/bazel/issues/16196. Catch-22 :)
