### ISSUE TITLE
Allow injecting dependencies through `--override_repository`

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#143]
Both rules_scala / intellij and the abseil people would like to test some downstream dependencies are not broken by downstream project.

We should have the possibility to git clone a repository and inject it with `--override_repository`. Right now it should be possible with configure in a hacky way (see https://github.com/bazelbuild/rules_scala/issues/308#issuecomment-336838679) but we should be able to inject that in an easier way. E.g. for now just specify the repository to git clone and once we have recursive workspace probably just specify a WORKSPACE file to override.

Ideally that could be passed down to bazel/presubmit so we have immediately global presubmit for abseil and other dependencies (not very efficient, but so far we are not constrained by that, more by peak hours during munich time).

/cc @ittaiz @gennadiycivil

**Comment by philwo** [comment]
This is out of scope for our CI.

**Comment by ittaiz** [comment]
Where do you think this should sit?
Btw, at least a part of it is completely CI scope since we will need it to
move our e2e tests from Travis to bazel ci
