### ISSUE TITLE
Install Android NDK 25 on macOS

### ISSUE THREAD

**Issue by keith** [bazelbuild/continuous-integration#1436]
https://github.com/bazelbuild/continuous-integration/pull/1434

**Comment by meteorcloudy** [comment]
`/Users/buildkite/android-ndk-r25b` should be available on all macOS machines now. Please set your `ANDROID_NDK_HOME` to test it. 

Feel free to reopen if it doesn't work.

/cc @ahumesky

**Comment by meteorcloudy** [comment]
Testing in https://github.com/bazelbuild/rules_android_ndk/pull/17

**Comment by ahumesky** [comment]
thank you!

**Comment by keith** [comment]
thanks!
