### ISSUE TITLE
upb is failing in Bazel@HEAD+downstream (main build fine)

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/continuous-integration#1439]
example breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2631#01833787-115d-48d9-938c-084b2f36562c

Culprit finder does not give any useful information; I couldn't find a good commit on the master branch at all.

**Comment by meteorcloudy** [comment]
I did a manually bisect between HEAD and 5.0.0 base commit (8d66a4171baddcbe1569972f019e54130111202c), it points to 
b33c5352fe59ded9dfcf10668bf104f977092218
