### ISSUE TITLE
Use redirector to point to canonical domains

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/continuous-integration#144]
Currently, the http --> https redirector will issue a 301 for all traffic on http://*.bazel.* to https://{request}. But it otherwise leaves the request unchanged.

We should update it so that it will point *.bazel.io --> *.bazel.build.

@damienmg should we make ci.bazel.build canonical (rather than ci.bazel.io)?

Any other domain redirections we should do?

Once this is complete, we can remove the javascript redirectors that are present on some of the sites.

**Comment by damienmg** [comment]
We should not do it for ci. There is a bunch of implications and the https
change was burdensome enough that we do not want to repeat it until we
switch off Jenkins.

**Comment by davidstanke** [comment]
Yup. Makes sense. Given that, I will force ci.bazel.build --> ci.bazel.io. (Currently, ci.bazel.build does resolve, to the Jenkins server, but then it breaks if you try to do anything interesting. Like logging in.)

**Comment by davidstanke** [comment]
Canonical domains:

https?://ci.bazel.build --> https://ci.bazel.io
http://ci.bazel.io --> https://ci.bazel.io

https?://(.*).bazel.io --> https://$1.bazel.build [except for ci.bazel.io]
http://(.*).bazel.build --> https://$1.bazel.build [except for ci.bazel.build]

**Comment by davidstanke** [comment]
To change NGINX config:
1. In GCP console, go to images
2. launch a temporary instance from the newest http-redirector image
3. edit config in the temp instance; test using curl
4. create a new http-redirector image from the instance
5. perform rolling replace on http-redirector instance group from prior image to new image
6. terminate the tem instance
7. deprecate the prior image

**Comment by davidstanke** [comment]
Canonical domain redirects have been implemented.
