### ISSUE TITLE
TensorFlow fails on Bazel@HEAD on Ubuntu & macOS; Windows fine, main build fine

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/continuous-integration#1443]
Example breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2632#018339c1-ea46-4950-b9ab-d91777f4c24d

Culprit finder barfs for both platforms: https://buildkite.com/bazel/culprit-finder/builds/3582

**Comment by meteorcloudy** [comment]
Closing in favor of https://github.com/bazelbuild/bazel/issues/16296
