### ISSUE TITLE
Windows Build Failed, but didn't report an error

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#146]
See https://ci.bazel.io/blue/organizations/jenkins/CR%2Fbazel-tests/detail/bazel-tests/541/pipeline/36, specifically the node=windows-x86_64,toolchain=msvc node.

The node is green and no error is reported, but when you look, it says "Windows batch script" failed, and shows the error that is not reported elsewhere, namely:
```
third_party/grpc/src/cpp/client/create_channel.cc(57): error C2065: 'unused': undeclared identifier
third_party/grpc/src/cpp/client/create_channel.cc(57): error C3861: '__attribute__': identifier not found
third_party/grpc/src/cpp/client/create_channel.cc(58): error C2143: syntax error: missing ';' before 
```

This caused a breaking change to be merged.

**Comment by damienmg** [comment]
Not sure we can do anything here :(

**Comment by philwo** [comment]
Obsolete, as we're migrating away from Jenkins.
