### ISSUE TITLE
Disable failing Gerrit tests until upstream is fixed

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#147]
Until the upstream issue https://bugs.chromium.org/p/gerrit/issues/detail?id=7611 is fixed, we should disable Gerrit testing.

**Comment by katre** [comment]
Only disabling the failing test, //javatests/com/google/gerrit/server:query_tests

**Comment by katre** [comment]
Now //javatests/com/google/gerrit/acceptance/server/notedb:server_notedb is showing the same behavior.

**Comment by buchgr** [comment]
seems to have been fixed. can be closed.
