### ISSUE TITLE
bazel-tests failing consistently on freebsd-12

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#149]
Error message is:
```
Failed to copy /var/jenkins_home/jobs/bazel/jobs/nightly/builds/106/archive/node=freebsd-12/variation=/bazel to /home/ci/workspace/Global/bazel-tests-node=freebsd-12/.bazel/bazel
```

Example: https://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/332/pipeline/29

**Comment by katre** [comment]
None of the freebsd-12 nodes have a "/var/jenkins_home" directory.

**Comment by katre** [comment]
Nightly run for 11/2 on freebsd-12 shows success, but the artifact is not downloadable:
https://ci.bazel.io/job/bazel/job/nightly/107/artifact/node=freebsd-12/variation=/bazel

Other artifacts for other platforms are downloadable, so this is probably the issue.

**Comment by katre** [comment]
Looks like a permissions issue:
```
jcater@jenkins:/volumes/jenkins_home$ ls -l jobs/bazel/jobs/nightly/builds/107/archive/node\=freebsd-*/variation\=/bazel 
-r-xr-xr-x 1 jcater jcater 89858786 Nov  2 00:01 jobs/bazel/jobs/nightly/builds/107/archive/node=freebsd-11/variation=/bazel
------xrw- 1 jcater jcater 91971332 Nov  2 00:01 jobs/bazel/jobs/nightly/builds/107/archive/node=freebsd-12/variation=/bazel
```

**Comment by damienmg** [comment]
This is preventing us from correctly testing Bazel. FreeBSD-12 is a pre-release so I will deactivate it for now.

**Comment by aehlig** [comment]
> Looks like a permissions issue:
> ```
> jcater@jenkins:/volumes/jenkins_home$ ls -l jobs/bazel/jobs/nightly/builds/107/archive/node\=freebsd-*/variation\=/bazel 
> -r-xr-xr-x 1 jcater jcater 89858786 Nov  2 00:01 jobs/bazel/jobs/nightly/builds/107/archive/node=freebsd-11/variation=/bazel
> ------xrw- 1 jcater jcater 91971332 Nov  2 00:01 jobs/bazel/jobs/nightly/builds/107/archive/node=freebsd-12/variation=/bazel
> ```

Interestingly enough, the permission issue is either a jenkins thing or has to
do with the way we do copying (maybe a missing `-p`); on the freebsd-12 slaves,
all the files called bazel have permissions 555 or 755.

Appart from the permissions, the actual file copying seems to work fine.

```
[root@freebsd-12-slave-4 /home/ci]# ls -l ./workspace/bazel/nightly/output/node=freebsd-12/variation=/bazel
-r-xr-xr-x  1 ci  ci  91933532 Nov 13 06:17 ./workspace/bazel/nightly/output/node=freebsd-12/variation=/bazel
[root@freebsd-12-slave-4 /home/ci]# sha256 ./workspace/bazel/nightly/output/node=freebsd-12/variation=/bazel
SHA256 (./workspace/bazel/nightly/output/node=freebsd-12/variation=/bazel) = 89e646b3de9bcb8b302a5459a24e40b84bc3396a733a74f11ae46f167979550c
[root@freebsd-12-slave-4 /home/ci]#
```

and

```
root@jenkins:/volumes/jenkins_home/jobs/bazel/jobs/nightly/builds# ls -l 123/archive/node=freebsd-12/variation=/bazel
-r--rwx--- 1 jcater jcater 91933532 Nov 13 06:17 123/archive/node=freebsd-12/variation=/bazel
root@jenkins:/volumes/jenkins_home/jobs/bazel/jobs/nightly/builds# sha256sum 123/archive/node=freebsd-12/variation=/bazel
89e646b3de9bcb8b302a5459a24e40b84bc3396a733a74f11ae46f167979550c  123/archive/node=freebsd-12/variation=/bazel
root@jenkins:/volumes/jenkins_home/jobs/bazel/jobs/nightly/builds# 
```



-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
It seems to be a known that Jenkin's "archive artifacts" does not preserve permissions, even though the report mentions that they're set to a fixed value; https://issues.jenkins-ci.org/browse/JENKINS-13128

Probably we also have to work around and set permissions on the receiving side manually.

**Comment by aehlig** [comment]
Over to @damienmg who better understands our CI setup and hence might know where to add the hook for manually fixing the permissions that are lost in the transfer from the slave to the master.
