### ISSUE TITLE
Mac hosts are not provisioned with Android SDK 31

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/continuous-integration#1494]
It seems that the Android 31 SDKs aren't yet provisioned on mac hosts despite it being listed in the [mac installer](https://github.com/bazelbuild/continuous-integration/pull/1364/files#diff-ec65c857dda5dc707bc531d34707491ccb13ffc0117c33f368b84af476415679R30).

Buildkite failure where a mac host explicitly targeting 31 fails to find the SDK https://buildkite.com/bazel/bazel-bazel-examples/builds/1635#01847724-1d95-4de3-b48e-60d113b79700/243-253

**Comment by Bencodes** [comment]
@meteorcloudy are you the right person to help deploy this?

**Comment by fweikert** [comment]
We're not using the installer script. I manually installed SDK 31 on the 28 older MacOS workers.

**Comment by Bencodes** [comment]
Thanks @fweikert!

**Comment by fweikert** [comment]
Ok, I'll keep this issue open to remind me to update the M1 Macs as well.
