### ISSUE TITLE
No matching toolchain when bzlmod is enabled

### ISSUE THREAD

**Issue by mai93** [bazelbuild/continuous-integration#1518]
[rules_proto](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2792#01852ade-4cab-4c9a-8595-fd4d92e1ea0c) and [bazel skylib](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2792#01852ade-39a4-4a7b-84b5-52f40243b734) are failing with similar error when built with bazel@head and bzlmod enabled

```
No matching toolchains found for types @bazel_tools//tools/jdk:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@bazel_tools//tools/jdk:toolchain_type'
```

A change related to the missing toolchain type was introduced [here](https://github.com/bazelbuild/bazel/commit/f23440b60337c9d74b9dfde1f7fd66e42181714f) but these tests are passing if bzlmod is not enabled.

**Comment by meteorcloudy** [comment]
https://cs.opensource.google/bazel/bazel/+/master:src/MODULE.tools;l=20-28?q=MODULE.tools&ss=bazel

@comius I guess we have to make similar changes (https://github.com/bazelbuild/bazel/commit/f23440b60337c9d74b9dfde1f7fd66e42181714f) to rules_java? Or should we just load the toolchains from @bazel_tools first, like we did for other languages?

**Comment by meteorcloudy** [comment]
BTW, this should be a bug in Bazel.

**Comment by comius** [comment]
There are two underlying issues.
One is that cc_test pulls in coverage tools which are built using Java. This one is solved by https://github.com/bazelbuild/bazel/pull/16995

Second issue is that all Java projects require `--java_language_version` and/or `--tool_java_language_version` setting, because default was removed in https://github.com/bazelbuild/bazel/commit/f23440b60337c9d74b9dfde1f7fd66e42181714f
Solution is either to re-add the default or to add a "default toolchain" in rules_java.

**Comment by comius** [comment]
Re @meteorcloudy: for the sake of consistency we should also register toolchain in bazel_tools. That is because cc rules when coverage is enabled need Java. And minimal cc project should not need to depend on rules_java in order to run coverage.

**Comment by meteorcloudy** [comment]
To clarify, do you mean https://github.com/bazelbuild/bazel/pull/16995 alone will solve this problem?

**Comment by comius** [comment]
https://github.com/bazelbuild/bazel/pull/16995 solves problem with cc targets when coverage is not run.
Release of rules_java and version upgrade will define default toolchain and solve the problem also for Java in general (cc coverage included).

**Comment by meteorcloudy** [comment]
Thanks, but do we still need https://github.com/bazelbuild/rules_java/pull/81?

**Comment by comius** [comment]
> Thanks, but do we still need [bazelbuild/rules_java#81](https://github.com/bazelbuild/rules_java/pull/81)?

No. Liam already did the necessary changes.
