### ISSUE TITLE
Unused test_http function with invalid return value

### ISSUE THREAD

**Issue by Androbin** [bazelbuild/continuous-integration#153]
The shell script [`jenkins/test/common.sh`](https://github.com/bazelbuild/continuous-integration/blob/master/jenkins/test/common.sh) contains a function [`test_http`](https://github.com/bazelbuild/continuous-integration/blob/master/jenkins/test/common.sh#L48) which tries to return a boolean value which it can't. This repository doesn't reference this function anywhere.

**Comment by Androbin** [comment]
@damienmg Friendly ping

**Comment by damienmg** [comment]
Yes we should just delete the function.
