### ISSUE TITLE
CI agent got into bad state under macOS

### ISSUE THREAD

**Issue by f0rmiga** [bazelbuild/continuous-integration#1548]
https://buildkite.com/bazel/rules-python-python/builds/4322#01864c91-26b1-4625-8c53-4ca9d99ea35d

On rules_python, I noticed that an agent got into a bad state and couldn't self-heal.

**Comment by fweikert** [comment]
That's https://github.com/bazelbuild/continuous-integration/issues/1550 which should be fixed by now (unfortunately this error likes to haunt us from time to time - we need to find out what the root cause is).

**Comment by f0rmiga** [comment]
Thank you!
