### ISSUE TITLE
Request to add project rules_testing

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/continuous-integration#1549]
https://github.com/bazelbuild/rules_testing

To request a review for being added to Bazel CI, please follow the instructions below.

- [x] My project is part of the bazelbuild GitHub organization.
- [x] I want to test the following project on Bazel CI: https://github.com/bazelbuild/rules_testing
- [x] I confirm that the project has a `.bazelci/presubmit.yml` file.

# Instructions (you can delete this section from the issue)

Welcome to Bazel CI! We are thrilled that you want to test your project with Bazel.
Please follow these steps to make the on-boarding experience as smooth as possible:

Notes to self:
1. Read the [introduction to Buildkite](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md) to learn about the basic concepts such as pipelines.
2. Create and commit your presubmit configuration in `<YOUR REPO>/.bazelci/presubmit.yml`. The configuration format is documented [here](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#configuring-a-pipeline), and you can find several an example [here](https://github.com/bazelbuild/rules_typescript/blob/master/.bazelci/presubmit.yml).

**Comment by rickeylev** [comment]
cc @comius

**Comment by rickeylev** [comment]
I saw there's been a couple commits. Thanks! I've added a .bazelci configuration.

Are there additional steps I need to do? I was looking around buildkite to see if I could trigger a build for it manually, but couldn't find it.

**Comment by meteorcloudy** [comment]
It seems we added the config for rules_testing in terraform but never deploy it, I'll take a look now.

**Comment by meteorcloudy** [comment]
@rickeylev The rules-testing pipeline is now deployed and here is the result of the first run:
https://buildkite.com/bazel/rules-testing/builds/1

You would also want to set up the Github Webhook by following:
https://buildkite.com/bazel/rules-testing/settings/setup/github

**Comment by rickeylev** [comment]
This is done. Thanks!
