### ISSUE TITLE
Remove javascript redirects from bazel.io --> bazel.build

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/continuous-integration#155]
there are js redirects on https://bazel.build -- and on some other sites I believe -- that can be removed now that we're redirecting from the load balancer.

**Comment by davidstanke** [comment]
Closing: wrong repo. Will reopen in bazelbuild/bazel-website.

**Comment by drigz** [comment]
Corresponding issue: https://github.com/bazelbuild/bazel-website/issues/74
