### ISSUE TITLE
Error: "/usr/local/var/bazelbuild: permission denied" (maybe bk-imacpro-11 specific?)

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/continuous-integration#1550]
Over in rules_python, we're noticing a regular flaky error that goes away after retrying. A few examples:

* https://buildkite.com/bazel/rules-python-python/builds/4336#01864dbf-a3e7-4f56-8417-eea3c5dbe8e1
* https://buildkite.com/bazel/rules-python-python/builds/4320#01864c7e-7f5b-432f-90f4-be286d079b25

> # Creating "/Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python"
> --
>   | $ cd /Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python
>   | # Using git-mirrors experiment 🧪
>   | # Creating "/usr/local/var/bazelbuild"
>   | ⚠️ Warning: Checkout failed! mkdir /usr/local/var/bazelbuild: permission denied (Attempt 1/3 Retrying in 2s)
>   | # Removing /Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python
>   | # Creating "/Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python"
>   | # Using git-mirrors experiment 🧪
>   | # Creating "/usr/local/var/bazelbuild"
>   | ⚠️ Warning: Checkout failed! mkdir /usr/local/var/bazelbuild: permission denied (Attempt 2/3 Retrying in 2s)
>   | # Removing /Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python
>   | # Creating "/Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python"
>   | # Using git-mirrors experiment 🧪
>   | # Creating "/usr/local/var/bazelbuild"
>   | ⚠️ Warning: Checkout failed! mkdir /usr/local/var/bazelbuild: permission denied (Attempt 3/3 Retrying in 2s)
>   | # Removing /Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python
>   | # Creating "/Users/buildkite/builds/bk-imacpro-11/bazel/rules-python-python"
>   | 🚨 Error: mkdir /usr/local/var/bazelbuild: permission denied

All of these seem to only happen with mk-imacpro11; all the failures I've seen have that host.

**Comment by fweikert** [comment]
Unfortunately this problem seems to affect individual iMacs from time to time. I fixed it this time (at least imac-11 is now failing with a different error -,-): https://buildkite.com/bazel/google-bazel-presubmit/builds/63510#01865002-d78e-461d-8fa0-b15f4a084ad4
