### ISSUE TITLE
Improve UX for skipped downstream tasks

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1561]
https://buildkite.com/bazel/bazel-at-head-plus-downstream runs the tasks specified in all downstream projects' CI configs, but with a custom Bazel binary built at HEAD. This may result in duplicate jobs since some projects build/test the same set of targets with two different versions of Bazel. 

We addressed this problem some time ago by skipping such duplicate tasks, which are mentioned in a build annotation [*].

However, #1455 shows that there is some confusion due to the subpar UX.

[*] Currently this mechanism is not working due to a bug, but will be fixed with #1557

**Comment by meteorcloudy** [comment]
Should this be closed by https://github.com/bazelbuild/continuous-integration/pull/1576?
