### ISSUE TITLE
Cargo-Raze failing on macOS infra on both downstream & Bazel CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1594]
Cargo-Raze failing on macOS infra on both downstream & Bazel CI.

**Downstream** : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2975#0187b105-4064-4b60-b3cc-bfff4bfa1749
**Cargo-Raze CI** : https://buildkite.com/bazel/cargo-raze/builds/1251#0187b09a-d399-4a61-8582-a7277a1c5bcb

**Steps followed to reproduce in local machine:**

1.  git clone https://github.com/google/cargo-raze.git 
2. git reset afe9b483b0449eb043f3fa8aa08f62afffcfa2ed --hard
3. export USE_BAZEL_VERSION=bbf78a2cec27bf42bcbba59d3f84c857dff3aa15
4. bazel build ...

**Error Logs:**
```

ERROR: /Users/sgowroji/bazelci/bazelhead_downstream/cargo/cargo-raze/impl/BUILD.bazel:45:10: Compiling Rust bin cargo_raze_lib_test (16 files) failed: (Exit 1): process_wrapper failed: error executing command (from target //impl:cargo_raze_lib_test) bazel-out/darwin_x86_64-opt-exec-ST-fd2704146ab2/bin/external/rules_rust/util/process_wrapper/process_wrapper --arg-file ... (remaining 341 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging: process_wrapper failed: error executing command (from target //impl:cargo_raze_lib_test) bazel-out/darwin_x86_64-opt-exec-ST-fd2704146ab2/bin/external/rules_rust/util/process_wrapper/process_wrapper --arg-file ... (remaining 341 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error: linking with `external/local_config_cc/cc_wrapper.sh` failed: exit status: 1
```

CC @meteorcloudy & @SalmaSamy

**Comment by meteorcloudy** [comment]
The error looks similar to https://github.com/bazelbuild/continuous-integration/issues/1587, so might also be related to a bug in Xcode 14.2

**Comment by UebelAndre** [comment]
[cargo-raze](https://github.com/google/cargo-raze) is no longer maintained. It's CI could probably be retired.

**Comment by meteorcloudy** [comment]
Already done in https://github.com/bazelbuild/continuous-integration/pull/1738
