### ISSUE TITLE
Publish a list of all release candidates (feature request)

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/continuous-integration#160]
Feature request: maintain a list of all release candidates. When a new candidate is cut, this list is automatically updated.

The list can have just one line per RC, which links to its detailed info (e.g. https://storage.googleapis.com/bazel/0.8.0/rc1/index.html)

**Comment by buchgr** [comment]
We are planning on removing the html release side on google cloud storage and to instead publish all the release candidates to the GitHub release page and marking them as "pre-release". People interested in all release candidates can either look at them on the release site or programmatically fetch them via the GitHub API.

Please re-open if this doesn't fit your indented use case.
