### ISSUE TITLE
Run all tests

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/continuous-integration#161]
Somehow on the current _HEAD_ one cannot run `bazel test //src/...`. IMO this is the only way of at least testing whether changes broke some part of Bazel. As long as this is not the default modus operandi (and tested for every commit), there is no way contributors can validate their work. Which in turns just means way more work for Bazel devs (AKA Google employees).

**Comment by buchgr** [comment]
cc @philwo

**Comment by philwo** [comment]
The recommended way is to use Bazel's CI or look at the config files and use the same set of test targets for a given platform: https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml#L13
