### ISSUE TITLE
CI target expansion is broken

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1614]
bazelci.py uses `bazel query` to expand target patterns such as `...` to a list of actual labels: https://github.com/bazelbuild/continuous-integration/blob/051f978c1b9cc662009c0997f7d7f175f88a7b95/buildkite/bazelci.py#L2125

Before https://github.com/bazelbuild/continuous-integration/commit/ecf091cbe37ccfdd2e62c8b9ee024876dd0ced82 this code only ran when sharding was enabled, but after the change it runs before every test invocation.

Unfortunately the query returns too many targets since it ignores the `--test_tag_filters` flag as well as any `target_compatible_with` attributes, e.g. https://buildkite.com/bazel/rules-testing/builds/157#0187ca82-94aa-4596-bb77-d67ad31e9aa5 and https://github.com/bazelbuild/continuous-integration/issues/1613

**Comment by fweikert** [comment]
https://github.com/bazelbuild/continuous-integration/issues/1612 seems to be another unintended side-effect (command line length too long).

**Comment by fweikert** [comment]
Example on Windows: https://buildkite.com/bazel/google-bazel-presubmit/builds/66532#0187e1cc-1a05-4f41-a2a4-b16b9d703b17

**Comment by fweikert** [comment]
Current status:
- I implemented an experimental switch that allows us to use cquery instead of query based on the EXP_USE_CQUERY env variable in https://github.com/bazelbuild/continuous-integration/pull/1626
- I had to uncomment some maven-related stuff in the WORKSPACE file since cquery was failing (https://bazel-review.git.corp.google.com/c/bazel/+/209336)
- Now some tests are failing since we don't have maven installed on our CI workers: https://buildkite.com/bazel/google-bazel-presubmit/builds/66624#_

**Comment by meteorcloudy** [comment]
I guess this is already fixed.
