### ISSUE TITLE
Bazel Bzlmod build fails on macos in downstream CI.

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1619]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2995#0187dfc8-8084-4f39-a9dd-0fbdcc01908e

Platform : Bazel (Bazel Bzlmod build on :mac: (OpenJDK 11, Xcode))

```
error: use of private header from outside its module: 'zconf.h' [-Wprivate-header]
--
  | #include <zconf.h>
  | ^
  | 1 error generated.

```

CC @meteorcloudy

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/1272 says it's https://github.com/bazelbuild/bazel/commit/699e40373f95e42390a85f29dfa1098636336103

**Comment by Wyverald** [comment]
I'm pretty stumped. Couldn't repro on my M1 Mac either. @googlewalt any ideas?

**Comment by googlewalt** [comment]
The culprit CL "migrated" the apple toolchain from bazel to apple_support which is maintained by OSS.  The reported error is from layering check, which I am surprised is enabled at all for OSS.  @keith can you confirm that layering check is enabled in the bazel Apple toolchain, and did this happen relatively recently?  If so it is possible that grpc 1.48.1 is not layering check compliant.

**Comment by keith** [comment]
Since bazel isn't using the apple_support toolchain it started getting the layering check when it started using the unix toolchain, related https://github.com/bazelbuild/bazel/pull/17763

**Comment by keith** [comment]
Fix is merged. Can we verify it fixed it)

**Comment by Wyverald** [comment]
doing a downstream run is quite expensive and we're resource-starved atm, so let's just wait until tomorrow to see.

**Comment by sgowroji** [comment]
Verifying and Closing the above issue, It is fixed in latest [Downstream](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3025#01882252-2e0e-46ea-acd1-7e52ed62f4e6) CI.
