### ISSUE TITLE
Flaky tests should be disabled on BazelCI 

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/continuous-integration#1631]
| Test | Example flake |
| ---  | --- |
| `src/test/java/com/google/devtools/build/lib/skyframe/LocalDiffAwarenessIntegrationTest`| [buildkite](https://buildkite.com/bazel/google-bazel-presubmit/builds/66638#0187e935-e6f2-462b-bd83-a346be309851) 
|`src/test/shell/bazel/bazel_sandboxing_networking_test` | [buildkite](https://buildkite.com/bazel/google-bazel-presubmit/builds/66527#0187e1af-70d9-4d9b-b2f0-d28f013ec455) |
| Windows tests | [buildkite](https://buildkite.com/bazel/google-bazel-presubmit/builds/66540#0187e20e-c05e-428a-884d-9f6d1efbefbf) 
| `src/test/java/com/google/devtools/build/lib/remote/remote` | [buildkite](https://buildkite.com/bazel/google-bazel-presubmit/builds/66640#0187e9bb-8c51-4da7-b050-2666a4c916b6) |

IMHO these tests add quite a bit of inertia to submitting changes, especially when we have a chain of small CLs to submit.

From my own experience: the 3 automatic trials almost never resolves the flakes. It's only when we manually click the retry button from BuildKite does the result differ.

**Comment by sgowroji** [comment]
Adding few more flaky tests from downstream CI.

Test | Example flake
-- | --
```src/test/shell/bazel:bazel_coverage_java_jdk11_toolchain_head_test``` | [buildkite](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3045#01884b85-614f-4048-a8d3-79784f66168e)
```src/test/shell/bazel:bazel_hermetic_sandboxing_test``` | [buildkite](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3045#01884b85-614f-4048-a8d3-79784f66168e)
```src/test/shell/bazel:bazel_proto_library_test```  | [buildkite](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3045#01884b85-614f-4048-a8d3-79784f66168e)

**Comment by meteorcloudy** [comment]
https://buildkite.com/organizations/bazel/analytics has just been available, those tests will probably show up on the dashboard.

**Comment by meteorcloudy** [comment]
I'm closing this one since all flaky tests are tracked by https://github.com/bazelbuild/bazel/issues?q=is%3Aopen+is%3Aissue+label%3A%22flaky+test%22 and gTech team is helping reporting new flaky tests based on https://buildkite.com/organizations/bazel/analytics .
