### ISSUE TITLE
Verify that the Windows VM instructions are clear and correct

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#166]
Hi @meteorcloudy and @laszlocsomor,

could you please check if my new documentation on how to create a Windows VM image for our Jenkins slaves looks good to you and is easy to understand?

It's here: https://github.com/bazelbuild/continuous-integration/blob/master/docs/windows-slave-image.md

Thanks :)
Philipp

**Comment by laszlocsomor** [comment]
Thanks for having written this doc! LGTM overall, but I have a few comments:

> ## Necessary steps
Is this an ordered list of steps

> - Server Manager -> Configure this local server
>   - Deactivate Windows Firewall.
>   - Deactivate Windows Defender.
>   - Deactivate IE Enhanced Security Configuration.
>   - (...)

Can you add a comment saying why these steps are necessary? Disabling these systems without good reason seems like a bad idea.

> - Go to https://www.python.org/downloads/windows/
>   - Download latest stable Python 3.x (64-Bit).
>   - Start installation.
>     - (...)
>     - Customize installation, check all boxes.

The installation process may change with future versions. I don't ask for any change here, but keep this in mind next time and either describe in broad terms what those checkboxes are, or attach a screenshot.

> - Go to http://www.msys2.org/
>   - Download latest x86_64 msys2 setup.
>   - Install to C:\msys64.

I reinstalled by Windows machine a couple of months ago and noticed that something (sadly I can't remember what exactly it was) still requires `c:\tools\msys64`.
As a remedy I simply created a junction `c:\tools\msys64` -> `c:\msys64`. I recommend adding this step to the doc:

```
md c:\tools
mklink /j c:\tools\msys64 c:\msys64
```

**Comment by laszlocsomor** [comment]
One more thing: please list all packages installed to msys2, with their versions.
I just ran into a problem with kokoro that "tar" didn't seem to be installed, and it was very helpful to cross-check the docs that it's indeed not.

**Comment by philwo** [comment]
Laszlo, do you mean *all* installed packages, even indirect dependencies? I think that won't help too much, because the list is out of our control and the docs will become out of date quickly, so you can't rely on them.

I would say, unless a package is listed as explicitly installed in the "Run "pacman -S ..." line, it's safer to assume that it's not installed, WDYT?

**Comment by laszlocsomor** [comment]
> I would say, unless a package is listed as explicitly installed in the "Run "pacman -S ..." line, it's safer to assume that it's not installed, WDYT?

Yes, SGTM.
