### ISSUE TITLE
CI status badges are broken

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/continuous-integration#167]
When we switched CI hosting from ci.bazel.io to ci.bazel.build (yay!) the status badges on the READMEs of various GH repos broke. Examples:

https://github.com/bazelbuild/bazel
https://github.com/bazelbuild/BUILD_file_generator
(etc.)

**Comment by philwo** [comment]
I think I got one of the rewrite rules wrong regarding the query string, which results in a 404 error:

https://ci.bazel.io/buildStatus/icon?job=bazel-tests
goes to
https://ci.bazel.build/buildStatus/icon?job=bazel-tests?job=bazel-tests

but should obviously go to:
https://ci.bazel.build/buildStatus/icon?job=bazel-tests

Will fix it tomorrow.

**Comment by philwo** [comment]
This is fixed now:

```bash
$ curl -i http://bazel.io/test?test=test
Location: https://bazel.build/test?test=test

$ curl -i https://ci.bazel.io/buildStatus/icon?job=bazel-tests
Location: https://ci.bazel.build/buildStatus/icon?job=bazel-tests
```
