### ISSUE TITLE
Request to add new project [rules_qt]

### ISSUE THREAD

**Issue by jheaff1** [bazelbuild/continuous-integration#1699]
https://github.com/jheaff1/rules_qt

Thank you for your interest in adding your project to Bazel CI.

At the moment we're operating at capacity and cannot add new projects except for projects maintained under the bazelbuild GitHub organization and for rules. To request a review for being added to Bazel CI, please follow the instructions below.

- [ ] My project is part of the bazelbuild GitHub organization.
- [x] My project is a rules set of a GitHub organization other than bazelbuild.
- [ ] I want to test the following project on Bazel CI: [URL_TO_GIT_HUB_PROJECT]
- [x] I confirm that the project has a `.bazelci/presubmit.yml` file.

# Instructions (you can delete this section from the issue)

Welcome to Bazel CI! We are thrilled that you want to test your project with Bazel.
Please follow these steps to make the on-boarding experience as smooth as possible:

1. Add the URL of your project's GitHub repository to the first line of this issue.
2. Add the name of your project to the issue title.
3. Please read the [introduction to Buildkite](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md) to learn about the basic concepts such as pipelines.
4. Create and commit your presubmit configuration in `<YOUR REPO>/.bazelci/presubmit.yml`. The configuration format is documented [here](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#configuring-a-pipeline), and you can find several an example [here](https://github.com/bazelbuild/rules_typescript/blob/master/.bazelci/presubmit.yml). No need to get it right on the first try - It's usually a good idea to start with a basic configuration, wait until the pipeline is set up, trigger a build and then iterate on the configuration.
5. The Bazel team will review this issue and create a pipeline on Buildkite.
6. The team will reach out to you and give you instructions on how to set up a GitHub webhook that triggers a CI build for incoming pull requests.

**Comment by meteorcloudy** [comment]
We already have rules_qt for https://github.com/justbuchanan/bazel_rules_qt, is this related?

**Comment by jheaff1** [comment]
Those rules only support Qt5 and do not build Qt from source, instead they require Qt to be installed on the build host.

if @justbuchanan is open to the idea of my submitting PRs to support Qt6 and to build from source, then I wouldn’t need my own ruleset

**Comment by justbuchanan** [comment]
Hi @jheaff1, I'd be open to accepging PRs for Qt6 and build-from-source support. Building from source has been on my todo list, but it's been a while since I last looked into it. Do you have this working yet? And do you know how difficult it would be to have the rules support both Qt5 and Qt6? I'm not opposed to dropping Qt5 support, but if possible, it would be nice to support both.

**Comment by jheaff1** [comment]
@justbuchanan I have successfully built Qt6 in Bazel for windows, Linux and android, I need to tidy up my work though.

At some point I could submit a PR to your repo to add Qt6 support (not building from source), then later add a PR to build from source?

**Comment by jheaff1** [comment]
I’ll close this issue as I’ll contribute to @justbuchanan’s rules instead
