### ISSUE TITLE
bk-imacpro-11 started failing KMS commands

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1701]
Latest example: https://buildkite.com/bazel/bazel-bazel/builds/23792#0188e316-706b-4e7f-8814-30a41b6e9051

Apparently something messed with the gcloud config on this machine. Yun tried to fix it, but without any success.

**Comment by fweikert** [comment]
Latest example: https://buildkite.com/bazel/bazel-bazel/builds/24067#01894a4b-def7-488c-8735-0e4073091481

I re-ran the gcloud specific setup instructions on this machine. We'll see if it has solved the problem.

**Comment by meteorcloudy** [comment]
This is no longer happening recently.
