### ISSUE TITLE
Nix Support (rules_rust)

### ISSUE THREAD

**Issue by rickvanprim** [bazelbuild/continuous-integration#1703]
Would it be acceptable to add Nix to the BuildKite Agent used by `rules_rust`?  @UebelAndre has expressed some interest in having an example using Nix, which is currently blocked on needing `nix`.  Unfortunately Nix is a bit more complex to get working in a container than just running their installer script and isn't available via the Debian/Ubuntu package manager (that I'm aware of).  It looks like the way to add it to the image would be to mimic what the official Nix Docker image does, see https://hub.docker.com/r/nixos/nix/dockerfile.  If that's amenable, I'll work on opening a PR to add Nix support based on that.

**Comment by UebelAndre** [comment]
@meteorcloudy I think @rickvanprim has a dockerfile that would work for CI. Is there some guidance on what to do add a new type of agent to Bazel CI so we can use it in `rules_rust`?

**Comment by UebelAndre** [comment]
@meteorcloudy I don't feel Github Actions are an option due to the lack of a remote cache. `rules_rust` doesn't produce a ton of data but compiling everything in the repo can be quite time consuming and expensive. Being able to add a new "Linux Platform" would be amazing.

**Comment by meteorcloudy** [comment]
OK, I'm open to accept a PR to add this platform for rules_rust, but we'll have to reply on the community to maintain it.

Please check https://github.com/bazelbuild/continuous-integration/tree/master/buildkite/docker on how it's done for other platforms.
