### ISSUE TITLE
Getting pipeline access

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/continuous-integration#1723]
Hi wonderful Bazelers,

Could I get access to the pipeline to be able to test downstream projects? (I'm following your instructions [here](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md#testing-local-changes-with-all-downstream-projects) and am hoping to use it to test PRs and make their merging smoother.) Personal email is christophersauer@pacbell.net

While we're at it, what's the status of bazelci availability for public-use tooling and essential library rules? (Please don't let this question block the above--just if it's in your mental cache.) I was thinking it's be nice to get our (fairly popular) [bazel-compile-commands-extractor](https://github.com/hedronvision/bazel-compile-commands-extractor) tool added for future setup, as well as rules for a few essential libraries: [bazel-make-cc-https-easy](https://github.com/hedronvision/bazel-make-cc-https-easy) and [bazel-cc-filesystem-backport](https://github.com/hedronvision/bazel-cc-filesystem-backport). I know we already have it over at rules_boost (which I'm a collaborator on) and it's quite valuable there.
 
Thanks so much for all you do,
Chris
(ex-Googler)

**Comment by meteorcloudy** [comment]
@cpsauer Sorry, the downstream pipeline takes a lot of resources and will even block presubmits for Bazel developers, therefore only a small number of people have access.

**Comment by cpsauer** [comment]
I'm sure! It's great that you guys run it at all. Thanks for your reply, Yun.
Might it be worth updating the docs/issue template if downstream testing (and ci for public rules) is no longer the recommendation?

Cheers,
Chris

**Comment by meteorcloudy** [comment]
@cpsauer For core Bazel developers, the documentation is still valid, sorry for the conflicting messages. I'll change the wording there.

Using the downstream pipeline to test your change is still valuable, do you have a specific PR you want to test, I can help initiating a downstream test.

**Comment by cpsauer** [comment]
No problem at all--thanks again, Yun, for all you do. (Just don't want others to similarly waste your time!)

I've already been helped on the PR that kicked this off, but thanks so much for offering and being great :) More meant it so I could help streamline and use less of your time in the future.
