### ISSUE TITLE
Bazel Dashboard - several issues with rules_repos

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1732]
- missing rules_cc, rules_android, rules_python
- possibly also add rules_rust
- sorting (I’d wish rules_repos are together, right now rules_pkg is before bazel and rules_java after), 
- a lot of rules_* don’t have categories:  "untriaged", (or at least "no priority"), "need more information", "need review"
- owner changes: 
  - rules_java->hvd, 
  - rules_cc->gnish, 
  - stardoc->arostovtsev
  - rules_python -> rlevasseur

**Comment by meteorcloudy** [comment]
https://dashboard.bazel.build/ 
@coeuvre Can you take a look?

**Comment by coeuvre** [comment]
Sure, I will take a look.

**Comment by coeuvre** [comment]
> * missing rules_cc, rules_android, rules_python
> * possibly also add rules_rust
> * sorting (I’d wish rules_repos are together, right now rules_pkg is before bazel and rules_java after),
> * a lot of rules_* don’t have categories:  "untriaged", (or at least "no priority"), "need more information", "need review"
> * owner changes:
>   
>   * rules_java->hvd,
>   * rules_cc->gnish,
>   * stardoc->arostovtsev
>   * rules_python -> rlevasseur

Done. May need a few hours for new repos to sync data.

I am now looking into email issues.

**Comment by comius** [comment]
I did some more triaging yesterday and caused another problem:
If you open Rules-API team, Untriaged. Dashboard shows 9 issues. Following the link, there are 0.

**Comment by coeuvre** [comment]
The sync process stuck at Sep 22. I didn't set the timeout for the HTTP request and the request never returned because of the Github incident on that day. So the entire sync process stopped.

I just restarted the server so everything will catch up. I will add a timeout to outgoing requests.
