### ISSUE TITLE
Infra issue with rules_haskell in BazelCI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1737]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3308#018a9699-9c57-47be-a3ce-e91889fe28d3

Platform : Ubuntu

Logs:
```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-39vb/bazel-downstream-projects/rules_haskell/WORKSPACE:51:13: //external:rules_haskell_sh_posix_nixpkgs: no such attribute 'exec_constraints' in '_nixpkgs_package' rule
ERROR: error loading package '': Encountered error while reading extension file 'os_info.bzl': no such package '@os_info//': error loading package 'external': Could not load //external package
Traceback (most recent call last):
  File "bazelci.py", line 4010, in <module>
    sys.exit(main())
  File "bazelci.py", line 3990, in main
    bazel_version=task_config.get("bazel") or configs.get("bazel"),
  File "bazelci.py", line 1366, in execute_commands
    bazel_version = print_bazel_version_info(bazel_binary, platform)
  File "bazelci.py", line 1659, in print_bazel_version_info
    [bazel_binary] + common_startup_flags() + ["--nosystem_rc", "--nohome_rc", "info"]
  File "bazelci.py", line 2667, in execute_command
    else None,  # capture_stderr=True when we want exceptions to contain stderr
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--nosystem_rc', '--nohome_rc', 'info']' returned non-zero exit status 2.
🚨 Error: The command exited with status 1
```

CC Greenteam @meteorcloudy

**Comment by Wyverald** [comment]
The last green commit of rules_haskell (https://github.com/tweag/rules_haskell/commit/f801bba2773ae2fde30e0da2138f6ac0f2c2a910) on Bazel 6.3.2 is from 3 months ago.

HEAD rules_haskell with Bazel 6.3.2 fails with a `find_cc_toolchain` error. Filed https://github.com/tweag/rules_haskell/issues/1963

last_green rules_haskell with HEAD Bazel fails with the error above. `bazelisk --bisect` points to https://github.com/bazelbuild/bazel/commit/4686e2550f76189cb1cfbe0852feb3337f38139c, which suggests that the error was within rules_haskell all along. Filed https://github.com/tweag/rules_nixpkgs/issues/416

**Comment by meteorcloudy** [comment]
Thanks for investigating and filing issues, since this is not an actual CI infra issue, let's close this one.

**Comment by meteorcloudy** [comment]
@sgowroji Please update the tracking list accordingly, thanks!
