### ISSUE TITLE
Replay job (sometimes) runs with a different Upstream project 

### ISSUE THREAD

**Issue by iirina** [bazelbuild/continuous-integration#174]
One practical example involving release candidates:

- I create and push an RC which triggers a release job on the CI. 
- The release job will start multiple jobs to test all other projects
- The release job is the Upstream for the other jobs that were started.
- I go home and at midnight the nightly gets build and starts other downstream jobs.
- One of the jobs started by the release fails and is probably flaky. I want to rerun and deflake it. 
- I hit replay.
- The new replay job is using the nightly as the Upstream project instead of the release, because the nightly is the most recent Upstream project that was built.

To deflake the failed jobs I have to re-run the whole release job. That is bad because it re-runs every project, although most of them were green, and send yet another email announcing the new RC.

The code that computes the Upstream project is [here](https://github.com/bazelbuild/continuous-integration/blob/c43fa8b1fc10379b5acff167c7d38b4c11f8f2e5/jenkins/lib/src/build/bazel/ci/JenkinsUtils.groovy#L168).

**Comment by philwo** [comment]
We'll make sure that this is fixed in the new CI.

**Comment by philwo** [comment]
Fixed on the new CI.
