### ISSUE TITLE
Release notes contain garbage characters

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1764]
Example: `Ã¢â‚¬â€œ` in https://releases.bazel.build/6.3.0/rc1/index.html

Looks like an encoding issue affecting apostrophes and hyphens.

We generate the release notes in Markdown, then convert them to HTML:

https://github.com/bazelbuild/bazel/blob/master/scripts/ci/build.sh#L178

**Comment by tjgq** [comment]
@coeuvre and I tried to repro this by running the same steps as the pipeline (including publishing to GCP) in the same docker image, and couldn't repro the issue. Some things we found along the way:

- While investigating this, don't trust the browser to display the file correctly; even a correctly encoded UTF-8 file might be incorrectly autodetected as Latin1 by the browser if it's missing an explicit encoding in the HTTP headers or in a `<meta>` tag. Always download the file (e.g. using `curl`) and inspect it with a hex editor.

- The majority of mangled characters are emdashes and smart quotes; we've determined that these are *not* in the commit messages; they're inserted by `pandoc` when the Markdown input contains a `--` or `"` (except inside backquotes).

- `pandoc` is documented as expecting both its input and output to be UTF-8, and this seems to be experimentally true. We're not sure whether `git` will attempt to do encoding conversions on commit messages (based on the locale environment variables?), but the fact that the emdashes and smart quotes are present is a strong signal that the mangling occurs after `pandoc`, not before. But the only thing after `pandoc` is `gsutil`, and we've experimentally determined that it doesn't transcode files.

- If you look closely at how the emdashes and smart quotes got mangled, you'll notice that they're double-encoded: they're the result of taking correctly encoded UTF-8 text, incorrectly decoding it as Latin1, then reencoding it in UTF-8. For example, an emdash (`U+2014`) is encoded UTF-8 as `e2 80 94`, which decodes as Latin1 into `â€“`, which is reencoded in UTF-8 as `c3 a2 a2 82 ac e2 80 9c`.

- This sort of mangling is consistent with opening the file in an editor that assumes Latin1 encoding and saving it again in UTF-8. It would help to understand whether the file currently at https://releases.bazel.build/6.3.0/rc1/index.html really did come straight from the pipeline, or whether a manual edit was made. @keertk mentioned in chat that she added a line at the top and re-uploaded the file, so it would help understand how the edit was made. I'd also suggest running the pipeline to double-check whether the file it uploads is already mangled (using `curl url | hexdump -C`, not trusting the browser).

**Comment by tjgq** [comment]
(Regardless of the outcome of the investigation, I think we should amend the `gsutil` invocation in the pipeline to set the content type of the uploaded file to `text/html;charset=utf-8`, so that it's not at the mercy of browser autodetection; but we shouldn't do so until we've actually understood what happened.)

**Comment by fweikert** [comment]
This issue is also affecting the release notes of rolling releases, which have never been opened/edited by a human.

**Comment by tjgq** [comment]
> This issue is also affecting the release notes of rolling releases, which have never been opened/edited by a human.

Discussed offline: the ones for rolling releases are valid UTF-8 (at least the ones I checked). The only issue there is the browser incorrectly sniffing the encoding, which can be fixed by setting the content type on upload.

**Comment by meteorcloudy** [comment]
This is now fixed with https://releases.bazel.build/7.0.0/rc3/index.html
