### ISSUE TITLE
Install Xcode 15 on all Mac machines

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#1780]
We should make sure the latest Xcode version is available on Bazel CI.

Related: https://github.com/bazelbuild/bazel-central-registry/pull/1119#issuecomment-1806531990

**Comment by fweikert** [comment]
Please note that Xcode 15 requires 13.5 or later, which means we have to upgrade all CI workers. I don't expect major problems on the iMacs since they run 13.2, but all other machines are on either 12.5 or 12.6.

**Comment by meteorcloudy** [comment]
Oh.. thanks for the notice, then this is more complicated than I thought..

**Comment by BalestraPatrick** [comment]
Xcode 15.1 was released this week, so it would be nice to have it given that rules_apple supports the new Apple Vision Pro but we can’t run tests for it on CI until we have Xcode 15.1 available.

**Comment by meteorcloudy** [comment]
Apple Silicon machines are now upgraded to 13.6.3 and Xcode 15.1 is now installed on all Apple Silicon machines!

We cannot install Xcode15.1 on Intel machines because the OS update is blocked due to some network problem (apparently you cannot update macOS with ipv6 only network).

**Comment by meteorcloudy** [comment]
Let me know if some SDK is still missing for visionOS.

**Comment by BalestraPatrick** [comment]
Thanks a lot @meteorcloudy! We'll try to move our builds to Xcode 15.1 and see how it goes.

**Comment by BalestraPatrick** [comment]
@meteorcloudy Are you sure that Xcode 15.1 is installed on all agents? I'm seeing 15.0 correctly, but setting 15.1 makes it fallback to 14.2 on a couple of machines I tried (`bk-macstudio-8`, `bk-macstudio-7`) at least: https://buildkite.com/bazel/rules-apple-darwin/builds/8696#018cceaa-cb2a-4222-9d4b-8015bf6d6919

**Comment by meteorcloudy** [comment]
Ah, sorry, apparently I messed up with the name, it should be /Applications/Xcode15.1.app instead of /Applications/Xcode15.0.app. Fixing it now.

**Comment by meteorcloudy** [comment]
Should be fixed now

**Comment by BalestraPatrick** [comment]
Works now, thank you!

**Comment by meteorcloudy** [comment]
Sure, I can do that. But do you think we still need Xcode 15 on Intel Macs?

**Comment by meteorcloudy** [comment]
Looks like you are no longer testing on Intel Macs?

**Comment by meteorcloudy** [comment]
I have installed Xcode15.2 and visionOS runtime on all Mac Studio machines
```
ci@bk-macstudio-4 ~ % xcrun simctl list runtimes available
2024-01-25 14:32:29.793 simctl[35804:6141170] CoreSimulator detected version change.  Framework version (944.5) does not match existing job version (944.4).  Attempting to remove the stale service in order to add the expected version.
== Runtimes ==
iOS 17.2 (17.2 - 21C62) - com.apple.CoreSimulator.SimRuntime.iOS-17-2
tvOS 17.2 (17.2 - 21K364) - com.apple.CoreSimulator.SimRuntime.tvOS-17-2
watchOS 10.2 (10.2 - 21S364) - com.apple.CoreSimulator.SimRuntime.watchOS-10-2
visionOS 1.0 (1.0 - 21N305) - com.apple.CoreSimulator.SimRuntime.xrOS-1-0
```

**Comment by BalestraPatrick** [comment]
That's correct. At least rules_apple, rules_swift and apple_support only build on Apple Silicon as far as I can see.

**Comment by meteorcloudy** [comment]
Good, then there is no hurry to update the OS for iMac Pros. 

Please confirm if Xcode15.2 is working for you, if so, we can probably close this one finally.

**Comment by fweikert** [comment]
@BalestraPatrick is 15.2 enough or do you still need 15.1, too?

**Comment by meteorcloudy** [comment]
I think 15.2 should be enough

**Comment by BalestraPatrick** [comment]
@meteorcloudy Feel free to close this issue, I don't have the rights to do it.

**Comment by meteorcloudy** [comment]
Thanks!
