### ISSUE TITLE
gerrit tests failing with Bazel release 0.11.0rc3

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#179]
https://ci.bazel.build/blue/organizations/jenkins/Global%2Fgerrit/detail/gerrit/415/pipeline/

Platforms:
- darwin-x86_64

Looks like it's trying to use python2 but there's no binary with that name.

**Comment by katre** [comment]
Blocking release https://github.com/bazelbuild/bazel/issues/3959

**Comment by katre** [comment]
Gerrit seems to expect both python2 and node, I can't test this locally.

**Comment by philwo** [comment]
I have added a `python2` symlink on the Mac Pros, so this should be fixed.
