### ISSUE TITLE
Add rules_kotlin to the CI pipeline.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/continuous-integration#180]
rule_location: https://github.com/bazelbuild/rules_kotlin
supported platforms: Ubuntu 16.04, macOS, FreeBSD.
testing: `bazel test //:all_tests`

---

The tests currently use the external testing strategy, they are executed via the python unittests framework.  The test cases are basically just "bazel build" and "bazel run" invocations with follow up assertions on the outputs. The outputs are picked up from "bazel-out/" and "bazel-bin/".

I understand the new CI system might not support shell commands as test targets, awaiting feedback on this.

**Comment by davidstanke** [comment]
@philwo for input on shell commands as test targets

**Comment by philwo** [comment]
Is there a way you can run these tests via "bazel test"? Maybe via https://docs.bazel.build/versions/master/be/python.html#py_test?

Currently we don't support running arbitrary commands as tests on the CI, because it has a number of disadvantages: We don't get target-level logs of test failures, we can't use our test results UI to show the results, it's harder to support Windows, because we don't want to run bash scripts there.

**Comment by hsyed** [comment]
I want to do exactly that, the problem is I need to run Bazel within Bazel as most of my tests are E2E tests covering skylark and the persistent worker. The bazel single process lock prevents this. 

I am assuming (hoping) there are E2E tests that run Bazel within Bazel like this. If I could get a reference to some tests like this I can adapt the setup and wire the tests up as py_tests. 

[bazelbuild/bazel-integration-testing](`https://github.com/bazelbuild/bazel-integration-testing`) is an approach that can handle this but the turn around times are slow, it has to download deps, unpack bazel and rebuild the workspace on each run.

**Comment by hsyed** [comment]
I have thought about it a bit and I can restructure the tests to collect all test case build artifacts via a file group and then have a single test target perform all the assertions.

Ill have to remove the negative test cases, but they are not that valuable.

Will the failure of build artifacts (transitively via the filegroup) still result in sensible error logs in the CI dashboard ?

**Comment by hsyed** [comment]
@philwo I've reworked the tests as per my previous comment. `bazel test //:all_tests` should be all that is needed.

**Comment by philwo** [comment]
Thank you, @hsyed! This is great. We'll make sure to get the project on CI asap.

**Comment by buchgr** [comment]
I added `rules_kotlin` to our new CI system [1]. Seems to work just fine!

<img width="1158" alt="screen shot 2018-02-22 at 7 34 24 pm" src="https://user-images.githubusercontent.com/1388179/36557047-70d89c66-1807-11e8-9669-6ac009ccbd8d.png">

@hsyed can we enable pull request testing on `rules_kotlin` to test our new CI system? Would you be interested in that?

[1] https://github.com/bazelbuild/continuous-integration/commit/91e6190f2faa6d6b250cc6c20d93f33d722d8e2d

**Comment by buchgr** [comment]
It will be on our new CI, so this can be closed.

**Comment by hsyed** [comment]
very much so. do I need to do anything for that ?

**Comment by buchgr** [comment]
https://github.com/bazelbuild/rules_kotlin/pull/28 :-)

**Comment by buchgr** [comment]
@hsyed I have sent you an invite to our CI to your gmail address.

**Comment by hsyed** [comment]
I need to sort out windows bugs (path generation problems), I don't have a windows machine. If I update the config in a windows PR will it build on each commit using the config from the PR branch ?

**Comment by buchgr** [comment]
@hsyed not yet. I ll ping you once we have windows working.

**Comment by buchgr** [comment]
Also, I ll set up pull request triggering tomorrow.

**Comment by hsyed** [comment]
Many thanks !
