### ISSUE TITLE
bazel-central-registry should run bazel tests in the repo

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/continuous-integration#1813]
There's already some test targets in bcr, e.g. https://github.com/bazelbuild/bazel-central-registry/blob/main/tools/BUILD#L68
I would like to add more, but I believe these are not being tested on buildkite currently.

FYI @meteorcloudy this is probably easy for you

**Comment by meteorcloudy** [comment]
Can you please create a `.bazelci/presubmit.yml` file just like other normal repo? I can help set up the pipeline when it's available.

**Comment by alexeagle** [comment]
Sure, https://github.com/bazelbuild/bazel-central-registry/pull/1151

**Comment by meteorcloudy** [comment]
This is done: https://buildkite.com/bazel/bazel-central-registry
