### ISSUE TITLE
 bazel test on Ubuntu 14.04 fails with Permission denied

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#182]
```
ERROR: /var/lib/buildkite-agent/builds/buildkite-ubuntu1404-rl9x/bazel/bazel-postsubmit/scripts/packages/BUILD:57:2: Executing genrule //scripts/packages:zip-bazel-exe_with_jdk failed (Exit 1)
  | touch: cannot touch '/tmp/tmp.SrDiMx4k/bazel.exe': Permission denied
```

bazel test on Ubuntu 14.04 fails: https://buildkite.com/bazel/bazel-postsubmit/builds/7#62e14d4f-b852-49ab-b196-d70f9cfe77d4

Is this a sandboxing error?

**Comment by buchgr** [comment]
@philwo

**Comment by philwo** [comment]
Nope, we need to use "--build_tests_only" when running "bazel test" as otherwise Bazel will try to build targets as part of the "bazel test //scripts/..." part that can't run on the platform (like the one mentioned above).

**Comment by buchgr** [comment]
thanks. fixed
