### ISSUE TITLE
Centos images default to python 2

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#1823]
In https://github.com/bazelbuild/bazel/issues/18776, Android tests are failing because they're using python 2 instead of python 3.

This is because the centos image has python3 installed, but it's not the default:
```
$ docker run -it gcr.io/bazel-public/centos7-java11-devtoolset10:latest bash
Unable to find image 'gcr.io/bazel-public/centos7-java11-devtoolset10:latest' locally
latest: Pulling from bazel-public/centos7-java11-devtoolset10
Digest: sha256:f335a5d84d385e95bd736abdfb2115fe368a7bd7993da15f833cdec6541edf5f
Status: Downloaded newer image for gcr.io/bazel-public/centos7-java11-devtoolset10:latest
[root@2c7017cf9f55 /]# which python
/usr/bin/python
[root@2c7017cf9f55 /]# python --version
Python 2.7.5
```

For debian-based containers, we install `python-is-python3` to fix this.

**Comment by katre** [comment]
Okay, due to syntax of Dockerfile, this only changed centos7-releaser. Going to try again, can this be re-opened?

**Comment by katre** [comment]
Actually, this is infeasible, and I'm backing out the change. If I look into this the fix will have to be in the tests.

**Comment by meteorcloudy** [comment]
OK, I have reverted the `latest` tag for all relevant container images to the previous version.
