### ISSUE TITLE
Request to add new project rules_platform

### ISSUE THREAD

**Issue by aranguyen** [bazelbuild/continuous-integration#1852]
Project url: https://github.com/bazelbuild/rules_platform
Thank you for your interest in adding your project to Bazel CI.

At the moment we're operating at capacity and cannot add new projects except for projects maintained under the bazelbuild GitHub organization and for rules. To request a review for being added to Bazel CI, please follow the instructions below.

- [x] My project is part of the bazelbuild GitHub organization.
- [x] I want to test the following project on Bazel CI: [rules_platform](https://github.com/bazelbuild/rules_platform)
- [x] I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by meteorcloudy** [comment]
As soon as the pipeline is green, I can add this one to the downstream pipeline.

**Comment by meteorcloudy** [comment]
Any update on this one?

**Comment by aranguyen** [comment]
@meteorcloudy I'm waiting for the last approval for this PR and will merge with it. It has the `.yml` file https://github.com/bazelbuild/rules_platform/pull/1

**Comment by aranguyen** [comment]
It's just merged!

**Comment by meteorcloudy** [comment]
Thanks! Adding it to the downstream pipeline in https://github.com/bazelbuild/continuous-integration/pull/1879
