### ISSUE TITLE
Run a test where we build bazel with clang

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#186]
(Suggested by @mhlopko)

In order to make sure that Bazel can build C++ code with clang, let's setup a test where we build Bazel with clang. Apparently the only thing we have to do for that is to install clang and then run `export CC=/usr/bin/clang` before calling Bazel.

**Comment by mhlopko** [comment]
\o/

**Comment by philwo** [comment]
@hlopko I guess this is still useful, right? If yes, I can set this up tomorrow. :)

**Comment by hlopko** [comment]
That is indeed super useful!! We'll need to set `CC` environment variable to the location of the clang for Bazel to use it.

Thanks!

**Comment by philwo** [comment]
Done: https://github.com/bazelbuild/bazel/pull/8493
