### ISSUE TITLE
rules_apple is not being tested

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#189]
https://ci.bazel.build/job/rules_apple/21/console

it doesn't do anything. we should probably test it on buildkite?

**Comment by sergiocampama** [comment]
FYI we've been using travis for the past few weeks: https://travis-ci.org/bazelbuild/rules_apple

**Comment by thomasvl** [comment]
You can probably call this fixed since we now have it up and going now (pending our failures).

**Comment by philwo** [comment]
Closing as fixed, because rules_apple is being tested on the new CI.
