### ISSUE TITLE
set up staging Jenkins instance at ci-staging.bazel.io

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#19]

**Comment by laszlocsomor** [comment]
Done, http://ci-staging.bazel.io is accepting HTTP traffic from Google-internal IPs.
I'll update the documentation with all the steps I took to get here.

**Comment by damienmg** [comment]
It is operational, now just automatizing and updating the documentation

**Comment by damienmg** [comment]
Automation is done, now only updating the documentation is left.

**Comment by damienmg** [comment]
And this is finished!
