### ISSUE TITLE
Missing iOS simulator runtimes in CI

### ISSUE THREAD

**Issue by luispadron** [bazelbuild/continuous-integration#1957]
The following PR https://github.com/bazelbuild/bazel-central-registry/pull/2009 is failing because some simulator runtimes are missing. These were previously available and the job built fine. 

There was an Apple runtime issue which has been resolved but likely put the machines in a bad state, could we look at getting the runtimes re-installed. 

```
error: iOS 17.2 Platform Not Installed.
```

**Comment by meteorcloudy** [comment]
Only Apple Silicon machines matter right?

**Comment by meteorcloudy** [comment]
Running `sudo xcodebuild -downloadAllPlatforms` on all apple silicon machines. 

This is weird, I'm not sure how those runtime disappeared in the first place.

**Comment by luispadron** [comment]
From what I understood, around May 1st, Apple rolled out an XProtect update which caused the runtimes to be unmounted/uninstalled. That update was rolled back on May 2nd but requires re-downloading/setting up the runtimes

**Comment by meteorcloudy** [comment]
Okay, that might be it. We'll soon move to a new fleet of Mac VMs for Bazel CI and hopefully won't have this issue again.

**Comment by luispadron** [comment]
@meteorcloudy Was this ready? Still seeing the same issue on some new PRs: https://github.com/bazelbuild/rules_apple/pull/2461

**Comment by meteorcloudy** [comment]
Hmm, maybe our macOS version is too old (13.6.3), I'll update them to 14.5 today.

**Comment by meteorcloudy** [comment]
I've upgraded macstudio{1..5, 7} to macOS 14.5 and installed Xcode 15.4 and all SDKs on {2,3,5}. I've lost remote access to the machines for now, will continue to do the rest of the update next week. Sorry for the delay.

**Comment by meteorcloudy** [comment]
I've upgraded all macstudios to 14.5 and installed Xcode 15.4 and all runtimes. Can you please update `xcode_version` in https://github.com/bazelbuild/rules_apple/blob/0b31b87fc8a8a71e847bebc648af0e084b24d2ee/.bazelci/presubmit.yml#L7 to test if it works?

**Comment by BalestraPatrick** [comment]
Thanks @meteorcloudy! Looks Xcode 15.2 is also working correctly for us, but I'll proceed with trying to upgrade to Xcode 15.4.

**Comment by meteorcloudy** [comment]
Indeed, all builds are now green also with xcode15.2: https://buildkite.com/bazel/rules-apple-darwin/builds/9183#_
