### ISSUE TITLE
Gerrit fails due to missing npm package on all platforms.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#196]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ which npm
+ npm_bin=/usr/bin/npm
+ [ -z /usr/bin/npm ]
+ which node
+ node_bin=/usr/bin/node
+ [ -z /usr/bin/node ]
+ npm list -g
+ grep -c fried-twinkie
npm ERR! invalid: minizlib@1.0.3 /usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib
+ fried_twinkie_config=0
```

https://buildkite.com/bazel/gerrit/builds/14#e53a4ba7-cacd-4dc4-8767-9892a582d682

**Comment by philwo** [comment]
This is still failing after installing the required packages: https://buildkite.com/bazel/gerrit/builds/15

There are these error messages in the log:
```
+ grep -c fried-twinkie
+ npm list -g
npm ERR! peer dep missing: typescript@2.3.4, required by tsickle@0.23.6
npm ERR! invalid: minizlib@1.0.3 /usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib
+ fried_twinkie_config=1
+ npm list -g
+ grep -c typescript
npm ERR! peer dep missing: typescript@2.3.4, required by tsickle@0.23.6
npm ERR! invalid: minizlib@1.0.3 /usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib
+ typescript_config=1
```
(see https://storage.googleapis.com/bazel-buildkite-artifacts/9369eecc-8220-494d-8757-045e7226a443/tmp/tmpamwbuexn/polygerrit-ui/app/template_test_edit.log)

But the test seems to continue fine, so I'm not sure if they're actually important. The last (failing) step then doesn't print any error, though:

```
+ /usr/bin/node /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/582672bc1a1cee8a93b225c1664fa943/execroot/gerrit/bazel-out/k8-fastbuild/bin/polygerrit-ui/app/template_test_edit.runfiles/gerrit/polygerrit-ui/app/template_test_srcs/template_test.js edit
```

I'd suggest to ask the Gerrit team what's up with this.

**Comment by philwo** [comment]
Found the problem: Gerrit is only compatible with fried-twinkie@0.0.15. (Whatever that is.) Newer versions don't work.

Now it's green on Linux. :) Will fix the missing `python2` link tomorrow.
