### ISSUE TITLE
[Bazel CI] Gerrit Error: 'fedora40',pipeline parsing of "(stdin)" with Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1960]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3890#018fc7d7-1587-4d69-8e90-0b56885703a7

Platform: Ubuntu

 Logs: 
```
Traceback (most recent call last):
  File "bazelci.py", line 4461, in <module>
    sys.exit(main())
  File "bazelci.py", line 4400, in main
    print_shard_summary=args.print_shard_summary,
  File "bazelci.py", line 2932, in print_project_pipeline
    soft_fail=soft_fail,
  File "bazelci.py", line 3169, in runner_step
    command = PLATFORMS[platform]["python"] + " bazelci.py runner --task=" + task
KeyError: 'fedora40'
fatal: pipeline parsing of "(stdin)" failed: EOF
``` 

 CC Greenteam @comius

**Comment by sgowroji** [comment]
CC @davido

**Comment by davido** [comment]
This is related to this change: https://github.com/bazelbuild/continuous-integration/pull/1959

@meteorcloudy @sgowroji Any idea, what is missing here, so that new docker image is fetched and used by Bazel CI?

**Comment by meteorcloudy** [comment]
Oh, looks like we forgot to add the platform at https://github.com/bazelbuild/continuous-integration/blob/e102c9f9d384243dbb80bfd5857f8b6f6c4f1bbc/buildkite/bazelci.py#L502-L507

**Comment by davido** [comment]
@meteorcloudy Thanks for the pointer, will send PR in a moment.

**Comment by davido** [comment]
@sgowroji @meteorcloudy 

Could you please review: https://github.com/bazelbuild/continuous-integration/pull/1966 ?
