### ISSUE TITLE
Add NDK 25b to Windows BazelCI

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/continuous-integration#1962]
To support tests for rules_android_ndk on Windows, we need an updated version of the NDK. Version 25b is on linux:
https://github.com/bazelbuild/continuous-integration/blob/fcd3cdd216acf5b78449ae6c05da1c789f5ef76c/buildkite/setup-docker.sh#L166-L175

So we should add Windows 25b to match. The URL is:
https://dl.google.com/android/repository/android-ndk-r25b-windows.zip

https://github.com/bazelbuild/continuous-integration/blob/fcd3cdd216acf5b78449ae6c05da1c789f5ef76c/buildkite/setup-windows.ps1#L198-L208

(NDK 26d is actually the lastest version of the NDK, but we should test and update to the latest version in a separate change.)

**Comment by meteorcloudy** [comment]
Windows VMs has been updated.

Android NDK r25b is installed to `c:\android_ndk\r25b`. However the default `ANDROID_NDK_HOME` env var still points to `c:\android_ndk\r15c`, you can override that in your presubmit.yml file.

**Comment by ahumesky** [comment]
Thank you!

**Comment by meteorcloudy** [comment]
Re-open since the image has been rolled back

**Comment by meteorcloudy** [comment]
I have a new Windows VM image in testing with the fix from https://github.com/bazelbuild/continuous-integration/pull/1968, will push next Monday morning.
