### ISSUE TITLE
--build_tests_only flag seems to be missing

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#198]
Just noticed that the "Test" phase of a Bazel Postsubmit is missing the `--build_tests_only` flag. Without that flag some non-test targets fail to build (because they're platform-specific).

https://buildkite.com/bazel/bazel/builds/110#64a15bbe-6f31-4a98-a06a-4d4b4d02011b

**Comment by buchgr** [comment]
done
