### ISSUE TITLE
Ubuntu 16.04 is not using --experimental_ui by default

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#199]
This is pretty weird: Bazel on Ubuntu 14.04 seems to be using the new UI (--experimental_ui), but Bazel on Ubuntu 16.04 doesn't, even though it's on by default: https://github.com/bazelbuild/bazel/blob/2a2aa7ab31367da47f8449059fdfcddfba3a20f1/src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandEventHandler.java#L197

This is visible in the log: https://buildkite.com/bazel/bazel/builds/110#64a15bbe-6f31-4a98-a06a-4d4b4d02011b

We should find out why it's not enabled on Ubuntu 16.04.

**Comment by philwo** [comment]
FYI @buchgr

**Comment by buchgr** [comment]
fixed. bazel was always using experimental UI, but on 16.04 curses where detected as unsupported. setting `--curses=yes` now.
