### ISSUE TITLE
Update Android build tools to latest version 35.0.0

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/continuous-integration#1991]
The new mac CI runners appear to not have x86_64 emulation enabled (or something like that), and the current version of the installed android build tools have only x86_64 binaries, so the arm64 mac tests are now failing on rules_android. Build tools version 35.0.0 have x86_64 + arm64 combination binaries, so adding that version should fix the issue.

See https://github.com/bazelbuild/continuous-integration/issues/1981#issuecomment-2216336753

https://github.com/bazelbuild/continuous-integration/blob/122ce87694d0dd505a019321a04f8e64378bddbd/macos/mac-android.sh#L30

https://github.com/bazelbuild/continuous-integration/blob/122ce87694d0dd505a019321a04f8e64378bddbd/buildkite/setup-docker.sh#L189

https://github.com/bazelbuild/continuous-integration/blob/122ce87694d0dd505a019321a04f8e64378bddbd/buildkite/android.sh#L24

https://github.com/bazelbuild/continuous-integration/blob/122ce87694d0dd505a019321a04f8e64378bddbd/buildkite/setup-windows.ps1#L261

**Comment by fweikert** [comment]
Installed v35 on Silicon workers
