### ISSUE TITLE
Serve ci.bazel.io and ci-staging.bazel.io over SSL

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#20]
We have the certificate and the load balancer. We should figure out how to redirect the traffic through that load balancer and make it work.

**Comment by laszlocsomor** [comment]
Done, ci-staging.bazel.io is accepting HTTP traffic from Google-internal IPs.
I'll update the documentation with all the steps I took to get here.

**Comment by damienmg** [comment]
Grown to P0 as per discussion with @aehlig, @ulfjack and @helenalt this morning

**Comment by damienmg** [comment]
DNS update sent and the instance are behind GCLB so it should be transparent. After that SSL should work (I have been able to test not SSL with new IP but SSL still somehow has an issue, will investigate once the DNS change is propagated).

**Comment by damienmg** [comment]
DNS update submitted, waiting for it to propagate.

**Comment by damienmg** [comment]
Up and running, we serve of https now :)

**Comment by davidstanke** [comment]
I'm still able to load it via http -- it works for either protocol. We should redirect http to https. <img width="1680" alt="screen shot 2017-09-29 at 3 48 30 pm" src="https://user-images.githubusercontent.com/2166159/31033416-f0009324-a52d-11e7-90cc-fdf1f679640e.png">

I think [HSTS](https://www.chromium.org/hsts) is the current best practice for doing this.

**Comment by damienmg** [comment]
Closing this issue, getting HSTS is a different FR filed under #139
