### ISSUE TITLE
Request to add new project https://github.com/ceres-solver/ceres-solver

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/continuous-integration#2005]
Thank you for your interest in adding your project to Bazel CI.

At the moment we're operating at capacity and cannot add new projects except for projects maintained under the bazelbuild GitHub organization and for rules. To request a review for being added to Bazel CI, please follow the instructions below.

- [ ] My project is part of the bazelbuild GitHub organization.
- [ ] My project is a rules set of a GitHub organization other than bazelbuild.
- [x] I want to test the following project on Bazel CI: (https://github.com/ceres-solver/ceres-solver)
- [ ] I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by meteorcloudy** [comment]
Sorry, we currently don't have capacity to onboard new projects that's not under bazelbuild or not a critical rule set in the Bazel community.
