### ISSUE TITLE
libxml2 is no longer in Msys2 on Windows VM

### ISSUE THREAD

**Issue by crt-31** [bazelbuild/continuous-integration#2112]
We are attempting to reenable windows CI int rules_scala (https://github.com/bazelbuild/rules_scala/pull/1649).

The rules_scala tests require libxml2 to be available in MSYS2. But due to some changes in msys2's default package deps over last year, libxml2 isn't a default Msys2 package anymore.

I'm not sure how the VM state gets reused or reset between runs, so first question is: 
* Is it OK to just run pacman ourselves to install libxml2 in the batch_commands of the presubmit.yml?  (This wouldn't affect future runs would it?)

Or, would it be better to add libxml2 to the list of msys2 packages that get initially setup onto the VM (see setup-windows.ps1)

Or, possibly, add a config option to the presubmit.yml that allows us to declare extra msys2 packages we require and let the CI system handle it. 

Please advise on which is the best way forward,
Thanks.

**Comment by meteorcloudy** [comment]
> Is it OK to just run pacman ourselves to install libxml2 in the batch_commands of the presubmit.yml? (This wouldn't affect future runs would it?)

Yes, this is perfectly fine and encouraged. The Windows VMs are destroyed after each build.
