### ISSUE TITLE
bazel-integration-testing

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#214]
The https://github.com/bazelbuild/bazel-integration-testing repository takes around 2 hours to build 
and test. I think we should have it on our CI but we can't really run it postsubmit, because at a rate of 40 commits a day this would use up all our macs for 10 hours every day.

@philwo

**Comment by hsyed** [comment]
The strategy used in that repo is not tractable without Bazel core support for this. Each test instance will 1) unpack Bazel afresh and 2) refetch external deps of the workspace. 

N versions of supported bazel version * Test instances * stuff that needs to be downloaded into the test workspace = ouch.

**Comment by buchgr** [comment]
@hsyed fy we set u up on our CI. pull requests should be working now. windows will follow soon.

**Comment by philwo** [comment]
This project is being tested on CI, so I'll close this.
