### ISSUE TITLE
Make Windows slaves run on PR verification

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/continuous-integration#22]
Right now it's just running OS X and Linux, which is annoying for debugging Windows-only issues, e.g., http://ci.bazel.io/job/Gerrit-bazel-tests/88/.

**Comment by damienmg** [comment]
Dmitry has started working on that with windows-tests and as soon as we stabilize ci-staging (hopefully tomorrow) he can start working on it again (or delegate to @meteorcloudy)

**Comment by meteorcloudy** [comment]
Fixed at 3198e0f8a3b0e9d798754a176ddcd10709623be6
