### ISSUE TITLE
Run Kotlin related integration tests on updates to the Kotlin rules.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/continuous-integration#221]
I am integrating a bit more closely with the intellij plugin now (toolchains, etc). As part of this work I am writing integration tests in the intellij repo to test the aspect processing. Would it be possible for these to run when the rules are updated ? 

cc @brendandouglas 

It will probably be a while till any of this new work gets upstreamed.

**Comment by brendandouglas** [comment]
You might want to take a look at the rules_scala setup. I believe they're running the intellij aspect tests as part of the rules_scala-specific CI (https://github.com/bazelbuild/rules_scala/blob/master/test_intellij_aspect.sh).

A similar approach might work well in rules_kotlin, once kotlin-specific aspect tests are checked in to bazelbuild/intellij.

**Comment by buchgr** [comment]
@hsyed Can you try what @brendandouglas suggested? If not, it will take us a couple of months to accomodate this as we have a lot on our plate right now.

**Comment by hsyed** [comment]
@buchgr I'll have a look, there is quite a bit of a test space though (multiple IJ versions, multiple IJ products). 

@brendandouglas A smoke test script or a smoke test_suite in the intellij repo might make sense. This would contain a canonical set of configurations that must pass.

**Comment by philwo** [comment]
We do have full CI including presubmit tests for PRs now, so I'll consider this fixed.
