### ISSUE TITLE
FR: Show platform status on the pipeline view

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#222]
Would be nice to see the status of individual platforms directly on the platform dashboard.

Here's a little mock-up of that idea:

<img width="747" alt="screen shot 2018-02-26 at 17 10 18" src="https://user-images.githubusercontent.com/504652/36681112-f92dca74-1b17-11e8-8213-5b469b536e95.png">

(FYI @aehlig)

**Comment by buchgr** [comment]
That already exists :-). Just click on "299 builds" and you get exactly that view: https://buildkite.com/bazel/bazel-bazel-postsubmit/builds

I think this can be closed?

**Comment by philwo** [comment]
LOL, another Buildkite moment. 😂
