### ISSUE TITLE
FR: Have a yellow state for pipeline steps, e.g. for flaky tests.

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#223]
Currently flaky tests turn a pipeline step red, but that makes the life of the sheriff hard, because they can't quickly see if a red commit has a new breakage that needs to be rolled back, or just known flakyness. Would be nice if there were a third possible result state for steps that indicates trouble, but doesn't block the pipeline and has a different color.

Alternative idea (but I like the above one better): Possibility to mute failing tests, so that they don't turn the step red.

(FYI @aehlig)

**Comment by buchgr** [comment]
I am very much against this idea as it just makes us ignore flaky tests again as we did over the past years. Just look at [1]. And no, we can't just introduce this third state and fix them over time - we need to fix these tests now. Yes, the life of the sheriff will be harder until we have no more flaky tests but maybe that should just mean that a sheriff should also be involved with helping fix flaky tests. In my opinion flaky tests are a serious bug that need to be addressed immediately.

[1] https://ci.bazel.build/job/bazel-tests/

**Comment by dslomov** [comment]
Well, I have participated in >10 large software projects in my life. All of
them have been in a permanent war against flaky tests and none win. Making
sheriff life more comfortable today should take precedence over
grand-standing :) Also pretending that we do not have flaky tests will  it
make them go away - instead let us make them visible and identifiable.

my 2c.

**Comment by buchgr** [comment]
@dslomov They have been visible for years and absolutely *nothing* happened. 

I would estimate the number of really flaky (>10% flakyness) tests in our project to be around a dozen - it's mostly the same tests that fail frequently. We need to fix them or delete them.

**Comment by philwo** [comment]
Obsolete, as we detect flaky tests now and Florian is also working on a dashboard to visualize them.
