### ISSUE TITLE
Collaborators are not whitelisted when PR branch is in project repo

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#226]
I should be whitelisted for pull requests to run on CI, as I'm using my @google.com address on GitHub, but I created a PR for rules_docker here: https://github.com/bazelbuild/rules_docker/pull/332 and apparently it still has to be verified by a project owner.

Buildkite link: https://buildkite.com/bazel/docker-rules-docker-presubmit/builds/1

**Comment by chaoren** [comment]
Looks like this is fixed?
None of our builds today require manual unblocking.
Yesterday (blocked): https://buildkite.com/bazel/intellij-plugin/builds/546
Today (not blocked): https://buildkite.com/bazel/intellij-plugin/builds/548

**Comment by chaoren** [comment]
The verify block is back again starting with this build: https://buildkite.com/bazel/intellij-plugin/builds/555

**Comment by philwo** [comment]
Friendly ping @buchgr.

**Comment by philwo** [comment]
Verify block is gone, so this is obsolete.
