### ISSUE TITLE
Missing pre- and/or postsubmit pipelines

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#228]
I went through all repos in the bazelbuild organization and checked the webhooks whether they have pre- and postsubmit Buildkite hooks. Here's what is still missing:

**Missing presubmits:**

- https://github.com/bazelbuild/bazel-skylib
- https://github.com/bazelbuild/bazel-toolchains
- https://github.com/bazelbuild/bazel-watcher
- https://github.com/bazelbuild/buildtools
- https://github.com/bazelbuild/eclipse
- https://github.com/bazelbuild/intellij
- https://github.com/bazelbuild/migration-tooling
- https://github.com/bazelbuild/rules_closure
- https://github.com/bazelbuild/rules_d
- https://github.com/bazelbuild/rules_go
- https://github.com/bazelbuild/rules_gwt
- https://github.com/bazelbuild/rules_jsonnet
- https://github.com/bazelbuild/rules_k8s
- https://github.com/bazelbuild/rules_nodejs
- https://github.com/bazelbuild/rules_perl
- https://github.com/bazelbuild/rules_sass
- https://github.com/bazelbuild/rules_scala
- https://github.com/bazelbuild/rules_typescript
- https://github.com/bazelbuild/skydoc

**Missing post and presubmits:**

- https://github.com/bazelbuild/bazel-gazelle
- https://github.com/bazelbuild/continuous-integration
- https://github.com/bazelbuild/rules_apple
- https://github.com/bazelbuild/rules_dotnet
- https://github.com/bazelbuild/rules_pkg
- https://github.com/bazelbuild/rules_webtesting
- https://github.com/bazelbuild/sandboxfs
- https://github.com/bazelbuild/tulsi
- https://github.com/bazelbuild/vim-bazel

**Maybe add these:**

- https://github.com/angular/angular/tree/master/packages/bazel

FYI @buchgr

**Comment by buchgr** [comment]
can be closed?

**Comment by philwo** [comment]
Obsolete.
