### ISSUE TITLE
Support building with a nightly green and not just released bazel

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#233]
For the rules repos, it would be nice to have two setups: released bazel and `master`s last green.

What the rules repos do their own releases, it is useful to know that our current `master` works with both the last bazel release, but also with what will the next bazel release.  We might need to adopt some new feature from bazel, and if we have detection/fallback code in our Skylark the release build will stay green, but we won't see the failure in our PRs or continuous build without a build happening against the `master` of bazel.

**Comment by philwo** [comment]
This is all done: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#using-a-specific-version-of-bazel
