### ISSUE TITLE
Provide installers without java (in latest.json)

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#234]
https://github.com/bazelbuild/bazel/releases includes installers with and without the jdk, but looking at https://storage.googleapis.com/bazel-builds/metadata/latest.json, it doesn't seem to include both.

Actually, are those even installers or are they actually bazel binaries?  Seems like it would make sense to provide things most like what is provided in the way of releases.

**Comment by philwo** [comment]
We're no longer distributing or testing Bazel without our embedded JDK, so this is probably obsolete.

People are of course welcome to build their own Bazel binaries without an embedded JDK for their own purposes, e.g. for a Linux distribution this is probably preferred.
