### ISSUE TITLE
Support repos with nested workspaces

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#238]
We currently can't test repos with nested workspaces:
 - https://github.com/bazelbuild/examples
 - https://github.com/bazelbuild/rules_nodejs/blob/master/.circleci/config.yml#L76

We should add support for that.

**Comment by philwo** [comment]
FYI @alexeagle

**Comment by irengrig** [comment]
I think implementing this functionality is really useful,
but wanted to mention that I found a (hopefully temporary) workaround:

it is possible to call the tests of a nested workspace from the wrapping workspace: https://github.com/bazelbuild/rules_foreign_cc/blob/master/.bazelci/config.yaml
and
https://github.com/bazelbuild/rules_foreign_cc/blob/006d5f6f8b6f6922943add61fcf038a4a1d802e1/WORKSPACE#L7

However, it forces putting the tests/examples workspace-level initiazation code into the WORKSPACE of the main project itself, which is not good.
That is why I hope we allow testing nested workspaces.
