### ISSUE TITLE
Login-less build status badges

### ISSUE THREAD

**Issue by dekkagaijin** [bazelbuild/continuous-integration#240]
The link leading from the Bazel CI badge for `rules_docker` is
A) login-gated
B) broken, when you do log in
 
https://github.com/bazelbuild/rules_docker

I don't know if B caused A, or if CI pipelines are private by default, but it seems like looking at build failures shouldn't _require_ credentials.

**Comment by dekkagaijin** [comment]
@mattmoor FYI

**Comment by buchgr** [comment]
Hi Jake,

I totally agree. This is a feature that Buildkite currently doesn't support but they are working on it and we are one the public beta. As soon as it's available we'll enable it.

You generally don't need to log in to view build and test results: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#build-and-test-results

**Comment by dekkagaijin** [comment]
Awesome, thanks

**Comment by buchgr** [comment]
(I also invited you to Buildkite)

**Comment by dekkagaijin** [comment]
I saw, danke :)
