### ISSUE TITLE
Support testing against different Bazel versions

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#241]
released versions, bazel HEAD

cc: @jayconrod

**Comment by DavidGoldman** [comment]
See #233 for a similar request.

Would be convenient to support testing against the following different versions of Bazel:

- Released versions (testing against the current release, testing against a specific release)
- `HEAD` version of Bazel (may be unstable, but useful to catch things early)
- Nightly green version of Bazel or equivalently the last green version of `HEAD` Bazel (stable and allows us to check compatibility with future Bazel releases)

**Comment by philwo** [comment]
This is all done: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#using-a-specific-version-of-bazel

**Comment by jayconrod** [comment]
Thanks for implementing this!

What's the minimum version of Bazel that BuildKite supports? I tried 0.18.0 in bazelbuild/rules_go#2084, which is currently the rules_go minimum version, but I got [this error](https://buildkite.com/bazel/rules-go-golang/builds/1163#7439e19c-ceb6-4e69-a5cf-de40a844650a).

```
bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --verbose_failures --keep_going --jobs=32 --announce_rc --experimental_multi_threaded_digest --experimental_repository_cache_hardlinks --disk_cache= --sandbox_tmpfs_path=/tmp --google_default_credentials --remote_cache=https://storage.googleapis.com/bazel-untrusted-buildkite-cache --remote_timeout=60 --remote_max_connections=200 --remote_default_platform_properties=properties:{name:"cache-silo-key" value:"[REDACTED]"} ...
--
  | ERROR: Unrecognized option: --remote_default_platform_properties=properties:{name:"cache-silo-key" value:"[REDACTED]"}
  | ERROR: Failed to connect to 'https://storage.googleapis.com/bazel-untrusted-buildkite-cache': cannot find a NameResolver for https://storage.googleapis.com/bazel-untrusted-buildkite-cache
  | bazel build failed with exit code 2
```

It's likely rules_go will need to bump the minimum Bazel version to start using transitions when they are stable, so maybe nothing needs to be fixed. If there's an easy change to fix this, it would be nice to have though.

**Comment by fweikert** [comment]
We should probably advertise which versions of Bazel can be run on CI.

The flag in question was added in Bazel 0.23.0. I see three easy options:

1. Use Bazel >= 0.23.0
2. Disable remote caching by passing the --monitor_flaky_tests flag to the bazelci.py script (ugly hack).
3. Use your own remote cache (by setting --remote_cache etc).

Maybe we should add an option to disable the default remote caching code path, or make it backwards compatible.

**Comment by philwo** [comment]
I’ll try to fix this next week. We have to make our flag-computation code in bazelci.py version aware so that it doesn’t try to use flags that only exist in newer versions with older Bazel’s.
