### ISSUE TITLE
choco install nodejs yarn

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#242]
We want to test angular rules on Windows which needs nodejs and yarn.

```
choco install nodejs yarn
```

cc: @alexeagle

**Comment by buchgr** [comment]
nevermind. we shouldn't install these.

**Comment by alexeagle** [comment]
yeah that's the job of the `node_repositories` workspace rule https://github.com/bazelbuild/rules_nodejs#installation
