### ISSUE TITLE
Run Bazel tests on Ubuntu 16.04 with Python 3

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#244]
The old CI had a special configuration to run tests with Python 3:
https://github.com/bazelbuild/bazel/commit/b30dfcb639f284d5b43973b6e8742e148f438fbe

We should also do this on the new CI.

**Comment by brandjon** [comment]
This will be obsolete when bazelbuild/bazel/issues#7375 is implemented.

**Comment by philwo** [comment]
Thanks, Jon! Closing this then.
