### ISSUE TITLE
Ubuntu 18.04 LTS is soon to be released. 

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#255]
We'll need to test Bazel on it. We can then drop Ubuntu 14.04.

https://itsfoss.com/ubuntu-18-04-release-features/

**Comment by philwo** [comment]
@rkachach Can you try grabbing a stack trace of Bazel when it's stuck and burning CPU like this? It might show us what's going on.

There are two ways:
1) Run `jstack PID` where PID is the process id of the "java" process of Bazel. You can find it via `ps axu | egrep "bazel.*java"`. Look for a process that's called "bazel(name of your workspace)" with a long command-line.
2) Alternatively, press Ctrl-\ in the terminal where Bazel is running. Then attach the file "server/jvm.out" that Bazel puts into its output base. You can get the path to the output base by running `bazel info output_base` in the same directory where your build is running.

**Comment by philwo** [comment]
This has been done in the meantime.
