### ISSUE TITLE
bazel-watcher has incorrect build failing badge

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/continuous-integration#257]
https://github.com/bazelbuild/bazel-watcher shows a build failing badge while the build actually succeeds on buildkite (at least the master branch).

This pull request is failing:
https://github.com/bazelbuild/bazel-watcher/pull/108
Perhaps that's causing the issue (note that the repo in the pull request confusingly is called rules_webtesting).

**Comment by buchgr** [comment]
fixed! thanks
