### ISSUE TITLE
Check for PR approval as alternative to verifying on Buildkite

### ISSUE THREAD

**Issue by drigz** [bazelbuild/continuous-integration#266]
When there is a PR that:

- is created by an external contributor (so review is required before the CI run)
- was reviewed and approved by a project collaborator (with GitHub's review functionality)

The collaborator must still click through to Buildkite to verify the PR (which requires a Buildkite account).

Bazel CI should check for PR approval and initiate a build.

**Comment by philwo** [comment]
We currently don't require a verification. For the future, I'm planning to just check that people have signed the CLA (because that's a requirement for merging the PR anyway). I'm tracking that here: https://github.com/bazelbuild/continuous-integration/issues/456
