### ISSUE TITLE
Release pipeline fails when the latest commit is not from a Googler

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#281]
The check in https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/setup-ubuntu.sh#L217 fails since BUILDKITE_BUILD_CREATOR_EMAIL contains the address of the commit author, who might not be a Googler.

I'm not sure whether this check is really needed, but I'm going to delete it for now to unblock the release.

**Comment by fweikert** [comment]
Workaround: simply start a new build in the pipeline (via the "new build" button in the top right corner).

**Comment by katre** [comment]
Is this issue still being worked on?

**Comment by philwo** [comment]
I think this should no longer happen. Did you see it again?

**Comment by katre** [comment]
No, I haven't. I was wondering if it should be closed and, if so, if the reference from https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md should be removed.
