### ISSUE TITLE
WARN: No artifacts found that match the file pattern "output/ci/**". Configuration error?

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#29]
This looks ominous:
```
Archiving artifacts
WARN: No artifacts found that match the file pattern "output/ci/**". Configuration error?
WARN: ‘output/ci/**’ doesn’t match anything, but ‘**’ does. Perhaps that’s what you mean?
Finished: SUCCESS
```

Scroll to the bottom of:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=ubuntu_15.10-x86_64/838/console

**Comment by laszlocsomor** [comment]
This also causes problems downstream:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel-Install/3197/console

**Comment by laszlocsomor** [comment]
I ssh'd into the machine and see this:
```
$ pwd
/home/ci/workspace/Bazel/JAVA_VERSION/1.7/PLATFORM_NAME/ubuntu_15.10-x86_64

$ ls output
bazel
```

So there's indeed no `output/ci` directory.

**Comment by damienmg** [comment]
That's normal that's not even a misconfiguration. We do not deploy ubuntu 15.10 binaries as it just do integration test that ./compile.sh works on those machine

**Comment by damienmg** [comment]
If you look downstream project log, you can see there is an issue with the installer: http://ci.bazel.io/job/Bazel-Install/3198/console. I would be @aehlig change that recently re-added a .bazelrc. We have to rollback another change on ci that was introduced when we removed the .bazelrc file

**Comment by laszlocsomor** [comment]
Thanks, that looks like a plausible cause indeed. However, there's more:
See http://ci.bazel.io/job/Bazel-Install/3208/console

Look at the stack trace at the top. That comes from Jenkins itself.

**Comment by laszlocsomor** [comment]
> We have to rollback another change on ci that was introduced when we removed the .bazelrc file

Do you know which one?

**Comment by laszlocsomor** [comment]
Found it.
