### ISSUE TITLE
TensorFlow_serving still failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#292]
https://buildkite.com/bazel/tensorflow-serving/builds/789

The build failed to build `@com_github_libevent_libevent//:libevent-srcs`, which is defined here:
https://github.com/tensorflow/serving/blob/c42810c1e149269d3bdeefa0fca56092215b1bb6/third_party/libevent.BUILD#L61

Reproduce:
```
pcloudy@buildkite-worker-ubuntu1804-java8-001d:/tmp/libevent.Qx97g$ ./autogen.sh
...
libtoolize: putting auxiliary files in '../..'.
libtoolize:   error: copying '/usr/share/libtool/build-aux/ltmain.sh' to '../../' failed
...
```

The reason is libtoolize tried to copy `ltmain.sh` to root `/` and it does't have the write permission.
It chose `../../` following the rule here: https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Input.html
> The default is srcdir or srcdir/.. or srcdir/../.., whichever is the first that contains install-sh. The other files are not checked for, so that using AC_PROG_INSTALL does not automatically require distributing the other auxiliary files. It checks for **install.sh** also, but that name is obsolete because some make have a rule that creates install from it if there is no makefile.

And we do have a `install.sh` script under /, which appears to be the installer of Bazel. After I renamed the file, `./autogen.sh` worked because then libtoolize chose `./` instead of `../../` to copy `ltmain.sh`.

@buchgr , Do we need need the installer? Can we remove that file after installing Bazel?

**Comment by buchgr** [comment]
Good find. I don't think we need that `install.sh`. I ll create new images and remove it.
