### ISSUE TITLE
Bazel with downstream projects red on macs

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/continuous-integration#293]
I'm told that this is caused by some optimization involving `git bundle`. Hope you know what that means :) Thanks!

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/321#1c52f3f1-f03c-4e3c-878d-8d88b131e91e

	git clone --recurse-submodules --reference /usr/local/var/bazelbuild https://gerrit.googlesource.com/gerrit.git /Users/buildkite/builds/buildkite-imacpro-3-1/bazel-downstream-projects/gerrit
	--
	  | Cloning into '/Users/buildkite/builds/buildkite-imacpro-3-1/bazel-downstream-projects/gerrit'...
	  | fatal: reference repository '/usr/local/var/bazelbuild' is not a local repository.
	  | Traceback (most recent call last):
	  | File "bazelci.py", line 1252, in <module>
	  | sys.exit(main())
	  | File "bazelci.py", line 1239, in main
	  | args.build_only, args.test_only, args.monitor_flaky_tests)
	  | File "bazelci.py", line 363, in execute_commands
	  | clone_git_repository(git_repository, platform)
	  | File "bazelci.py", line 633, in clone_git_repository
	  | "/usr/local/var/bazelbuild", git_repository, clone_path])
	  | File "bazelci.py", line 842, in execute_command
	  | return subprocess.run(args, shell=shell, check=fail_if_nonzero, env=os.environ).returncode
	  | File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
	  | output=stdout, stderr=stderr)
	  | subprocess.CalledProcessError: Command '['git', 'clone', '--recurse-submodules', '--reference', '/usr/local/var/bazelbuild', 'https://gerrit.googlesource.com/gerrit.git', '/Users/buildkite/builds/buildkite-imacpro-3-1/bazel-downstream-projects/gerrit']' returned non-zero exit status 128.

**Comment by mhlopko** [comment]
CC @buchgr

**Comment by philwo** [comment]
@buchgr Looks like the Git reference repository is missing on at least imacpro-3. Can you check the machines and add it where necessary? :)

**Comment by philwo** [comment]
@buchgr If the directory is really missing, all builds on that machine would fail all the time. Have you had time to look into this?

**Comment by buchgr** [comment]
no I haven't. can you take it?

**Comment by philwo** [comment]
@buchgr If you show me how to login to the new machines tomorrow, yes :D

**Comment by lfpino** [comment]
Any news about this? The Mac jobs in "Bazel with downstream projects" are still red: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/330

**Comment by lfpino** [comment]
Friendly ping @philwo, we've been running blind on Mac for a couple of days now.

**Comment by philwo** [comment]
@lfpino Sorry for the delay. I need physical access to the iMac Pros to fix this, but I wasn't in the office today. :( Will fix it first thing tomorrow!

**Comment by lfpino** [comment]
No problem! It's just scary to see so many red boxes in our CI, since it's usually so green :-)

**Comment by mhlopko** [comment]
Is this fixed?

**Comment by buchgr** [comment]
looking at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/356 makes me think so

**Comment by philwo** [comment]
I still have to reenable git reference support on the Macs.

**Comment by mhlopko** [comment]
Ack, thanks!

**Comment by philwo** [comment]
I've enabled git reference support on the Macs now. :)
