### ISSUE TITLE
Windows Tensorflow CI failing

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/continuous-integration#297]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/341#46616c2f-642e-456d-977a-87e70192322b

Not sure exactly when this particular failure started, as it's surrounded by a few flakes, but around here:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/340#23353efc-199f-482d-9056-ec3025f316ba

.....external/com_google_absl/absl/base/internal/raw_logging.cc
--
  | c1xx: error C2220: warning treated as error - no 'object' file generated
  | c1xx: warning C4117: macro name '__DATE__' is reserved, '#define' ignored
  | c1xx: warning C4117: macro name '__TIMESTAMP__' is reserved, '#define' ignored
  | c1xx: warning C4117: macro name '__TIME__' is reserved, '#define' ignored
  | cl : Command line warning D9025 : overriding '/w' with '/W3'

**Comment by meteorcloudy** [comment]
Looks like the [treat_warnings_as_errors](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL.tpl#L979) feature was enabled somehow. But it's not marked as enable by default,  @mhlopko @rongjiecomputer  any idea?

**Comment by meteorcloudy** [comment]
Ah, the `/WX` comes from absl's build script, see https://github.com/abseil/abseil-cpp/blob/master/absl/copts.bzl#L119

But it's still strange the build is passing with Bazel 0.15.0 but failing with Bazel@HEAD

**Comment by meteorcloudy** [comment]
Just debugged on this, https://github.com/bazelbuild/bazel/pull/5631 should fix the issue

**Comment by rongjiecomputer** [comment]
@meteorcloudy Sorry for the bug. I am working on test to cover all new MSVC CROSSTOOL features in https://github.com/bazelbuild/bazel/pull/5549.
