### ISSUE TITLE
TensorFlow failing on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#306]
```
tensorflow/python/lib/core/py_func.cc(355): error C2440: '=': cannot convert from 'const char *' to 'char *'
tensorflow/python/lib/core/py_func.cc(355): note: Conversion loses qualifiers
```
The first failure I found is https://buildkite.com/bazel/tensorflow/builds/1020

**Comment by meteorcloudy** [comment]
@buchgr @philwo I couldn't reproduce this bug locally. It's not failing on TF CI, either. 
Did we change VS or Python version in the new image?

**Comment by philwo** [comment]
Hi @meteorcloudy! :) VS is the same, but for Python we don't fix the version to a specific one, so I think it has been updated to Python 3.7 on macOS and Windows during the last regular update round.

**Comment by meteorcloudy** [comment]
Oh! I think TensorFlow only supports Python3.5 and Python 3.7. Is it possible to downgrade it?

**Comment by philwo** [comment]
I'll try it! Looks like we can specify an exact version for `choco install` :)

**Comment by meteorcloudy** [comment]
Yes!
Btw, according to https://docs.python.org/3/whatsnew/3.7.html
>   The result of PyUnicode_AsUTF8AndSize() and PyUnicode_AsUTF8() is now of type const char * rather of char *. (Contributed by Serhiy Storchaka in bpo-28769.)

So this should be the root cause.

**Comment by philwo** [comment]
Typical C++ issue - if it breaks, either add or remove `const`... :laughing:

**Comment by meteorcloudy** [comment]
Hi, @philwo Did the new image containing https://github.com/bazelbuild/continuous-integration/commit/9c932b7bdcfa625ac52bf3e10bfd45d8c3de4989 get deployed? I'm still seeing the same build error on Windows and Ubuntu:
https://buildkite.com/bazel/tensorflow/builds/1092#bd8fbcff-7400-4f30-bb30-3e9b984d6865

**Comment by philwo** [comment]
Hi @meteorcloudy - sorry! Not yet :( I'm still waiting for Bazel 0.16.1 - Jakob is just pushing it and then I'll roll out the new images on all platforms!

**Comment by meteorcloudy** [comment]
Sounds great! Thanks!

**Comment by meteorcloudy** [comment]
It's failing on a different issue, closing this one.
