### ISSUE TITLE
Let Jenkins jobs run in parallel on the same machine

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#31]
After being stuck for over 7 hours, I killed a CI job today. See related FR about adding timeout: https://github.com/bazelbuild/continuous-integration/issues/30

As soon as I killed the job, the worker started the next queued job. Since the VMs are [fairly beefy](https://github.com/bazelbuild/continuous-integration/blob/517d962874fabbc985f4800ad2474bab83182b8a/gce/vm.sh#L126) for Bazel, we could easily run 2 or 3 builds of the same job concurrently.

**Comment by damienmg** [comment]
Unfortunately that is not so much true. 8 cores for running the whole bazel test suite isn't that much.
