### ISSUE TITLE
Add rules_dotnet to the CI

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/continuous-integration#312]
https://github.com/bazelbuild/rules_dotnet

**Comment by fweikert** [comment]
The rules_dotnet pipeline was added in September 2018 (at least its first build has that timestamp), but I don't see any recent activity. I guess that the repo owners didn't set up the webhook.

**Comment by laurentlb** [comment]
I don't see it in https://buildkite.com/bazel/bazel-at-head-plus-downstream

What should owners do? Do we have any link to documentation?
(cc @tomaszstrejczek)

**Comment by fweikert** [comment]
Ok, there is a misunderstanding: We already have a pipeline for rules_dotnet, but it hasn't been tested as part of the downstream pipeline.

I'll open a PR.

**Comment by fweikert** [comment]
I have a fix, but it doesn't make much sense to merge is now: The rules_dotnet pipeline is completely stale (no build in recent months), and a manually triggered build failed completely. The rules_dotnet team should properly set up the GitHub webhook and then fix their tests.

**Comment by tomaszstrejczek** [comment]
Some time ago I tried with  philwo@google.com to get the pipeline fixed. However, we failed. Rules_dotnet require for NET framework testing a recent windows build with long path names and symbolic links enabled. Therefore I use Azure Pipelines with a private windows build agent.
Ofc I'm willing to provide any support necessary to get the rules on Buildkite.

Regards,
Tomek

________________________________

**Comment by fweikert** [comment]
Pipeline looks good, so I'll go ahead and add it to the downstream pipeline.
