### ISSUE TITLE
RBE toolchain flags can be safely upgraded without breaking projects

### ISSUE THREAD

**Issue by xingao267** [bazelbuild/continuous-integration#319]
https://github.com/bazelbuild/continuous-integration/pull/314 breaks several projects that does not pin to the commit of bazel-toolchains that contains configs/ubuntu16_04_clang/1.0/bazel_0.16.1/. We've created issues or sent PR to update their WORKSPACE pin.

https://github.com/bazelbuild/rules_scala/issues/600
https://github.com/bazelbuild/rules_rust/issues/125
https://github.com/bazelbuild/rules_go/issues/1698
https://github.com/bazelbuild/rules_nodejs/issues/296

We need to figure out a better path to update toolchain flags and project's pin to @bazel-toolchains. On one hand, we don't want to break project's that didn't update their WORKSPACE pin, on the other hand, we don't want to keep using legacy toolchain flags in the Buildkite configuration. 

In the short term, we need to make sure the flags are updated after project's WORKSPACEs are updated.

In the long term, maybe having some @bazel_toolchains//configs/ubuntu16_04_clang/1.0/latest/default:toolchain target defined in bazel-toolchains repo.

cc @philwo

**Comment by philwo** [comment]
@xingao267 Is this still an issue or can I close it?

**Comment by xingao267** [comment]
From the code (https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/bazelci.py#L1241), we should actually use the new rbe_repo rules and flags. @nlopezgi

**Comment by xingao267** [comment]
We should be able to roll forward https://github.com/bazelbuild/continuous-integration/pull/565/files as Buildkite now supports running docker. Let me make sure the rule repos have bazel_toolchains pinned to a proper commit.

**Comment by philwo** [comment]
Thank you! :)

**Comment by nlopezgi** [comment]
sent https://github.com/bazelbuild/continuous-integration/pull/685

**Comment by philwo** [comment]
Closing this, as the work is done and this is running now :)
