### ISSUE TITLE
submodule 'foo' cannot add alternate: path 'bar' does not exist

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/continuous-integration#320]
Discovered on the mac slave:

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/426#21e05c7e-d07b-4008-a526-93bee09a8e9d

**Comment by meteorcloudy** [comment]
This is still happening with Gerrit and Protobuf:

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/441#d504e8dc-24dd-45ab-aa82-48bcbb402520
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/441#55f2750b-e73a-4006-9a63-f7be5d8616ec

**Comment by philwo** [comment]
Sorry! Will fix it "once and for all" today... :|

**Comment by philwo** [comment]
On it right now, trying to repro and fix again on my iMac. I have no idea why Git on macOS has such a different behavior than on Linux and Windows.
