### ISSUE TITLE
PermissionError: The process cannot access the file because it is being used by another process: 'D:\\temp\\tmpf2rxws4j\\build_bep.json'

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/continuous-integration#321]
We see this lovely thing here: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/425#818dd0c2-3b15-41c3-983b-cb001e9985b4

Philipp says it's the CI config issue, so here you are :)

**Comment by philwo** [comment]
How do you ensure a file handle is really closed on Windows?

You reboot the entire machine. So that's what we'll be doing from now on. ;)

(Also for other reasons, but this will surely fix this error, too.)

**Comment by mhlopko** [comment]
I guess that doesn't work :) https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/505#68931062-f240-4ec6-877f-ae6f70f11564
