### ISSUE TITLE
TensorFlow fails with Bazel 0.16.1 with a permission denied error

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#329]
https://buildkite.com/bazel/tensorflow/builds/1296#9f96c049-e340-4b91-85b3-96f771e4822b
```
ERROR: C:/users/b/_bazel_b/73dvkxsy/external/com_google_absl/absl/strings/BUILD.bazel:32:1: Couldn't build file external/com_google_absl/absl/strings/_objs/strings/str_replace.obj: C++ compilation of rule '@com_google_absl//absl/strings:strings' failed: Failed to delete output files after incomplete download. Cannot continue with local execution.: C:/users/b/_bazel_b/73dvkxsy/execroot/org_tensorflow/bazel-out/_tmp/action_outs/stderr-1709 (Permission denied)
```

A similar error in Test Bazel job with Bazel@HEAD
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/449#11ae8513-6b85-4904-bbaa-11b0b7896a44
```
ERROR: D:/build/buildkite-worker-windows-java8-dp0f-1/bazel/bazel-with-downstream-projects-bazel/third_party/grpc/BUILD:72:1: Couldn't build file third_party/grpc/_objs/grpc_unsecure/avl.obj: C++ compilation of rule '//third_party/grpc:grpc_unsecure' failed: Failed to delete output files after incomplete download. Cannot continue with local execution.: C:/users/b/_bazel_b/lrtyebp3/execroot/io_bazel/bazel-out/x64_windows-
```

/cc @buchgr @philwo might be a Windows machine bug?

**Comment by philwo** [comment]
My guess is, it's a bug in remote execution, where a file handle isn't closed and then later Bazel cannot delete / overwrite a file that it already opened in the remote execution code.

**Comment by meteorcloudy** [comment]
Do we already have remote execution running on Windows machines?

**Comment by philwo** [comment]
Sorry - I meant remote caching!

**Comment by meteorcloudy** [comment]
That make sense! Did we recently upgraded remote caching code? Because it's only happening since yesterday.

**Comment by philwo** [comment]
No.. we still have Bazel 0.16.1 running on the VMs. We could try upgrading to 0.17.1 and see if that fixes the bug? :)

**Comment by meteorcloudy** [comment]
Sounds good, let's try it ;)

**Comment by philwo** [comment]
I'll get to it asap (but am just on the way to the airport ^^)!

**Comment by meteorcloudy** [comment]
Oh, you are OOO today, take it easy! No hurries! 
And thanks for the quick respond!

**Comment by meteorcloudy** [comment]
Hmm, looks like all buildkite presubmit are failing with the same error:
https://buildkite.com/bazel/google-bazel-presubmit

**Comment by meteorcloudy** [comment]
Will deleting and recreating all Windows vms work this around?

**Comment by meteorcloudy** [comment]
Thanks, I'll try to rerun the presubmit

**Comment by meteorcloudy** [comment]
Hmm, still failing with the same error.

**Comment by philwo** [comment]
OK, will try to temporarily disable remote caching for presubmits on Windows.

**Comment by philwo** [comment]
I think this is solved (for now). Please re-open if you see it again!
