### ISSUE TITLE
Verify lint and formatting on CI

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/continuous-integration#338]
I still have to use CircleCI for rules_nodejs and rules_typescript to check that BUILD/bzl files are formatted and that PRs don't introduce style guide violations.

It's particularly important for rules_typescript where PRs need to sync into google3, and so it falls on the googler doing the sync to fix issues that the PR author didn't.

I'd like to turn down our CircleCI setup and use only buildkite, but this is a blocker. Also I'm tearing down an old bazel caching setup on CircleCI, so now I have to build buildifier and skylint from source on every build which makes the linting job much slower.

**Comment by alexeagle** [comment]
Note, this has gotten better somewhat now that buildifier has binary releases published. But I still have to run a separate CI for rules_nodejs

/cc @fweikert

**Comment by alexeagle** [comment]
Ping! We're adding buildifier format/lint checks to rules_typescript in https://github.com/bazelbuild/rules_typescript/pull/357

But as Googlers submit changes in g3, these will not be checked. So I expect our CircleCI will keep going red on master as those are submitted. This puts me as the maintainer in the position of having to send a follow-up change each time to keep the build green.

/cc @manekinekko

**Comment by fweikert** [comment]
I'm working on enabling Buildifier in lint mode for Buildkite pipelines. See https://buildkite.com/bazel/re2-dummy/builds/6#bdeb9cb0-61a6-4a4e-93ab-397c853c762f for an example (only visible to registered users, does not fail on lint warnings yet).

**Comment by fweikert** [comment]
https://github.com/bazelbuild/continuous-integration/pull/448 has been merged
