### ISSUE TITLE
Make fake release candidate possible

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#34]
This should be possible by just having a special name pattern for release names that just doesn't send announcement mails.

/cc @dslomov

**Comment by kchodorow** [comment]
Would it be possible to have a separate job that sent the email?  Then the release manager could manually trigger it when they wanted to send an email (which might decrease stress about messing up the release process in general).

**Comment by damienmg** [comment]
Yes this is feasible. Probably a bit more work. I am unsure of the benefits (I can see them but I cannot judge if it is worth the bucket, and that would introduce another manual step in the actual process).

**Comment by kchodorow** [comment]
Thank you!
