### ISSUE TITLE
Downstream tests not running for 0.19.0rc3 due to No JDK host failures

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#341]
I am trying to run downstream tests to verify the 0.19.0rc3 release (...). Unfortunately, the tests on "Build Bazel (Ubuntu 18.04 (no JDK))" are failing consistently, and this is blocking all subsequent tests.

Error log: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/477#99bf56bd-c8c6-4549-aba9-42c190f623be
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/c24aa78459a2eb8c67d72009b6f722eb/external/bazel_tools/tools/jdk/BUILD:18:1: every rule of type java_runtime_alias implicitly depends upon the target '@openjdk_linux_archive//:runtime', but this target could not be found because of: no such package '@openjdk_linux_archive//': The repository could not be resolved
```

Possible Fixes:
1. Remove the "no JDK" tests.
2. Add an override to force downstream tests to run even if the first stage tests fail.

**Comment by philwo** [comment]
I think there's a cherry-pick missing: https://github.com/bazelbuild/bazel/commit/54c2572a8cabaf2b29e58abe9f04327314caa6a0

**Comment by katre** [comment]
That fixed it, thanks!
