### ISSUE TITLE
Add experimental linter (buildifier) to BuildKite 

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/continuous-integration#347]
Hi,
As discussed offline with @philwo and @laurentlb it's probably a good idea to add buildifier as a linter to BuildKite and preferably PR all existing bazelbuild rulesets with adding this as a non-required check.
This will allow collecting more info about the linter as well as promote us towards the "good" rulesets mode we're looking to get to.

**Comment by fweikert** [comment]
This feature has been implemented some time ago. Documentation: https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#running-buildifier-on-ci
