### ISSUE TITLE
Documentation: curl link is incorrect

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/continuous-integration#35]
https://github.com/bazelbuild/continuous-integration/blob/master/docs/machines.md instructs the user to do "curl https://bazel.googlesource.com/continuous-integration/+/master/mac/setup_mac.sh", which downloads an HTML page (to stdout). It needs some option to get the raw file.

**Comment by kchodorow** [comment]
Also, doc should mention:

* ci needs to be an admin user.
* The sudo command is wrong, as setup_mac.sh isn't executable and needs a node name.

**Comment by kchodorow** [comment]
Also, what node name should be.

**Comment by kchodorow** [comment]
Also, what to do after running those lines.

**Comment by damienmg** [comment]
Doc already mention that ci needs to be admin (sudo), node name (jenkins node name) and what to do after (set the machine to never sleep).

I'll add a check for sudo, and I found the command for the machine to never sleep
