### ISSUE TITLE
Re-enable skydoc and rules_sass

### ISSUE THREAD

**Issue by jelbourn** [bazelbuild/continuous-integration#363]
See https://github.com/bazelbuild/rules_sass/issues/27

The rules_sass integration was failing due to skydoc failing. https://github.com/bazelbuild/skydoc/pull/113 updated skydoc.

**Comment by mhlopko** [comment]
Fixed by https://github.com/bazelbuild/continuous-integration/commit/989d3871c025dfbaacae9bc8ada807a69c88db44
