### ISSUE TITLE
rules_rust is failing on ubuntu 14.04

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#379]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/581#37a1729b-a2af-4e71-a884-3a6b569cb84f
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/86f1779ca733938ca729bb6388303f9b/external/examples/hello_out_dir/BUILD:8:1: Couldn't build file external/examples/hello_out_dir/hello_out_dir.out_dir: error executing shell command: '/bin/bash -c mkdir bazel-out/k8-fastbuild/bin/external/examples/hello_out_dir/hello_out_dir.out_dir && tar -xzf external/examples/hello_out_dir/repacked_srcs.tar.gz -C bazel-out/k8-fastbuild/bin/ex...' failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
--
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox
  | mkdir: cannot create directory 'bazel-out/k8-fastbuild/bin/external/examples/hello_out_dir/hello_out_dir.out_dir': File exists

```

I couldn't reproduce this on my local machine. So I believe this is a CI issue.

FYI @philwo @fweikert

**Comment by meteorcloudy** [comment]
Not failing anymore

**Comment by meteorcloudy** [comment]
Happening again at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/596#d492de0e-a52c-4237-9bac-6b916a095be7
Not sure why `mkdir` failed with `File exists`,
/cc @damienmg Do you have any idea on this? Can we clean up the directory before executing `mkdir`?

**Comment by damienmg** [comment]
I think the code in rule_rust for outdir is wrong. The answer is just using
a treeartifact. I'll try to send a small pr later today.

**Comment by damienmg** [comment]
Should be fixed now :)

**Comment by meteorcloudy** [comment]
Thank you so much!
