### ISSUE TITLE
Sign Bazel releases with SHA256 or better

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#38]
A user reported that Bazel's release files are signed only with SHA1. I can confirm that this is indeed the case:

philwo@philwo:~/Downloads$ gpg --list-packets < bazel-0.4.0-installer-linux-x86_64.sh.sig 
:signature packet: algo 1, keyid 3D5919B448457EE0
	version 4, created 1478109806, md5len 0, sigclass 0x00
	digest algo 2, begin of digest c9 0b
	hashed subpkt 2 len 4 (sig created 2016-11-02)
	subpkt 16 len 8 (issuer key ID 3D5919B448457EE0)
	data: [4095 bits]

"digest algo 2" means SHA1.

This is probably as simple as modifying the ~/.gnupg/gpg.conf on whatever machine is used to create the signatures for the files - e.g. see https://debian-administration.org/users/dkg/weblog/48 or Ubuntu's checklist here https://wiki.ubuntu.com/SecurityTeam/GPGMigration.

**Comment by laszlocsomor** [comment]
Philipp, what do you think is the priority for this bug?

**Comment by damienmg** [comment]
IIRC this was fixed by @meteorcloudy and should be fixed at head. Side-note: that logic is done in Bazel itself so is not in that repository

**Comment by laszlocsomor** [comment]
Oh cool, thanks Damien!
