### ISSUE TITLE
Please re-enable rules_python

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/continuous-integration#382]
rules_python is green as of [build 151](https://buildkite.com/bazel/rules-python-python/builds/151). Please re-enable it on the Bazel w/ Downstream Projects pipeline.

I expect we may soon go temporarily red with Bazel 0.20 due to [rules_python #105](https://github.com/bazelbuild/rules_python/issues/105), but I aim to fix that imminently.

Thanks for keeping the pipeline green!

**Comment by meteorcloudy** [comment]
Done in https://github.com/bazelbuild/continuous-integration/commit/984cc94be173312c217fb62a15eea7c4c8a6835e

**Comment by meteorcloudy** [comment]
@brandjon Thanks for the fix! I'll re-enable it now. I'm not aware of any other incompatible flags.

**Comment by meteorcloudy** [comment]
Rerunning at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/600
