### ISSUE TITLE
Add kythe.io job

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#4]

**Comment by damienmg** [comment]
http://www.kythe.io/contributing for how to run kythe

Runs on Linux and OS X

problems:
  - add missing dependencies to the machines
  - tools/modules/configure.sh runs bazel so it's incompatible with the current way we create job

@schroederc fyi

**Comment by damienmg** [comment]
tools/modules/configure.sh is pulling llvm and clang sources... but also requires binaries, why @shahms?

**Comment by shahms** [comment]
We depend on the clang AST for the C++ indexer (and hence need the sources) and also need a compiler.  @zrlk may know more.

**Comment by zrlk** [comment]
To which binaries are you referring? We use Clang to build our code and require some version of it to be available.

**Comment by damienmg** [comment]
I need to `apt-get install clang` to build kythe, then kythe download clang source and build them...

**Comment by zrlk** [comment]
We build LLVM and Clang libraries for indexing near HEAD, but we rely on a versioned copy of the compiler--that we expect most developers to already have installed--to do the work.

**Comment by damienmg** [comment]
Another issue with kythe: it's more than the biggest job we have on ci (tensorflow) but the refactor I am doing will also take care of that (as well as handling the configure.sh issue). It will take some weeks though.

**Comment by damienmg** [comment]
Ok so the work on ci.bazel.io is done, we just need the modification to kythe for not needing to run bazel inside an external script then we can start adding the needed depedencies on the slave and add kythe.

**Comment by philwo** [comment]
Closing, as I'm currently not planning on adding more projects to our CI until we're in a more stable state.

**Comment by achew22** [comment]
@philwo, would it be possible to reopen this and add Kythe to the Bazel test suite? It might help prevent issues like https://github.com/bazelbuild/bazel/issues/8226 and would help provide coverage over some of the more exotic Bazel APIs

**Comment by philwo** [comment]
Yep, @lberki also pinged me about this. It would be best to file a new issue with our "Adding a project to Bazel CI" template. If someone from the Kythe team could do it, this would be perfect.

**Comment by fweikert** [comment]
Yeah, please file a request via this link: https://github.com/bazelbuild/continuous-integration/issues/new?template=adding-your-project-to-bazel-ci.md&title=Request+to+add+new+project+%5BPROJECT_NAME%5D&labels=new-project
