### ISSUE TITLE
Windows reimaging is totally flaky

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#40]
See bazelbuild/bazel#2229, some image do not have VC++ configured correctly and sometime they just cannot get access to the network, restarting them just refuse to reinit because it fails to create C:\bazel_ci because it already exists.

**Comment by laszlocsomor** [comment]
Thanks for implementing https://bazel-review.googlesource.com/#/c/7811/.
I'll add more logging to the script.

**Comment by laszlocsomor** [comment]
I'll downgrade this to P2, we can't work on this now.

**Comment by damienmg** [comment]
Because we have no bandwidth doesn't meant it is not important. Although this specific issue as been less frequent recently and with my change only a reboot is needed 90% of the time so p2 seems fine in that respect.
