### ISSUE TITLE
Tests / targets that should fail are passing due to cached results

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/continuous-integration#401]
Hi folks,
I noticed over the weekend that the travis CI build for rules_docker was failing (e.g., https://travis-ci.org/bazelbuild/rules_docker/builds/462618167), yet the BuildKite CI was passing.
This morning I fixed travis CI by updating the pins to several repos (https://github.com/bazelbuild/rules_docker/pull/592).

To repro, I created this PR: https://github.com/bazelbuild/rules_docker/pull/593. Note the BuildKite CI passed (https://buildkite.com/bazel/rules-docker-docker/builds/743) but the travis CI failed (https://travis-ci.org/bazelbuild/rules_docker/builds/462844001)
Also, note builds locally at master are failing, but the same builds on BuildKite CI pass without problems. 

I'm almost sure the builds are hitting remote cached results for when the builds were passing. Probably this is due to a change in Bazel version (probably changed to Bazel 0.20.0 in the last few days). However, it seems like the bazel version is _not_ part of the key, so while the build should fail with 0.20.0, its just getting cached results from the last run with 0.19.0. 

A possible fix (for this specific kind of breakage) is that maybe the bazel version should be part of the action key?

fyi @buchgr @ola-rozenfeld  @bergsieker

**Comment by nlopezgi** [comment]
Correction, I just noticed BuildKite CI is still running with Bazel 0.19.0, so that might be why my builds are still passing there but not on Travis CI or local.

**Comment by ola-rozenfeld** [comment]
No, Bazel version should most definitely not be part of the action key. That's the whole point of hermetic actions. If the Bazel version affects the test outcome without actually changing any of the inputs or command, this is something that should be debugged and fixed.
