### ISSUE TITLE
Bazel version should be configurable via presubmit settings.

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#403]
We should stop shipping Bazel binaries with our worker images. Instead, it would be nice if users could specify in their presubmit settings which binary they want to use (e.g. "latest", "latest-1", "0.20.0", "nightly").

**Comment by philwo** [comment]
That would be awesome and users have asked for this feature a lot of times! You'd make them really happy. :)

My idea how to implement this, would be to add the version selection logic to https://github.com/philwo/bazelisk, then install that (or just download on demand) on the VMs as the `bazel` binary and somehow integrate the selection logic nicely into our CI scripts and configs.

**Comment by fweikert** [comment]
https://github.com/bazelbuild/continuous-integration/pull/464 implemented this feature. Now that we're running Bazelisk on all CI workers we can consider this issue fixed.
