### ISSUE TITLE
Windows code review vetting of bazel-tests fails systematically

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#43]
See http://ci.bazel.io/job/Gerrit-bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/247/console

Interesting part is
```
c:\jenkins\workspace\Gerrit-bazel-tests\BAZEL_VERSION\latest\PLATFORM_NAME\windows-x86_64>c:\bazel_ci\installs\latest\bazel.exe --bazelrc=c:\jenkins\workspace\Gerrit-bazel-tests\BAZEL_VERSION\latest\PLATFORM_NAME\windows-x86_64\.bazelrc test //src/test/java/... + //src/test/shell/bazel:bazel_windows_example_test 
ERROR: Skipping '+': Bad target pattern '+': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
____Loading package: src/test/java/com/google/devtools/build/docgen
ERROR: Skipping '+': Bad target pattern '+': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
```

/cc @meteorcloudy

**Comment by meteorcloudy** [comment]
Same issue here: https://github.com/bazelbuild/continuous-integration/issues/41
We can just remove `+` from `"WINDOWS_TESTS": " + ".join(windows_tests),`, but I don't think that will help the failing tests.

**Comment by meteorcloudy** [comment]
Looks like Bazel tries to create file under `C:/Windows/Temp/_bazel_SYSTEM`, is that a problem, does Bazel have admin right?

**Comment by damienmg** [comment]
Oops sorry for the duplicate. replacing the + with just space should be enough. Why have the + in the first place?

**Comment by meteorcloudy** [comment]
Oh, that's my mistake, originally we do a `bazel query` first, but that doesn't work in batch, and I forgot to remove `+`.

**Comment by damienmg** [comment]
Woot why does Bazel tries tot create a file under C:/Windows/Temp/_bazel_SYSTEM??? The user is not SYSTEM AFAICT.

**Comment by damienmg** [comment]
Why does that work on bazel-tests but not on Gerrit-bazel-tests?

**Comment by meteorcloudy** [comment]
Look at the GetOutputRoot function here:
https://github.com/bazelbuild/bazel/blob/2354dc06300e29321c770479b034d056dc87f367/src/main/cpp/blaze_util_windows.cc#L292

Maybe one of "TMPDIR", "TEMPDIR", "TMP", "TEMP" is set to C:/Windows/Temp ?

**Comment by meteorcloudy** [comment]
It happened on Dec 8 for the first time:
http://ci.bazel.io/job/Gerrit-bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/228/console

Did we ever reimage the slaves at that time?

**Comment by damienmg** [comment]
Possible, we reimaged all the slaves after that though.

**Comment by damienmg** [comment]
I know how the GetOutputRoot works but the question why the output_root last segment is called `_bazel_SYSTEM`?

Maybe we should force set TMPDIR at the beginning of github jobs for Windows

**Comment by damienmg** [comment]
Ok during my sheriff run, calm week, I did some investigation and found what was wrong: there is a "$" sign in the output base path:

```
FAIL: //src/test/java/com/google/devtools/build/android/ziputils:ziputils-tests (see C:/windows/TEMP/_bazel_SYSTEM/m$HCUGyl/execroot/windows-x86_64/bazel-out/local-fastbuild/testlogs/src/test/java/com/google/devtools/build/android/ziputils/ziputils-tests/test.log)
____From Testing //src/test/java/com/google/devtools/build/android/ziputils:ziputils-tests:
==================== Test output for //src/test/java/com/google/devtools/build/android/ziputils:ziputils-tests:
/usr/bin/bash: C:/Windows/Temp/_bazel_SYSTEM/m/execroot/windows-x86_64/bazel-out/local-fastbuild/bin/src/test/java/com/google/devtools/build/android/ziputils/ziputils-tests: No such file or directory
================================================================================
```

We can see that "C:/windows/TEMP/_bazel_SYSTEM/m$HCUGyl" is used as output base but the test tries to execute using "C:/Windows/Temp/_bazel_SYSTEM/m" because the dollar sign get interpreted.

**Comment by damienmg** [comment]
This is a genuine bug in Bazel, closing this issue in favour of bazelbuild/bazel#2306
