### ISSUE TITLE
Enable downstream projects on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#454]
Projects to be enabled on Windows:

Belongs to Bazel team:
- [ ] Android Studio Plugin
- [ ] Android Testing
- [X] Bazel
- [ ] Bazel Bench
- [ ] Bazel Codelabs
- [ ] Bazel Remote Cache
- [X] Bazel integration testing
- [X] Bazel skylib
- [X] Bazel toolchains (not applicable)
- [X] Bazel watcher
- [X] Bazelisk
- [ ] Buildfarm
- [X] Buildtools
- [ ] CLion Plugin
- [ ] IntelliJ Plugin
- [ ] IntelliJ Plugin Aspect
- [X] Skydoc

Bazel rules:
- [X] rules_android
- [ ] rules_appengine
- [X] rules_apple (not applicable)
- [X] rules_cc
- [ ] rules_closure
- [ ] rules_d
- [ ] rules_docker
- [X] rules_foreign_cc
- [X] rules_go
- [ ] rules_groovy
- [ ] rules_gwt
- [ ] rules_jsonnet
- [X] rules_jvm_external
- [ ] rules_jvm_external - examples
- [ ] rules_k8s
- [ ] rules_kotlin
- [X] rules_nodejs
- [ ] rules_perl
- [ ] rules_python
- [ ] rules_rust
- [X] rules_sass
- [ ] rules_scala
- [ ] rules_swift
- [X] rules_typescript
- [ ] rules_webtesting

Belongs to other teams:
- [ ] Cartographer
- [ ] Cloud Robotics Core
- [ ] Envoy
- [ ] Flogger
- [ ] Gerrit
- [ ] Google Logging
- [ ] Kythe
- [X] Protobuf
- [ ] Subpar
- [X] TensorFlow
- [X] Tulsi (not applicable)
- [X] re2
- [ ] upb

**Comment by philwo** [comment]
@meteorcloudy I updated the list of projects and added all that were missing :)

**Comment by meteorcloudy** [comment]
Thank you so much!!!!

**Comment by meteorcloudy** [comment]
This is on downstream projects owners' responsibility now.
