### ISSUE TITLE
Incompatible flags pipeline misses lots of jobs

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/continuous-integration#475]
https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/96

The idea of the pipeline is to test every project with every flag.

There's a line on the page that lists 18 flags (search for "Build and test with the following incompatible flags"). However, only the first 10 flags appear in the reruns. The last 8 are skipped.

Example: search for "--incompatible_disallow_dict_plus" and you'll see matches at the end of the page. Search for "incompatible_disallow_load_labels_to_cross_package_boundaries" and you don't see the reruns.

Is it because there are too many jobs?

**Comment by meteorcloudy** [comment]
Looks like it's caused by https://github.com/bazelbuild/continuous-integration/commit/c3042cc06a4e0a83f0f6c91268c401ab8d7a9426#diff-9e9fe8cd1e3d245f56e4c1052c89faa2

**Comment by meteorcloudy** [comment]
A workaround for this is to trigger a build with `INCOMPATIBLE_FLAGS` environment variable set to exactly the flags you want to test.

**Comment by philwo** [comment]
Can we instead use the `--migrate` feature that Laurent contributed to Bazelisk yesterday maybe? I think bumping up the job limit will not help in the long-term as we get more projects, flags and platforms to test on...

**Comment by meteorcloudy** [comment]
Wow, I didn't know about this, but it looks like very cool and will save a lot of jobs for us!

**Comment by meteorcloudy** [comment]
@philwo Is Bazelisk deployed on CI machines?

**Comment by meteorcloudy** [comment]
I'd like to help adapting the incompatible flags pipeline to Bazelisk!

**Comment by philwo** [comment]
@meteorcloudy Yes, but not the Go version yet! @fweikert is working on it. :)

**Comment by meteorcloudy** [comment]
@philwo Cool, just ping me when it's done. I'll play with Bazelisk first, looks very very useful! Thanks for creating it!

**Comment by laurentlb** [comment]
`bazelisk --migrate` is great for rule owners, so that they know what they should fix.

The pipeline with custom flags (https://github.com/bazelbuild/continuous-integration/issues/475#issuecomment-463115839) is great for us, because we know which flags are ready to be flipped.

I would be happy if we drop the nightly run of the pipeline, and we let developers run the pipeline with the specific flags they're interested in. I have like 10 flags I care about, it would be enough for me to test them once a week.
Is there any time when it's fine to manually start a pipeline?

**Comment by meteorcloudy** [comment]
The main problem to manually start a pipeline is that it will consume most of CI resources and block presubmits at normal work time. 

@philwo Is it possible to limit the CI resource a pipeline can use?

**Comment by laurentlb** [comment]
If we don't have a fix soon, can I start a pipeline manually? (even if it's only at night, or only during the week-end)

**Comment by meteorcloudy** [comment]
@laurentlb Sure, you can do that!

**Comment by laurentlb** [comment]
Well, it looks like the button to start the pipeline has disappeared (cc @philwo).

**Comment by fweikert** [comment]
I gave "Build&Read" access to the sheriff team.

**Comment by laurentlb** [comment]
Obsolete
