### ISSUE TITLE
Schedule workers for regular reimaging

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#48]
The flakiness from the worker falling in bad shape is terrible, we should just reimage automatically slave.

Idea:
  - Reboot of all the machines every night when no build is running (rotate the reboot schedule so we have always slave online).
  - Reimage one worker per night (especially windows and when we have VM of mac, mac)

**Comment by philwo** [comment]
This is very important, but I'll close this one and will create individual actionable issues instead.
