### ISSUE TITLE
No space left on device for mac remote cache

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/continuous-integration#484]
We see this in the logs:
```
WARNING: Writing to Remote Cache:
500 Internal Server Error
open /var/lib/bazel-remote/upload438022801: no space left on device
```

https://buildkite.com/bazel/culprit-finder/builds/105#c5070dcd-2600-414d-9d80-50909fd2a6bd

**Comment by meisterT** [comment]
cc @fweikert

**Comment by philwo** [comment]
In theory, the bazel-remote cache server should clean up as necessary to stay under the set storage limit. It seems like at least one instance doesn't, though:

**Comment by philwo** [comment]
```
# Restart and read the log to make sure the service comes up fine.
[root@bazel-remote philwo]# systemctl restart bazel-remote.service ; journalctl -f -u bazel-remote.service

# Verify the used space again.
[root@bazel-remote philwo]# du -hs /var/lib/bazel-remote*
236G	/var/lib/bazel-remote
```

That seems to have worked for now.

**Comment by philwo** [comment]
I also created a user for @fweikert on the server and sent him the SSH instructions so that he can also look into this in case it happens again.

**Comment by meisterT** [comment]
I was investigating why in
https://buildkite.com/bazel/google-bazel-presubmit/builds/15703#_
the build on Mac was so much slower than on the other platforms and found the same thing happening again:
```
...
open /var/lib/bazel-remote/upload080958687: no space left on device
open /var/lib/bazel-remote/upload111376258: no space left on device
open /var/lib/bazel-remote/upload248065005: no space left on device
open /var/lib/bazel-remote/upload464955705: no space left on device
open /var/lib/bazel-remote/upload302240638: no space left on device
...
```

(I cannot reopen this issue)

**Comment by philwo** [comment]
Was this fixed? It seems so, I just checked the server and it was 177G of free space.

If someone touches the server to fix this, please update this bug, so others know about it.

**Comment by philwo** [comment]
I will update system packages and reboot the server, just in case:

```bash
pacman -Syu
reboot
```

**Comment by philwo** [comment]
I wrote a little script that restarts the cache servers when the free space is getting too low:

```bash
#!/bin/bash

set -euxo pipefail

while true; do
  USED_DISK_PERCENT=$(df --output=pcent / | tail +2 | cut -d'%' -f1 | tr -d ' ')

  if [[ $USED_DISK_PERCENT -ge 90 ]]; then
    echo "Almost out of space on disk, restarting cache servers."
    systemctl restart bazel-remote.service
    systemctl restart bazel-remote-trusted.service
  fi

  sleep 300
done
```

It's in `/usr/local/bin/maybe-restart-cache` and I installed it as a simple systemd service to keep it running:

```bash
cat > /etc/systemd/system/maybe-restart-cache.service <<'EOF'
[Unit]
Description=Workaround for https://github.com/bazelbuild/continuous-integration/issues/484.
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/maybe-restart-cache
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl enable maybe-restart-cache.service
systemctl start maybe-restart-cache.service
journalctl -f -u maybe-restart-cache.service
```

**Comment by buchgr** [comment]
It's quite weird that it seems to work for one instance but not for the other. In order to properly debug this we'll need to disable the script that restarts the server and look at the state of the server then.

**Comment by philwo** [comment]
I wasn't able to repro this anymore. Closing for now.
