### ISSUE TITLE
CI, macos: projects are failing with "$HOME is not defined"

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#485]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/816#_
https://buildkite.com/bazel/bazel-skylib/builds/295#9dd233c5-8475-44b8-8d73-f4a0927d5fab
https://buildkite.com/bazel/tulsi-bazel-darwin/builds/41

@fweikert Did something change to our mac slaves recently?

**Comment by fweikert** [comment]
I installed Bazelisk yesterday.

**Comment by fweikert** [comment]
Confirmed: the error comes from UserCacheDir() called by Bazelisk. I'll set $HOME for now to work around this issue.

**Comment by meteorcloudy** [comment]
Thank you!

**Comment by fweikert** [comment]
Ok, that's weird: The variable is actually set, according to printenv:

HOME=/Users/ci

**Comment by fweikert** [comment]
This is a bug in the Go version of Bazelisk. I'll install Bazel instead so that I have more time to investigate.
Btw, the Ubuntu Skylib failures in https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/816 are a bug in the Python version of Bazelisk :(

**Comment by fweikert** [comment]
I filed https://github.com/bazelbuild/continuous-integration/issues/488 to track the Linux issue.
I'm currently installing Bazel on non-busy iMacs.

**Comment by fweikert** [comment]
I forgot to update this issue, but all iMacs have been running pure Bazel for some time now.

**Comment by philwo** [comment]
> This is a bug in the Go version of Bazelisk.

Was this a bug in Bazelisk or in our bazelci.py script?

**Comment by meteorcloudy** [comment]
I think the problem is Bazelisk depends on `HOME` environment variable, but when running the test we clean up most environment variables including `HOME`.

**Comment by fweikert** [comment]
In the end it was a bug in the CI script. However, we should document Bazelisk’s reliance on certain environment variables since users might be surprised when running an integration test that invokes Bazel.

**Comment by philwo** [comment]
Good point, Florian. I agree.

We could also add logic to Bazelisk to detect running inside a Bazel integration test and e.g. use TEST_TMPDIR instead then, but I'm not sure if it's worth the added complexity...

**Comment by fweikert** [comment]
I deployed Bazelisk again, and it seems to work: https://buildkite.com/bazel/tulsi-bazel-darwin/builds/43
