### ISSUE TITLE
Add rules_proto to the CI

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/continuous-integration#486]
https://github.com/stackb/rules_proto is being used by rules_k8s.
It would be useful to test rules_proto separately on the CI.

cc @pcj

**Comment by pcj** [comment]
That would be great if this is possible.

**Comment by fweikert** [comment]
Sure, I'll create a Buildkite pipeline for you. Here's how the process works:

1. Please add a .bazelci/presubmit.yml file to your repository. 
  Example: https://github.com/bazelbuild/rules_typescript/blob/master/.bazelci/presubmit.yml
  Docs: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#configuring-a-pipeline

2. I'll send you further instructions on how to add a GitHub webhook that triggers new builds for incoming PRs.

**Comment by fweikert** [comment]
I created https://buildkite.com/bazel/rules-proto (not much to see yet) and sent you an invite to join Buildkite.
I'm going to send you the webhook instructions via email.

**Comment by laurentlb** [comment]
If you can fix issue with incompatible flags first, that'd be great.
(https://github.com/stackb/rules_proto/issues/14)

We want to make sure we never break you. This means, you're expect to fix issues in advance. We'll provide better tooling in the future. For now, you can try for example [bazelisk](https://github.com/philwo/bazelisk/).

**Comment by fweikert** [comment]
@pcj I tried to send you the instructions via email, but it bounced.

**Comment by pcj** [comment]
Can we pick this back up again?  I've got rules_proto compatible with 0.24.1 now and working to get https://github.com/stackb/rules_proto/issues/14 fixed.  Having the buildkite pipeline available will help speed this process as my travis CI launches ~75 different jobs and takes several hours to run (mostly recompiling protobuf itself).

@fweikert pcj127@gmail.com should work, thanks!

**Comment by fweikert** [comment]
I've sent you an email :)

**Comment by pcj** [comment]
Ok I'm up and running!  This is awesome :)

Any recommendation on this error:
```
ERROR: /home/bazel/.cache/bazel/_bazel_bazel/f2549f537061d174521cc2ed50491b17/external/build_stack_rules_proto/java/BUILD.bazel:17:1: no such package '@com_google_guava_guava//jar': Traceback (most recent call last):
  | File "/home/bazel/.cache/bazel/_bazel_bazel/f2549f537061d174521cc2ed50491b17/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 280
  | _maven_artifact_impl(ctx, "jar", _maven_jar_build_file_te...)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/f2549f537061d174521cc2ed50491b17/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 230, in _maven_artifact_impl
  | _check_dependencies(ctx)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/f2549f537061d174521cc2ed50491b17/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 56, in _check_dependencies
  | fail(("%s requires %s as a dependency...)))
  | com_google_guava_guava requires mvn as a dependency. Please check your PATH. and referenced by '@build_stack_rules_proto//java:proto_deps'
```

**Comment by pcj** [comment]
Second question:  I have a rule like this:

```
go_binary(
    name = "protoc-gen-scala",
    data = [
        ":compiler_plugin_deploy.jar",
        "@bazel_tools//tools/jdk:jre",
    ],
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
```

What's the correct jdk label to use for bazelci remote execution?

**Comment by pcj** [comment]
Third question: how to set environment variables for a task? `CC=clang`

``
ERROR: rules_swift uses Bazel's CROSSTOOL to link, but Swift requires that the driver used is clang. Please set `CC=clang` in your environment before invoking Bazel.
```

**Comment by pcj** [comment]
Fourth question: how to resolve this with `--all_incompatible_changes`:

```

ERROR: /home/bazel/.cache/bazel/_bazel_bazel/14ea55d860202089ca472a3c2933b148/external/io_bazel_rules_go/BUILD.bazel:62:1: in go_context_data rule @io_bazel_rules_go//:go_context_data:
--
  | Traceback (most recent call last):
  | File "/home/bazel/.cache/bazel/_bazel_bazel/14ea55d860202089ca472a3c2933b148/external/io_bazel_rules_go/BUILD.bazel", line 62
  | go_context_data(name = 'go_context_data')
  | File "/home/bazel/.cache/bazel/_bazel_bazel/14ea55d860202089ca472a3c2933b148/external/io_bazel_rules_go/go/private/context.bzl", line 418, in _go_context_data_impl
  | find_cpp_toolchain(ctx)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/14ea55d860202089ca472a3c2933b148/external/bazel_tools/tools/cpp/toolchain_utils.bzl", line 39, in find_cpp_toolchain
  | ctx.toolchains["@bazel_tools//tools/cpp:toolchain_type"]
  | In go_context_data rule @io_bazel_rules_go//:go_context_data, toolchain type @bazel_tools//tools/cpp:toolchain_type was requested but only types [] are configured
```

**Comment by fweikert** [comment]
Not sure about your other questions, but you can set env variables like this:

https://github.com/bazelbuild/rules_swift/blob/master/.bazelci/presubmit.yml#L26

**Comment by pcj** [comment]
@fweikert There is no indication in a PR that the bazelci jobs are running.  So I need to add the bot user as a member of the repo/organization?  Did I miss the configuration for this somehow?  Thanks.

**Comment by pcj** [comment]
Also, what is the correct way to render a Build Status link badge?  The image url for other bazel ci repos is an svg with a hash, but how do I determine that hash?

**Comment by fweikert** [comment]
1. I've changed the pipeline settings to run on all PRs.
2. The badge:

[![Build Status](https://badge.buildkite.com/5980cc1d55f96e721bd9a7bd5dc1e40a096a7c30bc13117910.svg?branch=master)](https://buildkite.com/bazel/rules-proto)

Do you have a Buildkite account? Otherwise I'll create one for you so that you can access the pipeline settings.

**Comment by fweikert** [comment]
Slightly related: You can set the "name" field for tasks in https://github.com/stackb/rules_proto/blob/master/.bazelci/presubmit.yml in order to set a display name (https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#specifying-a-display-name).

This should make finding the right job in the Buildkite UI much easier.

**Comment by pcj** [comment]
Thanks @fweikert No I don't have a buildkite account.

**Comment by pcj** [comment]
@philwo The link provided is a list of Authorized OAuth Apps, apps that I've already clicked "OK" for the github oauth flow.  Buildkite isn't on that list for me, and there isn't a way to install apps via those screens.

If I follow instructions from https://buildkite.com/docs/integrations/github-enterprise, I can indeed create the app in **Step 1**, but then that generates new ClientID/ClientSecret.  In my buildkite UI, I don't have permissions to https://buildkite.com/docs/integrations/github-enterprise#step-2-update-your-buildkite-organization-settings.

**Comment by philwo** [comment]
Thanks for checking! I'll reach out to Buildkite and/or GitHub support to figure this out.

I noticed that we have the same problem with other repositories that are not in the bazelbuild organization, like Tensorflow or protobuf and I'd like to get this sorted out quickly.

**Comment by philwo** [comment]
One last idea: Could you check https://buildkite.com/user/connected-apps and see if you can connect to GitHub from there? :) Maybe this will grant it the permissions it needs.

**Comment by philwo** [comment]
I finally figured it out and will add this to our setup instructions later:

Support level 0 (scheduled builds only): If we only want to test against an external public repository on a scheduled basis and/or as part of downstream tests, no setup is required on the side of the repository.

Support level 1 (postsubmit builds): If we want to test every commit of a repository as soon as it was pushed to the master branch, a repository admin needs to setup a webhook that pings Buildkite for every commit. @fweikert or me will provide the webhook URL.

Support level 2 (all features, e.g. pull request presubmit checks and commit status integration): If the repository owners want to use all of Bazel CI's features, like testing Pull Requests and seeing the results of CI for each commit in the master branch in the GitHub UI, one of the following has to be done:
- A repository admin adds our robot account https://github.com/bazel-io to the repository collaborators with write access (unfortunately write access is required to be able to send commit statuses) or
- someone who already has write access to the repository [connects their Buildkite account](https://buildkite.com/user/connected-apps) to GitHub and grants the required permissions.

**Comment by pcj** [comment]
OK, I changed the permissions to write for @bazel-io.

---

I then clicked the link for connected apps:


![Screenshot from 2019-05-09 07-59-38](https://user-images.githubusercontent.com/50580/57462992-2883ba00-7237-11e9-99a7-2f3d86a9d284.png)

---

And then approved it:

![Screenshot from 2019-05-09 08-00-27](https://user-images.githubusercontent.com/50580/57463073-549f3b00-7237-11e9-90e2-a6a0f1e29ea9.png)

Let me try a PR and see if that fixes it!

**Comment by pcj** [comment]
Hooray, it worked!  Should we close this issue?

![Screenshot from 2019-05-09 08-54-12](https://user-images.githubusercontent.com/50580/57463499-25d59480-7238-11e9-98ef-53cb0365d0de.png)

**Comment by philwo** [comment]
Yay! :) Glad that it all worked out. I'll close this - let me know if you encounter any issues in the future.

**Comment by fweikert** [comment]
Nice, thank you Philipp!

**Comment by fweikert** [comment]
Btw, we currently use the "Create a status for each job" setting. We can disable that option if you want only a single check to be displayed in GitHub.

**Comment by pcj** [comment]
@fweikert I like the current setting "Create a status for each job".
