### ISSUE TITLE
Bazelisk-on-Linux fails with "OSError: [Errno 26] Text file busy

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#487]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/816#af9ef607-6a94-465e-9e58-ca1c9ee9689f

https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/af9ef607-6a94-465e-9e58-ca1c9ee9689f/tests/analysis_test_e2e_test/attempt_1.log

https://github.com/philwo/bazelisk/commit/3feb38016821c28536ea6d3f9c89dc2f6f1cdfda#diff-772814c8f0d6cc5266c8a880a5468ed0

**Comment by philwo** [comment]
What was the fix?
