### ISSUE TITLE
startup-docker.sh fails

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#492]
Feb 22 15:41:50 bk-docker-0fcq startup-script: INFO startup-script: 7dd94051f25b: Pull complete
Feb 22 15:41:50 bk-docker-0fcq startup-script: INFO startup-script: Digest: <redacted>
Feb 22 15:41:50 bk-docker-0fcq startup-script: INFO startup-script: Status: Downloaded newer image for gcr.io/bazel-untrusted/ubuntu1404:java8
Feb 22 15:41:50 bk-docker-0fcq startup-script: INFO startup-script: + sudo -H -u buildkite-agent gcloud auth configure-docker --quiet
Feb 22 15:41:50 bk-docker-0fcq startup-script: INFO startup-script: cannot create user data directory: /var/lib/buildkite-agent/snap/google-cloud-sdk/70: Permission denied
Feb 22 15:41:50 bk-docker-0fcq startup-script: INFO startup-script: Return code 1.
Feb 22 15:41:50 bk-docker-0fcq startup-script: INFO Finished running startup scripts.
Feb 22 15:41:50 bk-docker-0fcq kernel: [  252.892479] audit: type=1400 audit(1550850110.338:27): apparmor="DENIED" operation="open" profile="/usr/lib/snapd/snap-confine" name="/var/lib/buildkite-agent/" pid=32337 comm="snap-confine" requested_mask="r" denied_mask="r" fsuid=999 ouid=999
Feb 22 15:41:50 bk-docker-0fcq systemd[1]: Started Google Compute Engine Startup Scripts.
Feb 22 15:41:50 bk-docker-0fcq systemd[1]: Startup finished in 4.303s (kernel) + 4min 7.708s (userspace) = 4min 12.012s.
Feb 22 15:52:49 bk-docker-0fcq systemd[1]: Starting Cleanup of Temporary Directories...
Feb 22 15:52:49 bk-docker-0fcq systemd[1]: Started Cleanup of Temporary Directories.

**Comment by fweikert** [comment]
Deleting the existing VMs and creating new ones did the trick...

**Comment by philwo** [comment]
I think this is fixed.
