### ISSUE TITLE
buildifier support for WORKSPACE files?

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#507]
Looking at the [buildifier support](https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#running-buildifier-on-ci), it says it runs on BUILD, BUILD.bazel and .bzl, what about WORKSPACE files since those also are supported by buildifier?

**Comment by fweikert** [comment]
I pushed new Docker images which contain the fix to this issue.
