### ISSUE TITLE
Deploy latest Bazelisk on CI

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#525]
We need to upgrade Bazelisk to get fixes from https://github.com/philwo/bazelisk/pull/36

**Comment by fweikert** [comment]
I'll do that once I'm in the office, and I'll also write some documentation so that others can do it.

**Comment by fweikert** [comment]
TODO:
1. Merge #527 
2. Create and deploy new Docker images to update Linux workers
3. Run create_images + create_instances to deploy Bazelisk 0.0.2 to Windows workers
4. Update Macs manually (at least we have a Homebrew formula)

**Comment by fweikert** [comment]
Windows images have been deployed.
