### ISSUE TITLE
Add PR hook for rules_jsonnet

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/continuous-integration#53]
Currently, it seems that bazelbuild/rules_jsonnet is not being tested with Jenkins.

**Comment by damienmg** [comment]
@davidzchen Can you send a gerrit code review for it?

**Comment by davidzchen** [comment]
Sounds good. Though before I do so, I would like to make a change to `rules_jsonnet` to put examples and docs into sub-workspaces, similar to what we are doing with other rules repos, such as `rules_rust`. However, it looks like I first need to fix `jsonnet.bzl` because currently, I get an error when I try to build the examples when they are in their own workspace.

**Comment by davidzchen** [comment]
Sent the following review: https://bazel-review.googlesource.com/10310
