### ISSUE TITLE
Add tests on FreeBSD

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#54]
bazel-tests does not run on FreeBSD. bazel-tests is the only wait to get pre-submit so it would be good to at least run the bootstrap test on FreeBSD.

**Comment by damienmg** [comment]
(side-note: not urgent, just filing for tracking)

**Comment by cgrushko** [comment]
Please reconsider urgency - this already caused a rollback, which hurts productivity.

**Comment by damienmg** [comment]
We have at least 10 very urgent request, we cannot do all of them, if you are hurt by hit, feel free to consider taking the task.

**Comment by aehlig** [comment]
Given that jenkins (now?) supports "configure" commands that change the source, we can run at least `//src/test/shell/integration/...` on FreeBSD, simply by adding the following "configure" command to redo the `#!`-fixes that otherwise are down by the ports infrastructure.

```
find -E . -type f -iregex '.*(sh|txt|_stub|stub_.*|bazel|get_workspace_status|protobuf_support|_so)' \
  -exec sed -i '' \
  -e '1s|^\#![[:space:]]*/bin/bash\([[:space:]]\)|\#!/usr/local/bin/bash\1|' \
  -e '1s|^\#![[:space:]]*/bin/bash$|\#!/usr/local/bin/bash|' \
  -e '1s|^\#![[:space:]]*/usr/bin/env bash\([[:space:]]\)|\#!/usr/local/bin/bash\1|' \
  -e '1s|^\#![[:space:]]*/usr/bin/env bash$|\#!/usr/local/bin/bash|' \
  {} +
```

Verified that this passes successfully on current head.

**Comment by philwo** [comment]
@aehlig Do you know what's blocking us from just running all tests (or at least all that are not Linux-specific) on FreeBSD?

Or, asked in a different way: Would you like to run more tests on FreeBSD or do you think the current situation is good enough and we can close this?

**Comment by buchgr** [comment]
Seems like we are dropping FreeBSD from our CI. So I think this can be closed.

**Comment by philwo** [comment]
Yeah, we need GCE images for FreeBSD in order to test Bazel on it. Unfortunately the currently available ones don't work (they print kernel stack traces on boot and somehow their SSH is messed up so that I can't login via `gcloud compute ssh`). :(
