### ISSUE TITLE
Re-enable Gerrit@Java9 toolchain CI job

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#559]
Due to Bazel issue: [1] https://github.com/bazelbuild/bazel/issues/7672 Java9 toolchain is broken and Gerrit job on Java9 was disabled, as pointed out in: https://github.com/bazelbuild/bazel/issues/7219#issuecomment-470420496.

Please re-enable Gerrit job on Java9 when Java9 toolchain is fixed again upstream.

Alternatively, if Java9 toolchain is discontinued and removed, Gerrit job on Java9 can be removed as well.

**Comment by hlopko** [comment]
cc @vladmos

**Comment by davido** [comment]
Thanks.
