### ISSUE TITLE
FR: Buildkite pipeline for multi-platform releases

### ISSUE THREAD

**Issue by iirina** [bazelbuild/continuous-integration#561]
We recently moved the Java tools out of the bazel binary (see https://github.com/bazelbuild/bazel/issues/6316), thus the Java tools are now released separately. Because the Java tools embed pre-built C++ binaries, they have to be individually released for macos, linux and windows. A Buildkite pipeline that supports multi-platform releases is essential for the Java tools project.

**Comment by iirina** [comment]
cc: @fweikert

**Comment by fweikert** [comment]
This feature could be useful for Buildifier and Bazelisk, too.

**Comment by philwo** [comment]
This should already work, right?
