### ISSUE TITLE
Support "bazel: last_downstream_green"

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#583]
Users should be able to use the Bazel binary that was built at the most recent commit that passed the downstream pipeline.

AIs:
- Upload commit to GCS
- Modify Bazelisk to read the commit from GCS

Bazelci already passes the "bazel" field in the config to Bazelisk, hence we don't need to change anything here.

**Comment by danny-kuminov** [comment]
If possible, it would be very useful for us if you published the bazel binary built at the green commit as well as the commit itself. It would save us the effort to download the code and build bazel (and presumably you already have the binary, otherwise what did you test? :-) ).
Thank you!

**Comment by fweikert** [comment]
We already publish Bazel binaries on GCS. See https://github.com/philwo/bazelisk/blob/master/bazelisk.go#L238

**Comment by danny-kuminov** [comment]
I didn't know that, thank you for the pointer!

**Comment by fweikert** [comment]
We record the last green commit in the downstream pipeline here: https://storage.googleapis.com/bazel-untrusted-builds/last_green_commit/downstream_pipeline

**Comment by danny-kuminov** [comment]
Thank you!

**Comment by fweikert** [comment]
I have a pending PR to support this feature in Bazelisk: 

https://github.com/philwo/bazelisk/pull/45

**Comment by fweikert** [comment]
TODO:
- [] Create and deploy new Bazelisk version
- [] Update CI documentation

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/899#_
I think we should not generate `Try Update Last Green Downstream Commit` step if the branch is not master?

**Comment by fweikert** [comment]
True, let me send a fix.

**Comment by fweikert** [comment]
8/10 iMacs and all Linux workers should have picked up 0.0.4 by now.

**Comment by fweikert** [comment]
- Deployed new Windows images
