### ISSUE TITLE
Release buildtools for Windows as well

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#600]
Upstream bug: https://github.com/bazelbuild/buildtools/issues/375

**Comment by fweikert** [comment]
We now have a pipeline for building buildtools release binaries. It only handles macOS and Linux at the moment, but we can add another step to build on Windows, too.

**Comment by hlopko** [comment]
@vladmos @laurentlb to ping when buildtools are ready to be released on windows :)

**Comment by vladmos** [comment]
Windows binaries are available: https://github.com/bazelbuild/buildtools/releases/tag/0.25.1

Please let us know if there are any problems with them.
