### ISSUE TITLE
Build releases for bazelbuild/buildtools on Buildkite

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#607]

**Comment by philwo** [comment]
FYI @vladmos

**Comment by vladmos** [comment]
The commands are described here: https://github.com/bazelbuild/buildtools/issues/497#issuecomment-462524140

Eventually I'd like to set up a workflow to automatically build and upload the binaries to Github, but it would be convinient even if it only builds the artifacts (3 binaries for 3 platforms) and I need to upload them manually.

**Comment by philwo** [comment]
@fweikert Is setting up the pipeline for this, so you should be able to get binaries built on CI soon.

**Comment by fweikert** [comment]
I've set up a pipeline for Linux and macOS builds: https://buildkite.com/bazel-trusted/buildtools-binaries/builds/13

laurentlb and vladmos are maintainers of that pipeline.

**Comment by fweikert** [comment]
TODO's:
- Automate the entire release process (including handling of tags and release notes)
- Add Windows job

**Comment by vladmos** [comment]
Perhaps an ideal workflow may look like the following:

  1. I create and upload a tag
  2. Buildifier detects it, builds all binaries, drafts a release on Github and uploads all the binaries
  3. I manually edit the release notes and submit a release.

Currently uploading the binaries manually is the most error-prone step, I may accidentally upload old binaries or rename linux binaries to `.mac`

**Comment by fweikert** [comment]
We also need a Windows version of https://github.com/bazelbuild/buildtools/blob/master/status.sh

**Comment by vladmos** [comment]
https://github.com/bazelbuild/buildtools/pull/631

**Comment by vladmos** [comment]
The script is ready, compatible with both Python 2 and 3. Please use it for all platforms, I'll remove the old shell script once it's not used anymore.

**Comment by fweikert** [comment]
Update: Windows binaries can be built too (https://github.com/bazelbuild/continuous-integration/pull/654). However, the entire process still involves a lot of manual steps.

**Comment by vladmos** [comment]
Much fewer steps than before, thanks!

**Comment by philwo** [comment]
Closing, because this seems done.
