### ISSUE TITLE
Benchmark slave seems to run other jobs, too

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#62]
I just noticed that the ubuntu_14.04-x86_64-benchmark-1 slave seems to run other jobs as part of a push, too (see screenshot).

Is this intended? If not, how can we fix it?

![screenshot from 2017-03-27 15 23 52](https://cloud.githubusercontent.com/assets/504652/24358483/8b740120-1301-11e7-9bac-48d1ed8cd757.png)

**Comment by hermione521** [comment]
I noticed it. I remember @damienmg said we can't fix it..

**Comment by damienmg** [comment]
Yes because this is not actually a job but just a scheduling task and Jenkins doesnt allow to bind those task to certain machines :(

**Comment by philwo** [comment]
Oh, OK. In that case it probably won't hurt much either. (I guess scheduling tasks don't really require any CPU or local resources, because they just schedule and wait for stuff?)

**Comment by damienmg** [comment]
Yes. It's just annoying and surprising.
