### ISSUE TITLE
Windows failure due to incomplete download

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#621]
From https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/2620#75cf4495-1560-43f0-912c-b729dd5f48e3:

```
external/com_google_protobuf/_objs/protoc_lib/cpp_generator.obj: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed: Failed to delete output files after incomplete download. Cannot continue with local execution.: D:/b/bnoxkwnx/execroot/io_bazel/bazel-out/_tmp/action_outs/stdout-672-0 (Permission denied)
```

**Comment by meteorcloudy** [comment]
@philwo Looks like cleaning the remote cache caused (revealed) some problem for Windows. Should we disable remote cache for Windows for now?

**Comment by philwo** [comment]
Yes, let's disable it. :(

**Comment by katre** [comment]
Let me know when I can re-run the failing tests

**Comment by meteorcloudy** [comment]
It's already done

**Comment by katre** [comment]
Thanks!

**Comment by meteorcloudy** [comment]
Reopening because the underlying issue has not been resolved.
I can reproduce in my custom branch  https://buildkite.com/bazel/pcloudy-test/builds/41#5ba9dc79-0e2e-4175-a490-16457b610c3c

**Comment by philwo** [comment]
@meteorcloudy This is fixed, right?

**Comment by meteorcloudy** [comment]
Yes!
