### ISSUE TITLE
Distfile tests fail on unrelated changes for a single configuration

### ISSUE THREAD

**Issue by aragos** [bazelbuild/continuous-integration#624]
https://buildkite.com/bazel/google-bazel-presubmit/builds/18479#6e38bfb3-7ce3-4d38-8558-be6778d1c868

`** test_bootstrap **************************************************************
Building Bazel from scratch..../usr/lib/jvm/zulu-9-amd64/bin/jar cmf /tmp/bazel_x8Oqimeg/MANIFEST.MF /tmp/bazel_x8Oqimeg/libblaze.jar -C /tmp/bazel_x8Oqimeg/classes A.class -C /tmp/bazel_x8Oqimeg/classes AUTHORS -C /tmp/bazel_x8Oqimeg/classes AnnotatedClass.class -C /tmp/bazel_x8Oqimeg/classes Annotations$ParametersOnlyAnnotation.class -C /tmp/bazel_x8Oqimeg/classes Annotations$RuntimeInvisible.class -C /tmp/bazel_x8Oqimeg/classes Annotations$RuntimeVisible.class -C /tmp/bazel_x8Oqimeg/classes Annotations.class -C /tmp/bazel_x8Oqimeg/classes B.class -C /tmp/bazel_x8Oqimeg/classes LICENSE -C /tmp/bazel_x8Oqimeg/classes LICENSE-junit.txt -C /tmp/bazel_x8Oqimeg/classes LICENSE.txt -C /tmp/bazel_x8Oqimeg/classes NOTICE -C /tmp/bazel_x8Oqimeg/classes NestTest$P.class -C /tmp/bazel_x8Oqimeg/classes NestTest.class -C /tmp/bazel_x8Oqimeg/classes about.html -C /tmp/bazel_x8Oqimeg/classes android -C /tmp/bazel_x8Oqimeg/classes api_diff.proto -C /tmp/bazel_x8Oqimeg/classes autovalue -C /tmp/bazel_x8Oqimeg/classes blogspot -C /tmp/bazel_x8Oqimeg/classes build -C /tmp/bazel_x8Oqimeg/classes com -C /tmp/bazel_x8Oqimeg/classes deps.proto -C /tmp/bazel_x8Oqimeg/classes difflib -C /tmp/bazel_x8Oqimeg/classes io -C /tmp/bazel_x8Oqimeg/classes jacocoagent.jar -C /tmp/bazel_x8Oqimeg/classes javax -C /tmp/bazel_x8Oqimeg/classes jdk -C /tmp/bazel_x8Oqimeg/classes junit -C /tmp/bazel_x8Oqimeg/classes licenses -C /tmp/bazel_x8Oqimeg/classes lombok -C /tmp/bazel_x8Oqimeg/classes module-info.class -C /tmp/bazel_x8Oqimeg/classes module-info.java -C /tmp/bazel_x8Oqimeg/classes mozilla -C /tmp/bazel_x8Oqimeg/classes net -C /tmp/bazel_x8Oqimeg/classes org -C /tmp/bazel_x8Oqimeg/classes pom.xml -C /tmp/bazel_x8Oqimeg/classes proguard -C /tmp/bazel_x8Oqimeg/classes sun -C /tmp/bazel_x8Oqimeg/classes textfile.txt
java.lang.IllegalArgumentException
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:182)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:453)
        at java.base/jdk.internal.module.ModuleInfoExtender.toByteArray(ModuleInfoExtender.java:194)
        at java.base/jdk.internal.module.ModuleInfoExtender.write(ModuleInfoExtender.java:179)
        at jdk.jartool/sun.tools.jar.Main.extendedInfoBytes(Main.java:2137)
        at jdk.jartool/sun.tools.jar.Main.addExtendedModuleAttributes(Main.java:2068)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:294)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1670)`

**Comment by philwo** [comment]
No idea what's up with this. :(

Considering that JDK 9 has been EOL for quite some time and isn't used as the default JDK on any stable Ubuntu version (same for JDK 10), I've sent a change to disable testing on JDK 9 and 10.

If we want to investigate and fix this so that we can continue testing with these JDKs, I guess @iirina is the best point of contact.

**Comment by philwo** [comment]
"Fixed" by disabling testing on JDK 9 and 10.
