### ISSUE TITLE
Missing info about downstream breakages for a new incompatible flag

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/continuous-integration#631]
In yesterday's [bazelisk + incompatible change nightly](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/95), the flag `--incompatible_use_python_toolchains` is tested according to the logs of the builds, but it has no corresponding summary annotation telling me which projects failed the flag.

Is this because 0.25 was just released and the pipeline grabbed the list of flags in an inconsistent way? Does it have to do with the labels attached to the flag's [migration bug](https://github.com/bazelbuild/bazel/issues/7899)?

**Comment by philwo** [comment]
@meteorcloudy @fweikert Any idea?

**Comment by meteorcloudy** [comment]
The CI is somehow one step slower, the result is now in the latest run:
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/99

**Comment by philwo** [comment]
Is this still an issue?

**Comment by meteorcloudy** [comment]
I think it's fine to close it.
