### ISSUE TITLE
Request to add flogger to Bazel CI

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#632]
- I want to test flogger project on Bazel CI: [https://github.com/google/flogger]
- I confirm that the project has a `.bazelci/presubmit.yml` file.

# Instructions (you can delete this section from the issue)

Welcome to Bazel CI! We are thrilled that you want to test your project with Bazel.
Please follow these steps to make the on-boarding experience as smooth as possible:

1. Add the URL of your project's GitHub repository to the first line of this issue.
2. Add the name of your project to the issue title.
3. Please read the [introduction to Buildkite](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md) to learn about the basic concepts such as pipelines.
4. Create and commit your presubmit configuration in `<YOUR REPO>/.bazelci/presubmit.yml`. The configuration format is documented [here](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#configuring-a-pipeline), and you can find several an example [here](https://github.com/bazelbuild/rules_typescript/blob/master/.bazelci/presubmit.yml). No need to get it right on the first try - It's usually a good idea to start with a basic configuration, wait until the pipeline is set up, trigger a build and then iterate on the configuration.
5. The Bazel team will review this issue and create a pipeline on Buildkite.
6. The team will reach out to you and give you instructions on how to set up a GitHub webhook that triggers a CI build for incoming pull requests.

**Comment by davido** [comment]
@philwo @meteorcloudy Can you help to set up the Buildkite pipeline for flogger project? Thanks!

**Comment by fweikert** [comment]
Please add a pipeline configuration to your repo first (.bazelci/presubmit.yml, see the instructions from the issue template for more details).

**Comment by davido** [comment]
@fweikert This is not my repo.

@hanwen Can you or Edwin ping flogger project owners to help with setting up `.bazelci/presubmit.yml`? All we want is to avoid that flogger breakage went unnoticed after Bazel upgrade.

**Comment by philwo** [comment]
If the project itself is not interested in using Bazel CI, we can also check-in a config file into our CI repo. That way we can use it as a downstream test for Bazel, but then we're also responsible for sending them PRs to do migrations and fixes, I guess.

**Comment by davido** [comment]
@philwo Let us do it and use flogger as a downstream test for Bazel, and do the same as we are currently doing with Gerrit itself. This is crucial for Gerrit Code Review project, as we are using flogger (even though we are not building it from the source in our build tool chain).

I will take care of sending PRs to flogger project for adjusting their build tool chain for Bazel migrations and fixes.

**Comment by philwo** [comment]
I verified that `bazel test //...` works fine for Flogger on our Ubuntu 16.04 with Java 8 container. A few tests fail with Java 11 - not sure if Flogger wants to investigate that, or if Java 11 isn't supported anyway.

**Comment by philwo** [comment]
Pipeline is setup and green: https://buildkite.com/bazel/flogger/builds/1

I have added it to our downstream projects, too: https://github.com/bazelbuild/continuous-integration/commit/f3750fae2e7a8127791c9fc9b7758e077375dbd6

**Comment by davido** [comment]
Thanks @philwo, very much appreciated!

**Comment by davido** [comment]
@philwo Can this repository be also added to baselisk incompatible job so that a similar breakage could be reported, like for example: https://github.com/bazelbuild/bazel/issues/5816#issuecomment-494312395? Thanks!

**Comment by philwo** [comment]
@davido I think the Bazelisk pipeline runs all of the downstream projects, so it should be picked up in the next nightly run :) I'll check tomorrow that it actually did.

**Comment by davido** [comment]
@philwo How cool is that? ;-)
