### ISSUE TITLE
bazelci sensitive to regional github outages

### ISSUE THREAD

**Issue by pcj** [bazelbuild/continuous-integration#639]
Today it seems that github is performing poorly in the EU.  It would be good for bazel's ci system to somehow be more resilient to regional github outages.

**Comment by philwo** [comment]
I've moved Bazel's Linux and Windows VMs to US Central. The macOS machines are still in the office in Europe.

I don't think there's anything we can do to make this better, but if anyone has concrete ideas or suggestions, please let me know! Closing this for now.

PS. LOL - just when I clicked "Comment", I got the "GitHub is having trouble" page and had to retry a minute later. Oh the irony.
