### ISSUE TITLE
Jenkins Blue Ocean UI

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/continuous-integration#64]
Jenkins' new UI looks like a huge improvement, and the v1.0 general availability was just announced. :)

https://jenkins.io/blog/2017/04/05/say-hello-blueocean-1-0/#say-hello-to-blue-ocean-1-0

**Comment by damienmg** [comment]
I just send a CR: https://bazel-review.googlesource.com/c/9933/

**Comment by damienmg** [comment]
:) coming along

**Comment by damienmg** [comment]
And now live :)
