### ISSUE TITLE
Request to add new project Kythe

### ISSUE THREAD

**Issue by achew22** [bazelbuild/continuous-integration#640]
- I want to test the following project on Bazel CI: https://github.com/kythe/kythe
- I confirm that the project has a `.bazelci/presubmit.yml` file.
The PR to add it lives here https://github.com/kythe/kythe/pull/3723 and may require input from the Bazel CI team

**Comment by fweikert** [comment]
I'll wait until the config is merged, then I can create the pipeline.

**Comment by achew22** [comment]
The config is now merged.

**Comment by fweikert** [comment]
I created https://buildkite.com/bazel/kythe and sent you the instructions for how to configure the GitHub webhook.

**Comment by philwo** [comment]
It seems like we have to install a missing tool (`flex`) in the CI image, too. I'll do that tomorrow and will see if we get a green build then.

**Comment by achew22** [comment]
@philwo, looks like there might be a few more required dependencies. From [their docs](https://kythe.io/getting-started/)

```
asciidoc
bison-3.0.4
clang >= 3.8
docker (for release images //kythe/release/... and //buildtools/docker)
flex-2.5
go >= 1.7
graphviz
jdk >= 8
leiningen (used to build //kythe/web/ui)
node.js
parallel
source-highlight
uuid-dev
wget
```

**Comment by achew22** [comment]
@shahms, could you comment on here. Are any of those deps not needed anymore?

**Comment by shahms** [comment]
Definitely required:
  `bison`, `flex`, `go`, `jdk`, `uuid-dev`

Maybe required:
  `clang` (We only support compiling with clang, but GCC *should* work)

The others are mostly required by the website and examples or for debugging and can probably be omitted.  I'd *really* like to move all of the external dependencies to toolchains, but have so far only done so for flex/bison.

**Comment by shahms** [comment]
@schroederc may be able to add more insight as well.

**Comment by achew22** [comment]
@philwo, did you have any luck?

**Comment by philwo** [comment]
Yes, I got this working now with installing a few dependencies. There are only four tests failing that don't run - Bazel shows them as "NO STATUS", so they don't fail the build. I wonder if that's expected?

//kythe/cxx/indexer/cxx/testdata:extension_property_xcode
//kythe/cxx/indexer/cxx/testdata:property_decl_defn_xcode_only
//kythe/cxx/indexer/cxx/testdata:selector
//kythe/cxx/indexer/cxx/testdata:subscript_ref

The first one seem to require Xcode, so it's probably WAI that they don't work on Linux. But the latter two fail with this:

```
bazel test --sandbox_tmpfs_path=/tmp //kythe/cxx/indexer/cxx/testdata:subscript_ref
DEBUG: Rule 'build_bazel_rules_nodejs' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "ee6f2e3ff1d5806ae864d31d28a7daa99057770f", shallow_since = "1542735594 -0800" and dropping ["tag"]
DEBUG: Rule 'boringssl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "40f8cd52590c8d887946844430f2c8fccf8bd5b3050010e78bab28382986960a"
WARNING: /workdir/kythe/cxx/indexer/cxx/BUILD:3:1: in cc_library rule //kythe/cxx/indexer/cxx:kythe_claim_client: target '//kythe/cxx/indexer/cxx:kythe_claim_client' depends on deprecated target '//kythe/cxx/extractor:index_pack': Please use :kzip_{reader,writer}
WARNING: /workdir/kythe/cxx/indexer/cxx/BUILD:389:1: in cc_library rule //kythe/cxx/indexer/cxx:lib: target '//kythe/cxx/indexer/cxx:lib' depends on deprecated target '//kythe/cxx/extractor:index_pack': Please use :kzip_{reader,writer}
INFO: Analyzed target //kythe/cxx/indexer/cxx/testdata:subscript_ref (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //kythe/cxx/indexer/cxx/testdata:subscript_ref failed to build
Target //kythe/cxx/indexer/cxx/testdata:subscript_ref failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.444s, Critical Path: 0.05s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
//kythe/cxx/indexer/cxx/testdata:subscript_ref                        NO STATUS

INFO: Build completed successfully, 1 total action
```

**Comment by shahms** [comment]
We omit those tests using `restricted_to = ["//buildenv:darwin"]` as they require xcode to build.  We'd love a better way to automatically filter out tests which aren't supported on the current platform but I haven't tried exec_compatible_with to see if it fits our needs yet.

**Comment by shahms** [comment]
(As you've noted when a test is filtered out due to an incompatible constraint the error message leaves something to be desired)

**Comment by philwo** [comment]
This is all done now from our side. :)

Just FYI, if you want to see presubmit results for pull requests, you'd need to complete the final setup step:

- Either a repository admin adds our robot account @bazel-io to the repository collaborators with write access (unfortunately write access is required to be able to send commit statuses)
- Or someone who already has write access to the repository [connects their Buildkite account to GitHub](https://buildkite.com/user/connected-apps) and grants the required permissions.

(We're also working on writing this all up in our documentation so it's easier to understand the steps required for onboarding a project...)

**Comment by shahms** [comment]
I've signed up for a Buildkite account, connected it to GitHub and granted appropriate permissions.

BuildKite asked about organizations upon signing up, should I create a new one or is there a Google Org, Bazel Org, etc?

**Comment by fweikert** [comment]
I've sent you an invite to the Bazel org.

**Comment by shahms** [comment]
Got it, thanks!

**Comment by philwo** [comment]
Looks like you're all set and pull-request tests are working :) I'm closing this issue, feel free to re-open or file a new one if you need help with anything.
