### ISSUE TITLE
Request to add new project upb

### ISSUE THREAD

**Issue by haberman** [bazelbuild/continuous-integration#656]
- I want to test the following project on Bazel CI: https://github.com/protocolbuffers/upb
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
Hi @haberman,

thanks for the request. :)

I've created a pipeline for your project: https://buildkite.com/bazel/upb/ and added you as an admin for the pipeline.

The first build failed, I'll investigate tomorrow what's up with it. Maybe we have to install a missing dependency on the CI image. For macOS, I'm not sure why the test log upload fails - I'll also have a look at that.

As soon as the build / test is green, I'll add your project to the downstream projects that we test against and if you like, you can also enable postsubmit and PR presubmit checks for your GitHub repo. I'll send instructions when we have the build working.

**Comment by philwo** [comment]
I've installed the missing dependency "libreadline-dev" and now the build works fine. :)

**Comment by philwo** [comment]
I've also added upb to our downstream project pipeline.
