### ISSUE TITLE
Downstream pipelines + projects with custom Bazel versions cause redundant work

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#666]
rules_apple runs the same set of targets with different Bazel versions: https://raw.githubusercontent.com/bazelbuild/rules_apple/master/.bazelci/presubmit.yml

It's also part of the downstream pipeline, which takes the same configuration, but overwrites the Bazel version with the Bazel-under-test binary. As a result, the tasks "macos_latest" and "macos_last_green" are completely identical in the downstream pipeline, which means we do the same work twice.

**Comment by meteorcloudy** [comment]
We should skip the config that are not for Bazel@Release for the incompatible flags pipeline. See this failure
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/116#8ce3fbee-0556-4d37-83e0-183158d0101e

FYI @hlopko

**Comment by meteorcloudy** [comment]
Ah, this is trick, rules_nodejs is using 0.26.0rc3 for all of their build
https://github.com/bazelbuild/rules_nodejs/blob/a7246faad7adea6318c461e5c50a0f48bedb03fe/.bazelci/presubmit.yml#L2

**Comment by hlopko** [comment]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/124#4745e432-0461-405e-8258-f66d47a127c4 seems buildfarm is fixed on 0.25.

What @meteorcloudy is saying makes sense to me!
