### ISSUE TITLE
Preparing working directory step failed with permission denied error

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#667]
https://buildkite.com/bazel/culprit-finder/builds/160#01a8acb6-b03f-4e60-879b-ef20a777125a
```
🚨 Error: Failed to remove "/var/lib/buildkite-agent/builds/bk-docker-8ztz/bazel/culprit-finder" (unlinkat /var/lib/buildkite-agent/builds/bk-docker-8ztz/bazel/culprit-finder/__pycache__/bazelci.cpython-36.pyc: permission denied)
```

**Comment by meteorcloudy** [comment]
FYI @hlopko

**Comment by meteorcloudy** [comment]
Rerun seems to fix the problem

**Comment by philwo** [comment]
This was an issue in our pipeline config, where certain steps ran as the wrong user inside the Docker container and thus created files that couldn't be deleted by the buildkite-agent user. I fixed all pipelines so this should not happen again.
