### ISSUE TITLE
Schedule regular restart of workers

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#68]
Today we had a test that flaked out because the machine was running out of memory, the jenkins slave process was taking up 40G of ram!!!

In addition to monthly reimaging #48, we should at least restart the slaves once a week.

/cc @aehlig fyi

**Comment by damienmg** [comment]
This is a subitem of #48

**Comment by philwo** [comment]
Closing, as I don't recall this being a problem in the last months.
