### ISSUE TITLE
"no such package '@buildkite_config//config': The repository '@buildkite_config' could not be resolved"

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/continuous-integration#694]
While triaging a flag flip, I noticed this unrelated error at bazel-head for `Bazel integration testing`. Figured I'd file an issue to alert sooner rather than let it go overnight. Not sure if it belongs here or in bazelbuild/bazel; looks like it affects only RBE.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1009#ec2e8f62-c20b-4eb6-907c-8e899980244f

**Comment by philwo** [comment]
FYI @nlopezgi

**Comment by philwo** [comment]
That project will have to bump their version of bazel-toolchains, I think.

Thanks for bringing it up, Jon!

**Comment by nlopezgi** [comment]
can you make sure they have a declaration of an rbe_autoconfig rule that looks just like this one:
https://github.com/bazelbuild/rules_scala/blob/master/WORKSPACE#L165

I need to update docs https://docs.bazel.build/versions/master/remote-execution-ci.html to reflect this change

**Comment by philwo** [comment]
@nlopezgi I sent PRs to all projects that I could find that use bazel_toolchains and mentioned you on them. :)

**Comment by nlopezgi** [comment]
Thanks for looping me in!

**Comment by philwo** [comment]
Bazel Integration Testing has merged the fix, so I'm closing this.
