### ISSUE TITLE
IntelliJ Plugin Aspect fails on Linux

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#705]
Looks like a simple configuration error:

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-fh25/bazel-downstream-projects/intellij/aspect/intellij_info_impl.bzl:105:25: android_common is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_google_legacy_api
--
  | ERROR: Skipping '//aspect:aspect_files': error loading package 'aspect': Extension 'aspect/intellij_info_impl.bzl' has errors
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1021#5f71c453-1fea-416c-8abb-1ba725f5d5f5

**Comment by jin** [comment]
We undid the protection of `android_common` behind `--experimental_google_legacy_apis`, because it's a breaking in a stable release. https://github.com/bazelbuild/intellij/pull/1005 removes this flag from the bazelci step.
