### ISSUE TITLE
Request to add new project starlark

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/continuous-integration#711]
- I want to test the following project on Bazel CI: https://github.com/bazelbuild/starlark
- I confirm that the project has a `.bazelci/presubmit.yml` file.

+@laurentlb

**Comment by fweikert** [comment]
I've created a pipeline (https://buildkite.com/bazel/starlark) and sent further instructions to Laurent.

**Comment by laurentlb** [comment]
I've added the webhook on GitHub.

**Comment by fweikert** [comment]
Nice, it works: https://github.com/bazelbuild/starlark/pull/51 -> https://buildkite.com/bazel/starlark/builds/2
