### ISSUE TITLE
Request to add new project rules_java

### ISSUE THREAD

**Issue by iirina** [bazelbuild/continuous-integration#712]
- I want to test the following project on Bazel CI: https://github.com/bazelbuild/rules_java
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by fweikert** [comment]
Done! Please configure the webhook as per https://buildkite.com/bazel/rules-java-java/settings/setup/github?setup=true (if you want GitHub presubmit support).

**Comment by iirina** [comment]
Thanks Florian! I configured the webhook as well.
