### ISSUE TITLE
Request to add new project Sandboxed API

### ISSUE THREAD

**Issue by cblichmann** [bazelbuild/continuous-integration#713]
- I want to test the following project on Bazel CI: https://github.com/google/sandboxed-api
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by fweikert** [comment]
I've created a pipeline: https://buildkite.com/bazel/sandboxed-api

Moreover, I've sent you an invite to the Bazel org in Buildkite. Then you'll be able to access the webhook setup instructions at https://buildkite.com/bazel/sandboxed-api/settings/setup/github.
Following these instructions will enable Buildkite runs for GitHub PRs.

**Comment by philwo** [comment]
@fweikert Someone with write access will also have to connect their GitHub account to Buildkite via https://buildkite.com/user/connected-apps, otherwise Buildkite does not have permission to report PR status checks back to the repo.

**Comment by cblichmann** [comment]
Done, thanks!
