### ISSUE TITLE
Gerrit: JavaScript dependency issue on CI environment

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#717]
This is a follow-up to upstream issue: https://bugs.chromium.org/p/gerrit/issues/detail?id=11011.

Can someone on Buildkite side check the JavaScript toolchain required by Gerrit Code Review?

@philwo @hanwen @meteorcloudy Can you please have a look? The problem appears to be Buildkite specific, as all PolyGerrit UI Tests are passing on GerritForge CI.

**Comment by philwo** [comment]
Here's the config for Gerrit: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/pipelines/gerrit-postsubmit.yml

And here's the stuff we install specifically for Gerrit in our CI Docker images: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/docker/Dockerfile#L97

We then run the tests using "bazel test //..." and not using "npm run test-template", because we're not testing NPM here, but Bazel. Are you not using `bazel test` to run your tests on GerritForge CI?

If it helps, we can run `npm install` before running `bazel test` though.

**Comment by davido** [comment]
> And here's the stuff we install specifically for Gerrit in our CI Docker images: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/docker/Dockerfile#L97

is telling me:

```
RUN curl -L https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get -qqy update && \
    apt-get -qqy install nodejs && \
    npm install -g typescript fried-twinkie@0.0.15 && \
rm -rf /var/lib/apt/lists/*
```

while on master te version is different, see: https://gerrit.googlesource.com/gerrit/+show/master/polygerrit-ui/README.md#35

```
  $ npm install
  $ sudo npm install -g polylint
```

Right now I'm wondering, if the first line should also be: `sudo npm install`.

Can we easily test Buildkite's docker file locally?

**Comment by philwo** [comment]
> Can we easily test Buildkite's docker file locally?

Yeah, it's publicly available. You should be able to use it like this:

`docker run --rm -it gcr.io/bazel-public/ubuntu1604:java8`

I'll send a PR to try running `npm install` before running the Gerrit tests. Maybe that already fixes the problem. :)

**Comment by philwo** [comment]
Nope, doesn't help: https://buildkite.com/bazel/gerrit/builds/2903#baeca7f4-7619-4241-a5cf-bdb3567448f6

**Comment by davido** [comment]
The error is different now. What have you changed exactly?

**Comment by davido** [comment]
> Are you not using bazel test to run your tests on GerritForge CI?

//CC @lucamilanesio
What tests are running for PolyGerrit changes?

**Comment by philwo** [comment]
> The error is different now. What have you changed exactly?

I run "npm install" before running "bazel test //...": https://github.com/bazelbuild/continuous-integration/commit/52f8e1c991adf4060f2f12f3d0026a6cbb3d59dd

**Comment by philwo** [comment]
The error message now:

```
TypeError: Cannot read property 'jsFiles' of null
    at tmp.file (/workdir/node_modules/fried-twinkie/index.js:96:50)
    at _fileCreated (/workdir/node_modules/fried-twinkie/node_modules/tmp/lib/tmp.js:246:7)
    at FSReqWrap.oncomplete (fs.js:135:15)
```

Maybe the fried-twinkie version that we install in our container is too old?

**Comment by davido** [comment]
> Maybe the fried-twinkie version that we install in our container is too old?

I am suspecting this too. Can you try to run: `sudo npm install -g polylint` in Dockerfile?

**Comment by philwo** [comment]
> I am suspecting this too. Can you try to run: sudo npm install -g polylint in Dockerfile?

No, we can't do global installations via `npm install -g`, because the CI user does not have write access to the directories where `npm` would try to write...

**Comment by davido** [comment]
I have asso found this pending change: https://gerrit-review.googlesource.com/c/gerrit-ci-scripts/+/226980.

Is is changing manual installation of JS deps. The "old" Docker image set-up commands are:

```
RUN npm install --unsafe-perm -g \
    eslint@"=4.19.0" \
    eslint-config-google@"=0.12.0" \
    eslint-plugin-html@"=5.0.3" \
    eslint-plugin-promise@"=4.0.1" \
    typescript \
    fried-twinkie@"^0.2.2" \
    polylint polymer-cli \

RUN npm install --unsafe-perm -g 'web-component-tester@$WCT_VER'
```

As we can see, it is installing much newer that what we currently doing in Buildkite's Dockerfile: fried-twinkie@0.0.15. While upstream is using version: fried-twinkie@"^0.2.2".

**Comment by davido** [comment]
@philwo I have just sent this PR: https://github.com/bazelbuild/continuous-integration/pull/720. Untested.
