### ISSUE TITLE
Gerrit Code Review: Bazel CI should verify code @HEAD

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#724]
We have this report for Bazel CI breakage for Gerrit in our issue tracker: [1].

The reports saying, that the commit failing on the Bazel CI is: b88b44c0abce326ab58cde6f562bd9e0d5ead86b, that is here: [2] and is very, very old.

I fixed the breakage on May 30: [3]. Why would Bazel CI try to build stale code base?

The report is also saying, that Gerrit build on Bazel CI was disabled.
Can someone have a look and re-enable Gerrit verification on Bazel CI?

Thanks.

//CC @buchgr @philwo @meteorcloudy.

[1] https://bugs.chromium.org/p/gerrit/issues/detail?id=11021
[2] https://gerrit.googlesource.com/gerrit/+/b88b44c0abce326ab58cde6f562bd9e0d5ead86b
[3] https://gerrit.googlesource.com/gerrit/+/0c4d288ea0f1e592fc820f1cea2b8225bba54553

**Comment by philwo** [comment]
> Why would Bazel CI try to build stale code base?

Bazel CI's downstream pipeline tests projects at their "last green commit". Gerrit's pipeline on Bazel CI has been red since May 16th due to https://github.com/bazelbuild/continuous-integration/issues/717, so the "last green commit" is still one from before that breakage and thus very old.

As soon as we fix the breakage and Gerrit's pipeline turns green again, the downstream pipeline will also test with newer versions.

This is by design, because it doesn't make sense to test Bazel@HEAD with projects at known broken commits.

**Comment by philwo** [comment]
Thanks to @davido's PR, Gerrit pipeline is now green on Linux!

However it's still red on macOS: https://buildkite.com/bazel/gerrit/builds/2911#67219396-639a-4313-a2b6-d7a7e1393609

Can you please update your .bazelversion to 0.27.0rc5? I think that should contain the fix for that.

**Comment by davido** [comment]
@philwo Thanks for clarifying. I've sent this CL: [1], but it wasn't merged yet. Can you somehow verify on Mac OS with this commit included?

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/227792

**Comment by philwo** [comment]
Nice! Thanks for the quick action.

Yes, I kicked off a build at that commit: https://buildkite.com/bazel/gerrit/builds/2912 - let's see what happens. I guess we also need to install the NPM packages on the macOS machines.

**Comment by philwo** [comment]
Yep, now we're back to the missing packages. Let me install them on the macOS machines and retest...

**Comment by philwo** [comment]
All packages have been installed on all Macs and nodejs was upgraded to 10. Retrying the build now.

**Comment by philwo** [comment]
GREEN! As soon as your Gerrit PR has been merged, the Gerrit pipeline will be green again and the downstream pipeline will pick up the latest commit! :)

**Comment by davido** [comment]
Thanks!
