### ISSUE TITLE
Cloning protobuf in downstream project fails on Mac

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#727]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1039#7f8287af-c4fa-40ce-99ac-6c59e59f5529
```
git submodule foreach --recursive git reset --hard
--
  | Entering 'third_party/benchmark'
  | HEAD is now at 5b7683f more clang tidy cleanups (#417)
  | error: unknown option `hard'
  | usage: git submodule--helper foreach [--quiet] [--recursive] [--] <command>
  |  
  | -q, --quiet           Suppress output of entering each submodule command
  | --recursive           Recurse into nested submodules
  |  
  | fatal: run_command returned non-zero status while recursing in the nested submodules of third_party/benchmark


```

**Comment by fweikert** [comment]
Interesting, it succeeded in #1035, but failed in #1036:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1035#e406e7a8-d57d-4404-a19a-c477999d61b4
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1036#c2f68f8d-53ce-4147-9693-65d4d283a2ac

**Comment by fweikert** [comment]
I'm not sure whether Philipp installed updates on the Macs, but something is definitely wrong - I cannot even SSH into the machines any more.

**Comment by philwo** [comment]
I upgraded git to 2.22.0 on the Macs a few days ago.

@fweikert, you have to be on the corp network or VPN to access the machines and also note that they changed IPs since we switched to a bigger subnet a few weeks ago.

The latest list is always in the spreadsheet.

**Comment by fweikert** [comment]
Thanks for the comment, I was indeed using an outdated SSH config :(

**Comment by fweikert** [comment]
https://www.spinics.net/lists/git/msg361307.html

**Comment by meteorcloudy** [comment]
Thanks for investigation!

**Comment by fweikert** [comment]
The test is green again: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1044#d9d728f8-2878-44ba-9391-f30bfa1bb7ad
