### ISSUE TITLE
Building/running gcr:deploy uses up 20GB

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/continuous-integration#73]
This is impractical.

```
$ df -h
...
/dev/dm-1                                                55G   54G     0 100% /
$ sudo du -sh /var/lib/docker
22G	/var/lib/docker
```
![docker](https://cloud.githubusercontent.com/assets/17042/25907871/b69c2002-3576-11e7-8074-472502a2ced0.png)

(Disk usage of /, the red area is docker.)

**Comment by damienmg** [comment]
Unfortunately unless we start using minimal distro instead of ubuntu we cannot reduce to much the size of the image...

**Comment by kchodorow** [comment]
...do we have to use docker?

**Comment by damienmg** [comment]
We can switch to the docker_push that @mattmoor had come with but for pull we are still depending on using apt-get install which requires docker. Ideally we would switch to use a dockerless version of it which would save several giga.

**Comment by damienmg** [comment]
The three images we are building with docker are:

```
FROM ubuntu:wily
RUN apt-get update
RUN apt-get install -y zip g++ openjdk-8-jdk openjdk-8-source wget git unzip python python3 curl dpkg-dev
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
```

```
FROM ubuntu:wily
RUN apt-get update
RUN apt-get install -y zip g++ openjdk-8-jdk openjdk-8-source wget git unzip python python3 curl
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
RUN apt-get install -y golang make
RUN apt-get update
RUN apt-get install -y jekyll
RUN apt-get install -y reprepro
RUN apt-get install -y devscripts
```

```
FROM ubuntu:wily
RUN apt-get update
RUN apt-get install -y zip g++ openjdk-8-jdk openjdk-8-source wget git unzip python python3 curl
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
RUN apt-get install -y ssh
```

(see https://github.com/bazelbuild/continuous-integration/tree/master/base)

I am pretty sure we can make it back to have dockerless images, @mattmoor have probably more visibility about the existing images we can reuse (Java / Jekyll / SSH / g++ / python / python3 / go)

**Comment by damienmg** [comment]
So we only build 2 images now. Closing this one as we cannot do much more than switching to distroless in that respect.

**Comment by mattmoor** [comment]
@damienmg You can still share the base portion of those images so you aren't paying for multiple copies.

e.g. put this in one Dockerfile:
```
FROM ubuntu:wily
RUN apt-get update
RUN apt-get install -y zip g++ openjdk-8-jdk openjdk-8-source wget git unzip python python3 curl
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
```

Tag it "base", then make the others:
```
FROM base
...
```

Right now each of these images *will* produce redundant versions of these layers.
