### ISSUE TITLE
Request to add new project rules_proto

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/continuous-integration#735]
- I want to test the following project on Bazel CI: https://github.com/Yannic/rules_proto
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
@Yannic @hlopko With http://github.com/bazelbuild/rules_proto now existing, should we instead add CI for that?

**Comment by Yannic** [comment]
`Yannic/rules_proto` will most likely be deprecated when `bazelbuild/rules_proto` is populated with content, so adding CI only for the latter sounds good.

Created https://github.com/bazelbuild/rules_proto/pull/2 to get the project started.

**Comment by Yannic** [comment]
@philwo We stated adding rules to `bazelbuild/rules_proto`. How shall we proceed with this request?

/cc @lberki

**Comment by philwo** [comment]
Hi @Yannic @lberki,

I added bazelbuild/rules_proto to the CI now!

Here's the first build: https://buildkite.com/bazel/rules-proto/builds/1
I've enabled postsubmit and presubmit checks for pull requests, too.

Let me know if you need anything else :)

**Comment by Yannic** [comment]
@philwo Thanks a lot! I fixed the failing targets, so the pipeline is green now.

I have one question: Is there a way to restart pipelines or steps? For example, https://buildkite.com/bazel/rules-proto/builds/7#885cdc79-8a08-4641-8eff-4d4a353699f0 failed because of an error from the GitHub API.

**Comment by philwo** [comment]
@yannic You should have the necessary permissions on the Buildkite pipeline when you're logged in there. You can click "Retry" on individual failed steps of a job, or the "Rebuild" button to rerun the entire job:

<img width="1203" alt="Screenshot 2019-08-19 at 15 47 19" src="https://user-images.githubusercontent.com/504652/63270537-aaed3280-c298-11e9-9ac1-06dd7144de1a.png">

If not, let me know and I'll check what's up there. :)

**Comment by Yannic** [comment]
@philwo I can see the "Retry" button after logging in, but I cannot click it because it seems like I don't have the required permissions :(.
<img width="372" alt="Bildschirmfoto 2019-08-19 um 15 51 51" src="https://user-images.githubusercontent.com/7313747/63271304-24d1eb80-c29a-11e9-80ba-2b02d31ed46a.png">

**Comment by philwo** [comment]
@Yannic I sent you a Buildkite invite to the e-mail address listed on your GitHub profile. If you accept it, you should get the required permissions to do retry / rebuild in that pipeline. :)

**Comment by Yannic** [comment]
@philwo Thank you! I verified I can trigger builds in that pipeline https://buildkite.com/bazel/rules-proto/builds/43.
Closing this.
