### ISSUE TITLE
bazel testing pipeline out of workers?

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/continuous-integration#741]
Some builds hang since Saturday in the Publish Bazel binaries pipeline:
https://buildkite.com/bazel-testing/bazel-bazel/builds/432#70cd243f-8150-40c0-82b8-b0e35c13450f

**Comment by philwo** [comment]
I was experimenting with doing some changes to the workers that might be required for autoscaling in the testing environment, but didn't have to finish it. This could have caused it. I didn't deploy any of these changes to the production environment, so it shouldn't happen there.

(FYI @fweikert)

**Comment by fweikert** [comment]
What exactly did you change? I created new instances, but there's only one agent that actually picks up jobs. I'll check the logs.

**Comment by fweikert** [comment]
https://github.com/bazelbuild/continuous-integration/commit/c9dfd8358708abf37fad5fd375ad42b62e3c0a49 seems to be the culprit since the oldest pending jobs are from Friday evening.

**Comment by fweikert** [comment]
I've created new bk-testing-docker images and instances from the master branch so that we can reduce the backlog of jobs.

**Comment by fweikert** [comment]
20 docker agents are back online and busy.

**Comment by philwo** [comment]
Yes, that’s the right commit. Thanks!

**Comment by meisterT** [comment]
No windows worker here? https://buildkite.com/bazel-testing/bazel-bazel/builds/467#02b4cbca-702c-4e0c-81d1-3e712a0642bb

**Comment by philwo** [comment]
@meisterT Windows workers aren’t working today, because it’s a public holiday in the US. 😀

(I might have done a similar change for Windows, too - but does the blocked testing CI cause you any trouble? If not, feel free to just ignore it :))

**Comment by meisterT** [comment]
It's not a priority or causing real trouble. I am just easily confused by the number of builds in the my builds bubble on buildkite.

![nmv2XJ19GHp](https://user-images.githubusercontent.com/418721/60647690-8bac5a00-9e3e-11e9-8328-c8aa009ecabc.png)

**Comment by fweikert** [comment]
Current status: Buildkite is busy executing the backlog of jobs. I created some additional Windows VMs this morning, which has helped.

**Comment by fweikert** [comment]
I'm closing this issue since the backlog has been processed and there's a sufficient number of agents.
