### ISSUE TITLE
Activate gerrit CI again

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#742]
Gerrit build was recently deactivated due a incompatibility issue. It is now fixed on Gerrit@HEAD.

**Comment by davido** [comment]
//CC @meteorcloudy @philwo.

This is a follow-up from Issue reported by @hlopko in: [1].

[1] https://bugs.chromium.org/p/gerrit/issues/detail?id=11122

**Comment by meteorcloudy** [comment]
Gerrit is green with Bazel@HEAD, do we have to do anything else?
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1104#4463dea3-5b3f-45d0-8147-330beefc9dab

**Comment by davido** [comment]
Thanks.
