### ISSUE TITLE
Request to add new project Bazel Gazelle

### ISSUE THREAD

**Issue by achew22** [bazelbuild/continuous-integration#759]
- I want to test the following project on Bazel CI: https://github.com/bazelbuild/bazel-gazelle
- I confirm that the project has a `.bazelci/presubmit.yml` file. [Yes](https://github.com/bazelbuild/bazel-gazelle/pull/587)

**Comment by achew22** [comment]
Friendliest of pings

**Comment by jayconrod** [comment]
@philwo Could you help us out? Anything else than needs to happen in bazel-gazelle first?

**Comment by philwo** [comment]
Hi! Sorry - I realize I accumulated quite a backlog of project addition issues here. :( I'll go through them tomorrow and will set you up! Config looks OK to me, I think it should work fine.

**Comment by philwo** [comment]
Hi @achew22 @jayconrod,

all done! :)

Here's the pipeline and first build: https://buildkite.com/bazel/bazel-gazelle/builds/1
I also enabled presubmit testing for pull requests in your repo.

Let me know if you need anything else!

Cheers,
Philipp

**Comment by jayconrod** [comment]
@philwo Thanks, looks like it's working! I fixed some things that didn't work on Windows and excluded tests that weren't expected to work there, so the pipeline is green now. I'm about to turn down Travis CI.

Thank you again! I think this issue can be closed.
