### ISSUE TITLE
Request to add new project grpc-ecosystem/grpc-gateway

### ISSUE THREAD

**Issue by achew22** [bazelbuild/continuous-integration#788]
- I want to test the following project on Bazel CI: https://github.com/grpc-ecosystem/grpc-gateway
- I confirm that the project has a [`.bazelci/presubmit.yml`](https://github.com/grpc-ecosystem/grpc-gateway/pull/983) file.

@johanbrandhorst, FYI
@philwo, et al. thanks for running this service!

**Comment by achew22** [comment]
@philwo, friendly ping

**Comment by fweikert** [comment]
I'll set up the pipeline tomorrow when I'm back in the office (Phil is on vacation).

**Comment by fweikert** [comment]
Done! Please see these instructions for setting up a GitHub webhook:
https://buildkite.com/bazel/grpc-gateway/settings/setup/github

**Comment by fweikert** [comment]
Closing since the pipeline exists.

**Comment by achew22** [comment]
The webhook has been installed for a while, but I haven't been seeing the status show up in our pull requests. It looks like the builds are even happening on the buildkite side. Do you know what I need to do for that?

**Comment by philwo** [comment]
@achew22 Someone who has write access to the repository has to connect their GitHub account to Buildkite via https://buildkite.com/user/connected-apps. This allows Buildkite to push the commit statuses to GitHub. :)
