### ISSUE TITLE
TensorFlow Linux build failed only on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#793]
I'm filing the issue here because it looks like a infra change that caused this.

I reran a previous build that succeeded on Linux, now it's failing with
```
ERROR: /workdir/tensorflow/lite/python/optimize/BUILD:28:1: Couldn't build file tensorflow/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.cc: SWIGing tensorflow/lite/python/optimize/calibration_wrapper.i failed (Illegal instruction): swig failed: error executing command
--
  | (cd /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/org_tensorflow && \
  | exec env - \
  | bazel-out/host/bin/external/swig/swig -c++ -python -module tensorflow_lite_wrap_calibration_wrapper -o bazel-out/host/bin/tensorflow/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.cc -outdir bazel-out/host/bin/tensorflow/lite/python/optimize -Iexternal/eigen_archive -Iexternal/swig -Ibazel-out/host/bin -Ibazel-out/host/bin/external/local_config_python -Iexternal/com_google_absl -Iexternal/gemmlowp -Iexternal/flatbuffers -Iexternal/arm_neon_2_x86_sse -Iexternal/farmhash_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/lite/python/optimize/calibration_wrapper.i)
  | Execution platform: @bazel_tools//platforms:host_platform
```
Previous build: https://buildkite.com/bazel/tensorflow/builds/3273#5f7fbeb9-314d-4106-a716-723510a5f107
Now: https://buildkite.com/bazel/tensorflow/builds/3286#f3a923cc-fd4d-4030-b687-bb348f0e6cde
Both are at https://github.com/tensorflow/tensorflow/commit/80560f9ae4fcf38a3be6246c58de56026d5ac990

Did we have any update on the docker image recently? It started to fail since Tuesday. [#3274](https://buildkite.com/bazel/tensorflow/builds/3274)

**Comment by philwo** [comment]
> "Illegal instruction (core dumped)"

I think what happened here is that we switched to newer machine types with a more modern CPU, then TensorFlow had some C++ code that got optimized for the new CPU, then we had to rollback to the old machine type, now we're still getting cache hits for these binaries, because CPU architecture isn't taken into account for the cache key and these binaries use some instructions that don't exist yet on the older CPU.

We'll have to bump the cache silo key...

**Comment by meteorcloudy** [comment]
I see, thanks for the investigation! I'll send a PR to bump the cache silo key.

**Comment by meteorcloudy** [comment]
Oh, you're fast! Thanks!
