### ISSUE TITLE
Cloud Robotics Core broken, due to dependency having disappeared

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#799]
With Bazel@Release: https://buildkite.com/bazel/cloud-robotics-core/builds/3379
With Bazel@HEAD: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1142#83fbb1cd-d937-4f25-bda5-0e7ac2b6dbe6
```
fatal: could not read Username for 'https://github.com': No such device or address
```

The same commit succeeded yesterday: https://buildkite.com/bazel/cloud-robotics-core/builds/3378

**Comment by philwo** [comment]
They depend on a repo that was deleted or made private: https://github.com/apcera/libretto

Nothing we can do here. If the project doesn’t fix this, we’ll have to remove the project from CI. Let’s keep this open to track how they respond.

@meteorcloudy Could you please file an issue with cloud robotics and reference this issue in the text?

**Comment by meteorcloudy** [comment]
Thanks for investigating! I'll file an issue to them.
