### ISSUE TITLE
Make gce/vm.sh fails when SSH command time out

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#80]
If you are not in an allowed IP for SSH the reimaging of a VM will just goes as if everything went fine, whereas it was not able to initialize the machine. We should emit correct error message in such cases.

**Comment by philwo** [comment]
I'm bumping the priority here, as I've recently seen this happen very often, especially with the FreeBSD 11 slaves, who don't seem to pick up gcloud SSH keys that were created after a certain date for yet unknown reasons.

**Comment by philwo** [comment]
Obsolete, as I've rewritten the entire image and VM handling infrastructure.
