### ISSUE TITLE
Starting Sauce Connect Proxy Step is flaky

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#804]
Starting Sauce Connect Proxy is needed for rules_webtesting, but it's flaky on all platform.

Linux: https://buildkite.com/bazel/rules-webtesting-saucelabs/builds/227#123be0b2-fd0f-421b-b44b-6b13433a804b

Mac: https://buildkite.com/bazel/rules-webtesting-saucelabs/builds/225#16d0f2fb-ab2e-4dbb-a9f5-f3522b5dbca7

Windows: https://buildkite.com/bazel/rules-webtesting-saucelabs/builds/224#67b74489-13cc-4125-bc1f-8157f7b501a4 (Always fail on Windows and get the Windows machine stuck)

We need to fix this in order to re-enable rules_webtesting in downstream.

**Comment by philwo** [comment]
I wonder what’s up with that feature. We didn’t change anything about it in the past months and it used to work fine 🤔 I have two suspicions - changed firewall rules (but I can’t imagine how they would impact this - we allow all outgoing traffic) or maybe we need to update the SC Proxy software.

**Comment by meteorcloudy** [comment]
The Windows machines getting stuck when running this is very weird..

**Comment by philwo** [comment]
Actually, I remember a single refactoring done recently - let’s have another look whether that maybe broke things: https://github.com/bazelbuild/continuous-integration/commit/2b63a7fb5fc133cb3c019453290a43a0596428bf#diff-9ca62ea3191ff346e911994ded260c87

**Comment by philwo** [comment]
I tried to run the same commands in a VM and observed that it can take ~25 seconds for the tunnel to become ready. I wonder if we just run into the 30 seconds timeout and should just wait longer. I'll send a patch to bump it to 60 seconds instead.

Still not sure what's up with Windows hanging, though.

**Comment by philwo** [comment]
The reason why it always fails on Windows is that the readyfile is not created by the proxy on that platform. I can repro this in a Windows VM and am now investigating how to fix it.

**Comment by philwo** [comment]
The problem is that we call the proxy like this:

`sauce-connect.exe /i TUNNEL_ID /f readyfile.txt`

but it actually needs dashes:

`sauce-connect.exe -i TUNNEL_ID -f readyfile.txt`

Conveniently, it doesn't print any warning or error about the wrong arguments, it just silently ignores them 😅 At least the fix is easy!

**Comment by meteorcloudy** [comment]
Thank you so much for debugging and a quick fix!!!!

**Comment by meteorcloudy** [comment]
One more strange behavior:
The build failed on Windows (which I should fix), but the job didn't terminate:
https://buildkite.com/bazel/rules-webtesting-saucelabs/builds/228#283cdc66-1bcc-4568-83e2-e76f1e0b57a4

Looks we failed to terminate the sauce process?
