### ISSUE TITLE
Running docker from mac in buildkite CI

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/continuous-integration#824]
Hi folks,
We are trying to increase the testing coverage on Mac - Buildkite of [rules_docker](https://github.com/bazelbuild/rules_docker). Several of our tests need docker to be present.
Would it be possible to install docker (plus give permissions adequately) so that tests can run the docker binary?
Thanks!

see also
https://github.com/bazelbuild/rules_docker/pull/1143

**Comment by philwo** [comment]
@nlopezgi I don't think this will be possible, unfortunately. :( I'm pretty sure that having access to Docker on a Mac is equivalent to having root on the machine. Our macOS lab machines do not use virtualization, instead we rely on UNIX permissions as a security barrier (all CI jobs run as a minimally privileged user, after each job we ensure that we can restore the machine to the same state as before the job ran). In case a machine gets compromised, we would have to manually reinstall it from scratch.

**Comment by nlopezgi** [comment]
thanks for the clarification, no worries then, we'll have to live with the current level of testing that we have on Mac.
