### ISSUE TITLE
FreeBSD slaves are still with Bazel < 0.5.2

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#84]

**Comment by aehlig** [comment]
The corresponding change to the ports tree is still pending, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220303

If desired, I can manually update the slaves anticipating that change to the FreeBSD ports tree.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment]
> The corresponding change to the ports tree is still pending, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220303

Manually updated the machines to what it would be,
had the mentioned PR be submitted. I will, of course,
monitor that PR and reflect any changes, in case a
different change gets committed to `devel/bazel`.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment]
https://svnweb.freebsd.org/ports?view=revision&revision=445987
