### ISSUE TITLE
Request to add new projects rules_bison, rules_flex, and rules_ragel

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/continuous-integration#844]
- I want to test the following projects on Bazel CI:
  - https://github.com/jmillikin/rules_bison
  - https://github.com/jmillikin/rules_flex
  - https://github.com/jmillikin/rules_ragel
- I confirm that the projects all have a `.bazelci/presubmit.yml` file.

(I'm batching this because they're all similar small rulesets for a common build tool -- please let me know if you'd prefer separate tracking issues)

**Comment by philwo** [comment]
All done! :) I granted you admin access to the three pipelines so that you can setup webhooks for your repos yourself.

Let me know if you need anything else here.

**Comment by jmillikin** [comment]
Thanks! Webhooks set up successfully, and builds are green.
