### ISSUE TITLE
Request to add new project grpc/grpc

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/continuous-integration#857]
- I want to test the following project on Bazel CI: https://github.com/grpc/grpc
- I confirm that the project has a `.bazelci/presubmit.yml` file https://github.com/grpc/grpc/pull/20784.

See https://github.com/bazelbuild/continuous-integration/pull/653#issuecomment-493624684

//cc @jtattermusch

**Comment by Yannic** [comment]
@philwo friendly ping?

**Comment by fweikert** [comment]
Done: https://buildkite.com/bazel/grpc-grpc/builds/1

You're a pipeline admin now (congrats!). Please follow these instruction to set up GitHub webhooks: https://buildkite.com/bazel/grpc-grpc/settings/setup/github
