### ISSUE TITLE
Request to add new project grpc/grpc-web

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/continuous-integration#858]
- I want to test the following project on Bazel CI: https://github.com/grpc/grpc-web
- I confirm that the project has a `.bazelci/presubmit.yml` file https://github.com/grpc/grpc-web/pull/665.

//cc @stanley-cheung

**Comment by Yannic** [comment]
@philwo friendly ping? It's been a year and it would be great if we could onboard grpc-web onto Bazel-CI

**Comment by fweikert** [comment]
Done: https://buildkite.com/bazel/grpc-grpc-web/builds/1

You're a pipeline admin now (congrats!). Please follow these instruction to set up GitHub webhooks: https://buildkite.com/bazel/grpc-grpc-web/settings/setup/github
