### ISSUE TITLE
Proposal to allow project owners to be notified about incompatible changes

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/continuous-integration#859]
Hello excellent productive EngProdExcellence engineers :)

We discussed before that it would be useful for project owners to be notified about an incompatible changes that they need to migrate for.

Right now we have one big pipeline that builds all downstream projects and shows one global summary. If we could also create a per-project pipelines that only run one project against all incompatible changes, and fail the build in case at least one migration is needed, project owners could set a buildkite notification for this.

Does it make sense? Is it possible?
@philwo @meteorcloudy

**Comment by fweikert** [comment]
I actually implemented this feature some time ago, but haven't merged the code yet since it's blocked by an open PR.

Commit: https://github.com/fweikert/continuous-integration/commit/df4f466a98b495218e7e2d60cae73f2bec89977c

Pipeline: https://buildkite.com/bazel/bazel-federation-bazel-rc-plus-incompatible-flags

Settings:

```
---
env:
  USE_BAZELISK_MIGRATE: true
```

Example: https://buildkite.com/bazel/bazel-federation-bazel-rc-plus-incompatible-flags/settings

**Comment by fweikert** [comment]
The feature PR is https://github.com/bazelbuild/continuous-integration/pull/837, blocked by https://github.com/bazelbuild/continuous-integration/pull/838

**Comment by philwo** [comment]
@fweikert I wasn't aware that #838 is needed for a production feature. From the description it sounded like it was just useful for developers to test scripts (which is nice, but IMHO doesn't warrant the added complexity).

If you need that PR and don't see a simpler way to do it, feel free to merge it.

**Comment by fweikert** [comment]
#838 is not really needed, it was just in the same branch. I cherrypicked the important commit into a separate branch and merged it.

However, merging 838 would still be nice since otherwise we have to change all the URLs in bazelci.py whenever we want to test something.

**Comment by fweikert** [comment]
Documentation: https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#testing-with-incompatible-flags

**Comment by fweikert** [comment]
Example run: https://buildkite.com/bazel/bazel-federation-bazel-rc-plus-incompatible-flags/builds/12
