### ISSUE TITLE
Request to add new project attilaolah/bazel-tools

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/continuous-integration#871]
- I want to test the following project on Bazel CI: http://github.com/attilaolah/bazel-tools
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by attilaolah** [comment]
Closing in favour of GitHub Actions.

**Comment by philwo** [comment]
Sorry for not following up here, @attilaolah! 😞 I hope GitHub Actions works well! I just saw that they apparently install Bazelisk on their machines out of the box - this is really cool.

**Comment by attilaolah** [comment]
No worries!
