### ISSUE TITLE
Discard old archive artifacts after some time

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#88]
We want to keep the build information but not all the version of Bazel, it is filling up the disk (currently taking 1.3Tb, we have a 10Tb hard limit).

**Comment by laszlocsomor** [comment]
Do you have anything against manually deleting the build outputs on the machine? Even better, automate it? (A cron job would be a start, I could set that up.)

**Comment by damienmg** [comment]
As discussed offline with @aehlig, I am against manual or self-build automation:
 - We will mess up with Jenkins model
 - We might mess up and accidentally delete something we do not want.

What could be done however, is since we do not actually care about log output or job information of non release build, we can use jenkins auto-deletion mechanism to delete build older than 3 months and mark a permanent the release builds specifically. That's totally supported by Jenkins, the only question left is how to automated marking the release build as permanent.

Maybe there are also other plugins to do exactly what I suggested earlier, instead of relying on a cron.

**Comment by laszlocsomor** [comment]
How do you normally mark a build as permanent? Knowing that would help finding a way to automatically mark release builds as permanent.

What's our short term solution? Does increasing the disk in GCP help for now? Can I push changes to github?

**Comment by damienmg** [comment]
Yes sorry we have 8TB of free space, which should offer us at least a year.
Mark as permanent used to be a checkbox on a build, cannot find it anymore.

**Comment by laszlocsomor** [comment]
Got it, thanks! So is it safe to push changes to github now and let CI run?

**Comment by damienmg** [comment]
Yes we can!
