### ISSUE TITLE
Jenkins Test Results Analyzer not working

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#89]
http://ci.bazel.io/job/bazel-tests/test_results_analyzer/ is reporting:
```
No build data retrieved. You may need to select a Module.
```

This seems to be related to our config for publishing test result XML, which is set to:
bazel-testlogs/**/test.xml, bazel-testlogs/**/dummy.xml

If these files can't be loaded, the analyzer can't run.

**Comment by damienmg** [comment]
FTR the dummy.xml is going away in the next days.

**Comment by damienmg** [comment]
And indeed, it works in the new jobs: http://ci.bazel.io/job/CR/job/bazel-tests/test_results_analyzer/

**Comment by katre** [comment]
Ah, excellent, because I couldn't make any sense of it. Thanks!

**Comment by damienmg** [comment]
Just reopening until the change for the main jobs get merged. I'll mark the change that fix it in the CL description so it get closed when I merge it :)

**Comment by katre** [comment]
SGTM
