### ISSUE TITLE
Status of --incompatible* issues

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#903]
On the 18th, a bunch of rule sets got issues filed for different --incompatible* flags.  But looking at https://buildkite.com/bazel/bazelisk-plus-incompatible-flags, it seems like those flags are no longer being tested.  So…

What's the deal?  Should you be closing all those issues you opened on other project?  Is there any other guidance for them now that the flags aren't being monitored?

**Comment by fweikert** [comment]
I'm still working on fixing the notification feature (see commits for https://github.com/bazelbuild/continuous-integration/issues/869). As soon as the feature is done, a new set of issues with correct details will be created.

**Comment by thomasvl** [comment]
Should all the ones previously created be closed out?

**Comment by fweikert** [comment]
Yes, that would make sense.

**Comment by thomasvl** [comment]
It looks like some are getting recreated when the projects can't fix them (the issue is in the bazel release) - https://github.com/bazelbuild/rules_swift/issues/368

**Comment by fweikert** [comment]
Wrote a mini PM: https://github.com/bazelbuild/continuous-integration/issues/915#issuecomment-569651706

**Comment by thomasvl** [comment]
Closing this out since I got the status on these original issues and it seems like there are other issues open to track improvements to the system.
