### ISSUE TITLE
UI Improvement: Make CI removes Presubmit-Ready votes so it can be retriggered by resetting it.

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/continuous-integration#92]
See https://bazel-review.googlesource.com/c/13430/
After Bazel CI set Verified -1: https://bazel-review.googlesource.com/c/13430/#message-168cc226730dc6bd92789969411a6511642a8b0d

switching presubmit-ready back to +1 has no effect.

**Comment by damienmg** [comment]
You need to remove Bazel CI and its vote.

**Comment by damienmg** [comment]
(this is documented in the in-fly documentation)

**Comment by dslomov** [comment]
I did and it had no effect :(

**Comment by dslomov** [comment]
Ah I see I have not removed "Bazel CI", only its vote

**Comment by dslomov** [comment]
(maybe Bazel CI should remove itself when it adds "Verified" vote?)

**Comment by damienmg** [comment]
If it removes itself, it removes the vote, the problem is sometime removing Bazel CI actually retrigger the build and Verified stays 1 (some glitch in gerrit).

Maybe what we should do is have bazel ci remove pre-submit+1 when it starts, in which case no need to do anything else, wdyt?

**Comment by dslomov** [comment]
if pre-submit+1 set later re-triggers it, that would work.
