### ISSUE TITLE
Request to add new project bcsgh/bazel_rules

### ISSUE THREAD

**Issue by bcsgh** [bazelbuild/continuous-integration#926]
- I want to test the following project on Bazel CI: https://github.com/bcsgh/bazel_rules
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by bcsgh** [comment]
If I can put more than one project in a single request:
https://github.com/bcsgh/bash_history_db
https://github.com/bcsgh/stl-to-ps
https://github.com/bcsgh/tbd

**Comment by philwo** [comment]
Hi @bcsgh, thanks for your request! I'll get to this soon, either tomorrow or early next week and will get back to you here then!

**Comment by bcsgh** [comment]
Bump? 
https://github.com/bcsgh/bazel_rules
https://github.com/bcsgh/utilities

**Comment by philwo** [comment]
Hi @bcsgh! Sorry for the delay 😞 I'll get to this by end of this week, promised!

Cheers,
Philipp

**Comment by bcsgh** [comment]
Bump?

**Comment by fweikert** [comment]
Sorry for the long delay. Are you still interested in testing your projects on Bazel CI?

**Comment by bcsgh** [comment]
Yes, please:

- https://github.com/bcsgh/bash_history_db
- https://github.com/bcsgh/bazel_rules
- https://github.com/bcsgh/stl-to-ps
- https://github.com/bcsgh/tbd-http
- https://github.com/bcsgh/tbd
- https://github.com/bcsgh/utilities

Is it possible to have CI enabled for a (for now) private repository? If so, than I'd include

- https://github.com/bcsgh/fm-index
- https://github.com/bcsgh/url

(Presumably that would require granting some account access to those repos?)

**Comment by fweikert** [comment]
Done:

- https://buildkite.com/bazel/bcsgh-bash-history-db
- https://buildkite.com/bazel/bcsgh-bazel-rules
- https://buildkite.com/bazel/bcsgh-stl-to-ps
- https://buildkite.com/bazel/bcsgh-tbd
- https://buildkite.com/bazel/bcsgh-tbd-http
- https://buildkite.com/bazel/bcsgh-utilities

Unfortunately we don't support private repos right now. 
Can you please send me an email (address is in my profile) so that I can invite you to our Buildkite org? Then we can set up GitHub integration for your pipelines, too.

**Comment by bcsgh** [comment]
It looks like my attempt to get clang builds isn't working:
https://github.com/bcsgh/bazel_rules/blob/master/.bazelci/presubmit.yml#L10-L17
https://buildkite.com/bazel/bcsgh-bazel-rules/builds/1#8bc82d85-0507-46fb-bed3-06a67903bffb/201-832

The only mention of clang I'm seeing in the docs seems to suggest that should work, but it's not explicitly about setting the compiler:
https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#setting-environment-variables

Before I start debugging that myself, is there documentation/example elsewhere for doing that?

**Comment by fweikert** [comment]
Unfortunately there is no documentation on Clang specifically :(

`clang: error: invalid linker name in argument '-fuse-ld=/usr/bin/ld.gold'` - not sure where this flag value comes from.

I checked some of our clang builds, and they all run on Ubuntu 18.04, whereas your task runs on 16.04.:
- https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml
- https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml
- https://github.com/bazelbuild/rules_swift/blob/master/.bazelci/presubmit.yml

**Comment by bcsgh** [comment]
Thanks. That gives me some ideas were to look.

Oh what I'd give for a set of fully hermetic cross tool libraries! Just add `--crosstool=@clang//11.0.1/host-amd64-linux/target-RISC-V-BSD` and no need to worry about how or what, if any, tool chains are installed locally. Any idea where I would ask for such a thing? I suspect it would end up being a very cross functional endeavor.

**Comment by fweikert** [comment]
I don't have any idea except for maybe https://groups.google.com/g/bazel-dev.

**Comment by fweikert** [comment]
Btw, if you want Buildkite to update commit statuses in GitHub, please invite @bazel-io as collaborator.

**Comment by fweikert** [comment]
Closing this issue since the project has been onboarded. Please let me know if some help is needed!

**Comment by bcsgh** [comment]
Thanks. All my remaining concerns have open issues: 

- I've opened https://github.com/bazelbuild/continuous-integration/issues/1134 for another project to add
- And https://github.com/bazelbuild/continuous-integration/issues/1133 for one of the builds that seems to be failing (I suspect the CI's invocation of bazel?).

**Comment by philwo** [comment]
Hi @bcsgh,

I noticed that all of your projects on Bazel CI are red, most of them for a while:

- https://buildkite.com/bazel/bcsgh-bazel-rules
- https://buildkite.com/bazel/bcsgh-stl-to-ps
- https://buildkite.com/bazel/bcsgh-tbd
- https://buildkite.com/bazel/bcsgh-tbd-http
- https://buildkite.com/bazel/bcsgh-utilities

I'm looking to reduce the complexity / scope of our Bazel CI setup a bit - would you mind testing these projects using GitHub Actions instead? 😊 We've recently added support for Bazelisk that should make it really easy: https://github.com/marketplace/actions/setup-bazelisk - if that's an option for you, please let me know (and feedback on that GitHub Actions plug-in would also be very welcome!).

**Comment by bcsgh** [comment]
Would you mind taking a look at https://github.com/bazelbuild/continuous-integration/issues/1133?

Fixed:
- https://buildkite.com/bazel/bcsgh-bazel-rules
- https://buildkite.com/bazel/bcsgh-utilities

Fix blocked on https://github.com/bazelbuild/continuous-integration/issues/1133
- https://buildkite.com/bazel/bcsgh-stl-to-ps
- https://buildkite.com/bazel/bcsgh-tbd
- https://buildkite.com/bazel/bcsgh-tbd-http

---

As for feedback: that link might be useful for someone who knows what a "GitHub action plug-in" is and/or something about "Bazelisk". I've never run into ether before. It would be a vast improvement if it included:

- A description of what that is supposed to accomplish (I presume it's something CI/CD related?, but I only know that because I came to it from here).
- Why I'd want to use it vs something else.
- Descriptions of the basic concepts (or links to the same).
- A "how to set this up" section (preferably one that is useful for someone who knows the generic concepts but has never run into any of the proper nouns before.)

Bonus points would be to have an example `.bazelci/presubmit.yml` before and `action.yml` after.

At this point I've really no motivation to move off the existing system and maybe have motivation to stay on it. (E.g. IIRC things in the existing system are used as part of the bazel release testing. Would you notice a release breaking my build with the alternative?) If you want people to move to a new system, you should make it as easy as possible, particularly for people who have minimal or zero knowledge about the specifics of the new system.

**Comment by philwo** [comment]
Thanks for the feedback! I'll look into #1133. I'll get back regarding your other questions soon.
