### ISSUE TITLE
Bazel release - invalid developer directory '/Applications/Xcode10.2.1.app'

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/continuous-integration#929]
Command run:
```bash
$ scripts/release/release.sh create --force_rc=2 2.1.0 41ec5a28fb30a8d6c5c60194c4bb29528352cf78 733ac0ff7ad1e13ab68ceb2fde694d7ab71b2366 c94b1474b368dedf9f68f34fad90cc8664f2b0e0 2a8cc7075f741721563efd9dc050ca3458cde30b
$ scripts/release/release.sh push
```

This results in a failure on macos: https://buildkite.com/bazel-trusted/bazel-release/builds/127#4f738b03-fa8f-4162-aa00-44db615aeacd

**Comment by laurentlb** [comment]
cc @philwo

**Comment by philwo** [comment]
Ohh, I see! Let's keep the failed step like it is for now - the solution is simple, but I have to do a quick check of why we pinned the release builds to an old Xcode version tomorrow. 🤔 We can then click "retry" on Buildkite for the macOS job and it should just work.

**Comment by laurentlb** [comment]
Sounds good!

**Comment by philwo** [comment]
Fixed with https://github.com/bazelbuild/continuous-integration/commit/be135ec5ff94a8e32afa845dcc040664b08e11a0.
