### ISSUE TITLE
Slaves do not properly clean up files

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/continuous-integration#93]
The Jenkins slaves leak files, filling up the disks over time. While #48 might be a work-around for that problem, it seems worth addressing the underlying problem as well. A particularly big source of accumulated files is `~ci/.cache/bazel`. Among other things, each new version of bazel (and we generate one for every push in order to test bazel tests and downstream projects with bazel at head) unpacks its own embedded tools there (in a unique directory).

**Comment by philwo** [comment]
Agree that this is a problem, especially on machines we can't easily reimage, like the Mac Pros.

**Comment by buchgr** [comment]
can be closed, as we are shutting down jenkins.
