### ISSUE TITLE
Switch to nightly builds

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#94]
We currently build after each push but there is no need for it, instead we should have bazel-tests and bazel-docker-tests run on post submit and the whole pipeline run as a nightly (since the sheriff can retrigger it if he needs too).

**Comment by damienmg** [comment]
Due to a86356a81e14f8b11d32876dc534a3a406784c91, this is no longer completed.

/cc @aehlig @dslomov

**Comment by dslomov** [comment]
Ah sorry I missed this issue and its resolution.
From sheriffing last week (when CI run the entire pipeline post-push), I think we are not ready yet for nightly-only runs. Majority of breakage I discovered was detected by Global/pipeline (testng with Bazel at HEAD).

It is also not clear in the UI how to trigger this pipeline manually.
