### ISSUE TITLE
Request to add new project k0s

### ISSUE THREAD

**Issue by btwiuse** [bazelbuild/continuous-integration#940]
- I want to test the following project on Bazel CI: https://github.com/btwiuse/k0s
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by fweikert** [comment]
Sorry for the long delay. Are you still interested in testing your project on Bazel CI?

**Comment by btwiuse** [comment]
Sure, I'm still playing with Bazel and would like to further test it with Bazel CI. It would be great if it could be added. Thanks in advance!

**Comment by fweikert** [comment]
Created https://buildkite.com/bazel/btwiuse-k0s

Next steps:
1. Please send an email to the address in my profile, then I can send you instructions on how to set up GitHub integration via web hooks.
2. If you want Buildkite to update PRs with test results, please invite @bazel-io as collaborator.

**Comment by btwiuse** [comment]
Ok I'm closing this now that everything is working.

It would be nice if I can get a badge like this one here: https://raw.githubusercontent.com/bazelbuild/rules_proto/master/README.md

> * Postsubmit [![Build status](https://badge.buildkite.com/26d40f574d6f6026928bc271780782e5f168fe7e3595ea6d79.svg?branch=master)](https://buildkite.com/bazel/rules-proto)

Can you give me a link to the svg for my buildkite project?

The link should be like this:
```
https://badge.buildkite.com/26d40f574d6f6026928bc271780782e5f168fe7e3595ea6d79.svg?branch=master
```

**Comment by fweikert** [comment]
https://badge.buildkite.com/4be3caf595f18998bd63a201633a01b94c63e8d4c19f2a8920.svg
Adding a branch param will scope it to a particular branch (e.g. ?branch=main)
