### ISSUE TITLE
Buildifier support doesn't warn/error for files that need formatting

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#943]
Apparently the buildifier formatting as changed, but bazel_skylib was passing the buildifier step, but the truth was files needed reformatting (https://github.com/bazelbuild/bazel-skylib/pull/235).  Should the setup be catching this rather then silently rewriting the files and not reporting anything?

**Comment by thomasvl** [comment]
Looking at `--help`

```
  -mode string
    	formatting mode: check, diff, or fix (default fix)
```

So maybe passing `-mode=check` will get an error status instead?

**Comment by laurentlb** [comment]
cc @vladmos

**Comment by thomasvl** [comment]
Actually, it looks like maybe an attempt is run for this:

https://github.com/bazelbuild/continuous-integration/blob/67c573347144fe885ba563af0d7a68b8be2f8b8d/buildifier/buildifier.py#L205-L212

So maybe `-mode=check` is failing to report correctly?

**Comment by thomasvl** [comment]
Buildifier does get it right:

```
$ buildifier -mode=check -r . || echo nope
WORKSPACE # reformat callsort
internal_setup.bzl # reformat
lib/new_sets.bzl # reformat
lib/unittest.bzl # reformat
nope
```

So it is something on the CI side, looking at the past [skylib results](https://buildkite.com/bazel/bazel-skylib/builds/891#f3c77841-2870-4d00-b3a5-22f2364661c3), I'm not seeing the about put about downloading buildifier and running it either:

https://github.com/bazelbuild/continuous-integration/blob/67c573347144fe885ba563af0d7a68b8be2f8b8d/buildifier/buildifier.py#L241-L245

**Comment by thomasvl** [comment]
Got it, buildifier is reporting the files needed fixing to stderr, not stdout:

```
$ buildifier -mode=check -r .  > /dev/null
WORKSPACE # reformat callsort
internal_setup.bzl # reformat
lib/new_sets.bzl # reformat
lib/unittest.bzl # reformat
```

But https://github.com/bazelbuild/continuous-integration/blob/67c573347144fe885ba563af0d7a68b8be2f8b8d/buildifier/buildifier.py#L215 is checking stdout.

**Comment by vladmos** [comment]
The proper way to fix it is to add the information to the json object that Buildifier prints to stdout when called with `--format=json` (and also exit with 0 so that the caller can safely parse the output), I'll send a PR to buildifier.

**Comment by vladmos** [comment]
Apparently that's already implemented: if you call buildifier with `--mode=check --format-json` it will report `formatted: true|false` for each file.
