### ISSUE TITLE
bazel-bench failing with "Permission denied"

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#952]
https://buildkite.com/bazel/bazel-bench/builds/475#b86b2ae7-40d2-4f61-8b3f-64d3e67b6baf

bazel-bench is failing because its `//:benchmark_test` cannot create `/benchmark_test`. @joeleba, this may be a bug in the test, or may be an infrastructure error (hence filing the bug under this repo).

**Comment by joeleba** [comment]
Fixed with https://github.com/bazelbuild/bazel-bench/pull/92
