### ISSUE TITLE
CI using old Bazel commit

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/continuous-integration#956]
CI is using Bazel at an old commit, the commit being used is:
4019199bcf3646d6b0ae6475b3222e7e1fdf6617

After syncing and at the time of the build, there were 3 other commits after that one.

The build is here:
https://buildkite.com/bazel/google-rules-cc-presubmit/builds/314#bfdd5e55-d283-4145-b250-386497f21da7

**Comment by philwo** [comment]
This was due to a temporarily broken binary building pipeline in the trusted CI, which has been long fixed.
