### ISSUE TITLE
Use distributed caching on ci.bazel.io

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#97]
To speed up our build

**Comment by Mistobaan** [comment]
How do you configure distributed caching on Jenkins?  any guide?

**Comment by damienmg** [comment]
Jakob has a prototype to just spawn up his service as a docker container: https://github.com/buchgr/bazel-remote

**Comment by buchgr** [comment]
It's also on Dockerhub: https://hub.docker.com/r/buchgr/bazel-remote-cache/

**Comment by philwo** [comment]
@buchgr Can we enable your GCS based distributed cache for Jenkins CI?

**Comment by buchgr** [comment]
done on buildkite
