### ISSUE TITLE
Increase performance of CI builds

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#98]
So far a global tests takes around 1h30 minutes, most of it is taken from downstream jobs, the top 3 slowers are:

1. [TensorFlow](http://ci.bazel.io/job/Global/job/TensorFlow/workflow-stage/): ~1h15, capped by windows build (linux build is below 20 minutes)
2. [bazel-docker-tests](http://ci.bazel.io/job/Global/job/bazel-docker-tests/workflow-stage/): ~1h. 2 issues: all the tests are exclusive and non incremental (any change to bazel distribution artifact re-run all the tests)
3. [bazel-tests](http://ci.bazel.io/job/Global/job/bazel-tests/workflow-stage/): ~35min. Tests are 30minutes on all config, mostly capped by integration tests.

Project using TensorFlow are next on the lists.

Proposals:

1. Distributed caching (#97) should help a lot for 1 and 3 and all the other.
2. To reduce the whole pipeline, increasing our capacity should help: add 4 mac server and 4 windows to have all the fleet with 8 slaves of each. It should also decrease the pressure on CI during daytime in Europe when people use a lot CI.
3. For 1. we must make TF move out of the ugly CI Windows setup. /cc @meteorcloudy. At least we could trick a bit to reuse the local cache.
4. To reduce the cap time on 3, we could make integration tests not depends on packed bazel but instead on each tools directly, that would remove the ZIP phase from the tests but also we could make tests depends on only part of the tools instead. It would however increase the maintenance burden of those tests.
5. bazel-docker-tests time can only be reduced by sharding the tests among several workers, apart from using remote execution, the only way would be to create more jobs for now and manually shard those tests.

I believe we can easily goes to a Global test under 30 minutes if we do all that.

/cc @buchgr @aehlig @ulfjack FYI

**Comment by damienmg** [comment]
Also we need to investigate why some mac build are super slow (over an hour): http://ci.bazel.io/job/Global/job/bazel-tests/112/console

We should add --profile to bazel-tests.json so we can get the profile file right after the problem.

**Comment by meteorcloudy** [comment]
As for the TensorFlow Windows build, with 0.5.3 I think we can remove `bazel clean --expunge` then it should be much faster.

**Comment by damienmg** [comment]
So our capacity increase and the split of CI helped a lot. TF on Windows was deactivated because it was always failing, TF is now down at 15min.

Splitting the docker tests right now which is the cap.

**Comment by damienmg** [comment]
docker-tests is 28 min now, we can split it further if needed, maybe we should move some more tests to that post-submit job (e.g. determinism test)?

**Comment by meteorcloudy** [comment]
Sounds good to me.

**Comment by damienmg** [comment]
Some more sources of slowness: stashing or archiving bazel takes 5min sometime. Can we make that faster? This is network communication of ~200M in between GCE machines...

**Comment by damienmg** [comment]
https://github.com/jenkinsci/workflow-basic-steps-plugin/commit/413df48bdcb832261e8fb110150eeb8069e77c33 Seems to recommend not using stash...

**Comment by philwo** [comment]
Performance recently seems fine to me. I've reduced our slave count by half and instead bumped the instance types up one notch to 32 cores, 128 GB RAM and will also enable using a local SSD for increased I/O performance.
