### ISSUE TITLE
Request to add new project toxicity-detector

### ISSUE THREAD

**Issue by sophieball** [bazelbuild/continuous-integration#986]
- I want to test the following project on Bazel CI: https://github.com/sophieball/toxicity-detector
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by fweikert** [comment]
Sorry for the long delay. Are you still interested in testing your project on Bazel CI?

**Comment by sophieball** [comment]
Ah! I don't need it anymore. Sorry that I forgot to close this. Thanks for following up!
