### ISSUE TITLE
Pipeline bazelisk-plus-incompatible-flags has buggy page

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/continuous-integration#987]
See https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/542
Many flags are repeated 30 times on the page, which makes it hard to read.

**Comment by meteorcloudy** [comment]
This pipeline went completely crazy... But we didn't make any significant change to our CI scripts, will do some investigation today!

**Comment by meteorcloudy** [comment]
OK, I found the root cause is because we don't have `migration-3.3` label on github. @laurentlb, do you know why we didn't label the incompatible flags in bazel 3.3?

**Comment by meteorcloudy** [comment]
I'll fix the CI build script to make sure it doesn't fall apart when no incompatible flags are found on github.

**Comment by laurentlb** [comment]
@katre

**Comment by katre** [comment]
When I was preparing the release, I searched for [`is:issue is:open breaking-change-3.3`](https://github.com/bazelbuild/bazel/issues?q=is%3Aissue+is%3Aopen+breaking-change-3.3), which returned zero issues, so I didn't bother creating the new label. I didn't realize this would break the CI pipeline. Should we update the [release playbook](https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md#update-the-status-of-github-issues-for-incompatible-changes) to clarify that the `migration-X.Y` label always needs to exist?

**Comment by katre** [comment]
Although now that I look again, I should have added that label for everything with `breaking-change-4.0`, as well, so I will add the label now.

**Comment by katre** [comment]
I have created the label and applied it.

**Comment by laurentlb** [comment]
Thanks!

As we do breaking changes only for major releases, we should have only breaking-X.0 labels (not 3.3). Yes, please update the playbook.
